### ISSUE TITLE
[Elastic Cache Parameter Group] Parameter group not creating resources if "external-name" is set (0.44)

### ISSUE THREAD

**Issue by WolfGanGeRTech** [crossplane-contrib/provider-upjet-aws#1005]
### What happened?

The ParameterGroup.elasticache.aws.upbound.io/v1beta1 is not able to create new resources if "external-name" annotation is set. 

It should first check if the resource exists and if not, create it, but when "external-name" is set he only tries to check if it exists and fails if it doesn't. The error returned is:

```
 Warning  CannotObserveExternalResource  4s (x4 over 9s)  managed/elasticache.aws.upbound.io/v1beta1, kind=parametergroup  failed to observe the resource: [{0 unable to find ElastiCache Parameter Group (testingcachebug): couldn't find resource  []}]
```

### How can we reproduce it?

```yaml
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ParameterGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1beta1/parametergroup
    crossplane.io/external-name: testingcachebug
  labels:
    testing.upbound.io/example-name: testingcachebug
  name: testingcachebug
spec:
  deletionPolicy: "Orphan"
  forProvider:
    family: redis2.8
    name: testingcachebug
    parameter:
      - name: min-slaves-to-write
        value: "2"
    region: eu-central-1
```

Just use this manifest and the error will occour.

### What environment did it happen in?

* Crossplane Version: 1.12.2
* Provider Version: 0.44 (aws-provider-cache)
* Kubernetes Version: 1.25 
* Kubernetes Distribution: AWS

**Comment by WolfGanGeRTech** [comment]
Any update?

**Comment by turkenf** [comment]
Hi @WolfGanGeRTech,

Could not reproduce with provider version `0.47.1`, please try and let us know.
```
NAME                                                        READY   SYNCED   EXTERNAL-NAME     AGE
parametergroup.elasticache.aws.upbound.io/default           True    True     cache-params      10m
parametergroup.elasticache.aws.upbound.io/testingcachebug   True    True     testingcachebug   44s
```

**Comment by WolfGanGeRTech** [comment]
Hello,

I have tested again with 0.47.1 and same issue.

The manifest I used was:

```yaml
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ParameterGroup
metadata:
  annotations:
    crossplane.io/external-name: cache-params9
  name: cache-params9
spec:
  deletionPolicy: Orphan
  forProvider:
    family: redis7
    name: cache-params9
    region: eu-central-1
```

When I describe the resource I get:

```
Name:         cache-params9
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-name: cache-params9
API Version:  elasticache.aws.upbound.io/v1beta1
Kind:         ParameterGroup
Metadata:
  Creation Timestamp:  2024-02-01T09:38:48Z
  Generation:          2
  Resource Version:    478050855
  UID:                 f52bfb23-bf2e-43e6-9d09-57a6aae1877e
Spec:
  Deletion Policy:  Orphan
  For Provider:
    Family:  redis7
    Name:    cache-params9
    Region:  eu-central-1
    Tags:
      Crossplane - Kind:            parametergroup.elasticache.aws.upbound.io
      Crossplane - Name:            cache-params9
      Crossplane - Providerconfig:  default
  Init Provider:
  Management Policies:
    *
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2024-02-01T09:38:57Z
    Message:               observe failed: failed to observe the resource: [{0 unable to find ElastiCache Parameter Group (cache-params9): couldn't find resource  []}]
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                         Age                From                                                             Message
  ----     ------                         ----               ----                                                             -------
  Warning  CannotObserveExternalResource  11s (x2 over 13s)  managed/elasticache.aws.upbound.io/v1beta1, kind=parametergroup  failed to observe the resource: [{0 unable to find ElastiCache Parameter Group (cache-params9): couldn't find resource  []}]
```

Since he can't find the resource he should create one.
