### ISSUE TITLE
Issue with KMS Key Policy Creation

### ISSUE THREAD

**Issue by nc-rajeshnair** [crossplane-contrib/provider-upjet-aws#1011]
**Composition**
```
#Create an IAM Role for custom KMS Grant used by Ecommerce DB
    - name: kms-db-iam-role          
      base: 
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: Role
        metadata:
          name: kms-db2-role
          annotations:
            crossplane.io/external-name: kms-db2-role
          labels:
            name: kms-db2-role
        spec:
          providerConfigRef:
            name: default
          forProvider:
            region: us-east-1
            assumeRolePolicy: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "rds.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                  }
                ]
              }
        patches:
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.arn
            toFieldPath: status.iam.grant.arn
#Create a custom KMS for Ecommerce DB
    - name: ecom-db-kms
      base:
        apiVersion: kms.aws.upbound.io/v1beta1
        kind: Key
        metadata:
          name: kms-db2-key
          annotations:
            meta.upbound.io/example-id: rds/v1beta1/instance
          labels:
            name: kms-db2-key
        spec:
          providerConfigRef:
            name: default
          deletionPolicy: Delete  
          forProvider:
            region: us-east-1
            deletionWindowInDays: 7
            description: Custom KMS for Ecommerce DB
            tags:
              Name: kms-db2-key
              Env: Development
              region: us-east-1          
        patches:
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.Arn
            toFieldPath: status.kms.kmsArn     
            policy:
              fromFieldPath: Required  
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.keyId
            toFieldPath: status.kms.kmsKeyId     
            policy:
              fromFieldPath: Required                               
#Create an Alias for Ecommerce DB Custom KMS 
    - name: ecom-db-kms-alias          
      base: 
        apiVersion: kms.aws.upbound.io/v1beta1
        kind: Alias
        metadata:
          name: kms-db2-alias  
          annotations:
            crossplane.io/external-name: kms-db2-alias   
          labels:
            name: kms-db2-alias
        spec:
          providerConfigRef:
            name: default
          deletionPolicy: Delete  
          
          forProvider:
            region: us-east-1
            targetKeyId:
            targetKeyIdSelector:
              matchLabels:
                 name: kms-db2-key

        patches:
           - type: FromCompositeFieldPath
             fromFieldPath: status.kms.kmsArn
             toFieldPath: spec.forProvider.targetKeyId
             policy:
                fromFieldPath: Required  
#Create a KMS Grant for Ecommerce DB
    - name: ecom-db-kms-grant          
      base: 
        apiVersion: kms.aws.upbound.io/v1beta1
        kind: Grant
        metadata:
          name: kms-db2-key-kms-db2-kms-grant  
          annotations:
            crossplane.io/external-name: kms-db2-kms-grant   
          labels:
            name: kms-db2-kms-grant 
        spec:
          providerConfigRef:
            name: default
          forProvider:
            region: us-east-1
            keyId:
            keyIdSelector:
              matchLabels:
                name: kms-db2-key            
            granteePrincipalSelector:
              matchLabels:
                name: kms-db2-role            
            operations:
              - Encrypt
              - Decrypt
              - GenerateDataKey
              - DescribeKey
        patches:
           - type: FromCompositeFieldPath
             fromFieldPath: status.kms.kmsKeyId
             toFieldPath: spec.forProvider.keyId  
             policy:
                fromFieldPath: Required
```
**CompositeResourceDefinition**
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkmss.platformref.crossplane.io
  annotations:
      argocd.argoproj.io/sync-wave: "2"  
      helm.sh/hook-weight: "2"
      helm.sh/hook: post-install
spec:
  group: platformref.crossplane.io
  names:
    kind: XKms
    plural: xkmss
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:           
            status:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    currentCanonicalId:
                      type: string
                kms:
                  type: object
                  properties:
                    kmsId:
                      type: string
                    kmsArn:
                      type: string
                    kmsKeyId:
                      type: string 
                iam:
                  type: object
                  properties:
                    userPolicy:
                      type: object
                      properties:
                        arn:
                          type: string
                    grant:
                      type: object
                      properties:
                        arn:
                          type: string
                        id:
                          type: string
```
**ERROR**
```
91s (x175 over 4h2m)     Warning  CannotObserveExternalResource  Grant/aws-resource-claim-l5twr-48q92                                    failed to observe the resource: [{0 parsing resource ID: unexpected format of ID ("ecom-db-kms-grant"), expected KeyID:GrantID []}
```
**Status**
```

Spec:
  Deletion Policy:  Delete
  For Provider:
    Grantee Principal:  arn:aws:iam::029425502293:role/kms-db2-role
    Grantee Principal Ref:
      Name:  rds-composite-resource-mghx6
    Grantee Principal Selector:
      Match Labels:
        Name:  kms-db2-role
    Key Id:    arn:aws:kms:us-east-1:029425502293:key/ec83578b-18cb-47c2-a72e-b92bee8e27b0
    Key Id Ref:
      Name:  rds-composite-resource-q89sv
    Key Id Selector:
      Match Labels:
        Name:  kms-db2-key
    Operations:
      Encrypt
      Decrypt
      GenerateDataKey
      DescribeKey
    Region:  us-east-1
  Init Provider:
  Management Policies:
    *
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2023-12-06T10:34:58Z
    Message:               observe failed: failed to observe the resource: [{0 parsing resource ID: unexpected format of ID ("kms-db2-kms-grant"), expected KeyID:GrantID  []}]
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                           Age                    From                                            Message
  ----     ------                           ----                   ----                                            -------
  Warning  CannotResolveResourceReferences  7m14s (x4 over 7m21s)  managed/kms.aws.upbound.io/v1beta1, kind=grant  cannot resolve references: mg.Spec.ForProvider.KeyID: referenced field was empty (referenced resource may not yet be ready)
  Warning  CannotObserveExternalResource    45s (x22 over 7m5s)    managed/kms.aws.upbound.io/v1beta1, kind=grant  failed to observe the resource: [{0 parsing resource ID: unexpected format of ID ("kms-db2-kms-grant"), expected KeyID:GrantID  []}]
```
### What environment did it happen in?

* Crossplane Version: v1.14
* AWS Provider Version: v.045.0

**Comment by haarchri** [comment]
think the external-name is not correct:

```
        kind: Grant
        metadata:
          name: kms-db2-key-kms-db2-kms-grant  
          annotations:
            crossplane.io/external-name: kms-db2-kms-grant    # <-- remove this in your composition
```
