### ISSUE TITLE
SecurityGroupRule: Drift Remediation is not working in SecurityGroupRule resource in Upbound AWS provider.

### ISSUE THREAD

**Issue by infa-msheik** [crossplane-contrib/provider-upjet-aws#104]
Whenever I modify SecurityGroupRule Resource Cidr, Description, Port directly in the AWSconsole,  Crossplane upbound provider  instead of remediating the drift it is creating the new Rule with old values in the k8 yaml.

When updating the Port it is showing the resource requires replacement error.
```
managed/ec2.aws.upbound.io/v1beta1, kind=securitygrouprule  cannot run plan: plan failed: Instance cannot be destroyed: Resource aws_security_group_rule.test-sgrule-up has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

Yaml Used:
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: test-sgrule-up
spec:
  deletionPolicy: Delete
  forProvider: 
    description: "crossplane testing sg rule"
    fromPort: 80
    protocol: "tcp"
    toPort: 80
    type: "ingress"
    cidrBlocks: 
    - "10.0.0.0/8"
    region: us-west-2
    securityGroupIdRef:
      name: "test-sg-up"                                   
  providerConfigRef:
    name: default
```
