### ISSUE TITLE
LaunchTemplate Versions Getting created automatically without any change in the k8 yaml.

### ISSUE THREAD

**Issue by infa-msheik** [crossplane-contrib/provider-upjet-aws#105]
New versions being created while no changes to the object

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: test-lt-up
spec:
  deletionPolicy: Delete
  forProvider: 
    monitoring: 
    - enabled: false  
    region: us-west-2
    iamInstanceProfile: 
    - name: xxx_xxxxx         
    imageId: "ami-xxxxxxxxxxx"
    instanceType: "t2.micro"
    networkInterfaces: 
    - associatePublicIpAddress: "false"
      securityGroups:
      - "sg-xxxxxxxxxxxxxxxxx"
      - "sg-xxxxxxxxxxxxxxxxx"          
    name: "test-lt-up"
    userData: |
      xxxxxxxxxxxxxxxxxxxxxxxxxxJIiBLxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    tagSpecifications:
    - resourceType: instance
      tags:
        BU: "test"  
        BE: "Infra"     
    - resourceType: volume
      tags:
        BU: "test"  
        BE: "Infra"        
    keyName: "test.pem"       
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
      - volumeSize: 20
        volumeType: "gp3"                                      
  providerConfigRef:
    name: default
```
```
k describe launchtemplate.ec2.aws.upbound.io/test-lt-up
Name:         test-lt-up
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2022-10-29T07:08:57Z
              crossplane.io/external-create-succeeded: 2022-10-29T07:08:57Z
              crossplane.io/external-name: lt-xxxxxxxxxxxxxxxx
              upjet.crossplane.io/provider-meta: null
API Version:  ec2.aws.upbound.io/v1beta1
Kind:         LaunchTemplate
Spec:
  Deletion Policy:  Delete
  For Provider:
    Block Device Mappings:
      Device Name:  /dev/xvda
      Ebs:
        Volume Size:  20
        Volume Type:  gp3
    Default Version:  1
    Iam Instance Profile:
      Name:         xxxxxxxxxxxxxxxx
    Image Id:       ami-xxxxxxxxxxxxxxxx
    Instance Type:  t2.micro
    Key Name:       xxxxxxxxxxxxxxxx.pem
    Monitoring:
      Enabled:  false
    Name:      test-lt-up
    Network Interfaces:
      Associate Public Ip Address:  false
      Security Groups:
        sg-xxxxxxxxxxxxxxxx
        sg-xxxxxxxxxxxxxxxx
    Region:  us-west-2
    Tag Specifications:
      Resource Type:  instance
      Tags:
        BE:           Infra
        BU:           test
      Resource Type:  volume
      Tags:
        BE:  Infra
        BU:  test
    Tags:
      Crossplane - Kind:            launchtemplate.ec2.aws.upbound.io
      Crossplane - Name:            test-lt-up2
      Crossplane - Providerconfig:  default
    User Data:                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Arn:             arn:aws:ec2:us-west-2:xxxxxxxxxxxxxxxx:launch-template/lt-xxxxxxxxxxxxxxxx
    Id:              lt-xxxxxxxxxxxxxxxx
    Latest Version:  3
    Tags All:
      Crossplane - Kind:            launchtemplate.ec2.aws.upbound.io
      Crossplane - Name:            test-lt-up
      Crossplane - Providerconfig:  default
  Conditions:
    Last Transition Time:  2022-10-29T07:09:22Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-10-29T07:08:57Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2022-10-29T07:09:09Z
    Reason:                Success
    Status:                True
    Type:                  LastAsyncOperation
    Last Transition Time:  2022-10-29T07:10:39Z
    Reason:                Finished
    Status:                True
    Type:                  AsyncOperation
Events:
  Type    Reason                   Age               From                                                     Message
  ----    ------                   ----              ----                                                     -------
  Normal  CreatedExternalResource  117s              managed/ec2.aws.upbound.io/v1beta1, kind=launchtemplate  Successfully requested creation of external resource
  Normal  UpdatedExternalResource  6s (x3 over 71s)  managed/ec2.aws.upbound.io/v1beta1, kind=launchtemplate  Successfully requested update of external resource
```
<img width="1388" alt="Screenshot 2022-10-29 at 12 46 30 PM" src="https://user-images.githubusercontent.com/112253650/198963858-dd437fd6-cc0a-4cf6-9167-71638b4617f2.png">
<img width="1342" alt="Screenshot 2022-10-29 at 12 49 42 PM" src="https://user-images.githubusercontent.com/112253650/198963926-ef0dc91e-0cb8-4d6c-94ec-fd0388ec2458.png">
