### ISSUE TITLE
NodeGroup cannot be created without the desired size and launch template version

### ISSUE THREAD

**Issue by idanshaby** [crossplane-contrib/provider-upjet-aws#1050]
### What happened?
I am able to create an EKS node group by applying the following yaml:
```
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: control-plane-node-group
spec:
  forProvider:
    ...
    launchTemplate:
      - name: workload-cluster-1-launch-template
    scalingConfig:
      - maxSize: 10
        minSize: 1
  initProvider:
    scalingConfig:
      - desiredSize: 1
```
However, when I try to apply the following object using upbound SDK (0.46.1):
```
eksNodeGroup := eks.NodeGroup{
		TypeMeta: apimachineryv1.TypeMeta{Kind: "NodeGroup", APIVersion: internal.UpboundEKSAPIVersion},
		ObjectMeta: ...
		Spec: eks.NodeGroupSpec{
			ForProvider: eks.NodeGroupParameters{
				...
				LaunchTemplate: []eks.LaunchTemplateParameters{
					{
						Name:    <name>,
					},
				},
				ScalingConfig: []eks.ScalingConfigParameters{
					{
						MaxSize: <value>,
						MinSize: <value>,
					},
				},
			},
			InitProvider: eks.NodeGroupInitParameters{
				ScalingConfig: []eks.ScalingConfigInitParameters{
					{
						DesiredSize: <value>,
					},
				},
			},
		},
	}
```
it fails with the following error:
```
"error": "NodeGroup.eks.aws.upbound.io \"workload-cluster-1-control-plane-node-group\" is invalid: [spec.forProvider.launchTemplate[0].version: Invalid value: \"null\": spec.forProvider.launchTemplate[0].version in body must be of type string: \"null\", spec.forProvider.scalingConfig[0].desiredSize: Invalid value: \"null\": spec.forProvider.scalingConfig[0].desiredSize in body must be of type number: \"null\", <nil>: Invalid value: \"null\": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]"
```
Looking at the code, I see that the version of the launch template as well as the desired size of the scaling config (both under the ForProvider field) lack the json `omitempty` tag, although they do contain it under the terraform tag. Maybe it should be added.

### What environment did it happen in?

* Crossplane Version: 1.14.5
* Provider Version: 0.46.1
* Kubernetes Version:
Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.2
* Kubernetes Distribution: EKS
