### ISSUE TITLE
Request for `SupportCase` resource

### ISSUE THREAD

**Issue by lewyg** [crossplane-contrib/provider-upjet-aws#1051]
### What resource do you need?

Terraform Resource Name:  resource does not exist in Terraform provider-aws

### What is your use case?

Hey, in our team we want to automate the process of adding accounts to Enterprise Support plan. This is done by creating a Support Case for AWS support team. Currently, there is no resource for SupportCase, and we have to use AWS API calls to do so.

Could you create a new resource for the creation of AWS Support Case ([API](https://docs.aws.amazon.com/awssupport/latest/user/about-support-api.html))?

API:
- [CreateCase](https://docs.aws.amazon.com/awssupport/latest/APIReference/API_CreateCase.html)
- [DescribeCases](https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeCases.html)

The resource may support only the creation of cases without attachments. 

The resource may look like:

```yaml
---
apiVersion: support.aws.upbound.io/v1beta1
kind: SupportCase
metadata:
  name: support-case-1
spec:
  forProvider:
    subject:  # string
    serviceCode:  # string
    severityCode:  # string
    categoryCode:  # string
    communicationBody:  # string
    ccEmailAddresses:  # array[string]
    language:  # string
    issueType:  # string
  providerConfigRef:
    name:
```
