### ISSUE TITLE
nil pointer dereference in Autoscaling attachment

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane-contrib/provider-upjet-aws#1062]
### What happened?

When creating an autoscaling attachment with a minimal `forProvider`, the provider will crash with a nil pointer dereference:

```
xb", "gvk": "autoscaling.aws.upbound.io/v1beta1, Kind=Attachment"}
2024-01-03T23:10:02Z	DEBUG	provider-aws	Async create starting...	{"trackerUID": "36fcfc55-92e7-4562-bf33-a491a42e67ab", "resourceName": "dms-k8s-ddm-97cnf-9x4xb", "tfID": ""}
2024-01-03T23:10:02Z	DEBUG	provider-aws	Creating the external resource	{"uid": "36fcfc55-92e7-4562-bf33-a491a42e67ab", "name": "dms-k8s-ddm-97cnf-9x4xb", "gvk": "autoscaling.aws.upbound.io/v1beta1, Kind=Attachment"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x16dc16a]

goroutine 4598 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0011120e0, {0x12dd8228, 0xc00bafdb90}, 0x0, 0x0, {0x10f83600, 0xc00c820000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:779 +0x14a
github.com/crossplane/upjet/pkg/controller.(*noForkExternal).Create(0xc006921110, {0x12dd8228, 0xc00bafdb90}, {0x12e2ecd0?, 0xc00ba66a00})
	github.com/crossplane/upjet@v1.1.0-rc.0.0.20231227120826-4cb45f9104ac/pkg/controller/external_nofork.go:574 +0xe4
github.com/crossplane/upjet/pkg/controller.(*noForkAsyncExternal).Create.func1()
	github.com/crossplane/upjet@v1.1.0-rc.0.0.20231227120826-4cb45f9104ac/pkg/controller/external_async_nofork.go:137 +0x145
created by github.com/crossplane/upjet/pkg/controller.(*noForkAsyncExternal).Create in goroutine 3638
	github.com/crossplane/upjet@v1.1.0-rc.0.0.20231227120826-4cb45f9104ac/pkg/controller/external_async_nofork.go:133 +0x168
```

### How can we reproduce it?

Use the following attachment file, which is accepted by the API server:

```yaml
apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: Attachment
metadata:
  name: dms-k8s-ddm-97cnf-9x4xb
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
```

### What environment did it happen in?

* Crossplane Version: 1.14.5
* Provider Version: v0.47.1
* Kubernetes Version: 1.29
* Kubernetes Distribution: Kind
