### ISSUE TITLE
Custom annotations and labels for AWS family provider pod

### ISSUE THREAD

**Issue by pierluigilenoci** [crossplane-contrib/provider-upjet-aws#1088]
### What problem are you facing?

When a provider in the AWS family is created, a further pod is created, but it is impossible to define specific labels or annotations for this pod.

### How could an Official AWS Provider help solve your problem?

I want to specify labels/annotations for that pod.

**Comment by pierluigilenoci** [comment]
@turkenf, could you please take a look?

**Comment by turkenf** [comment]
Hi @pierluigilenoci,

- You can add the `spec.skipDependencyResolution: true` configuration to create the automatically created family provider yourself, please check [here](https://docs.upbound.io/providers/provider-families/#installing-a-provider-family:~:text=services%20to%20install.-,Install%20Providers%20in%20an%20offline%20environment,-View%20the%20installed)
- You can use `DeploymentRuntimeConfig` to add labels and annotations to the provider pods, please check [here](https://docs.crossplane.io/v1.14/concepts/providers/#runtime-configuration)

For example, you can try the sample YAML file below to add labels to the pods of the s3 family provider.
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-s3
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:v0.47.1
  skipDependencyResolution: true
  runtimeConfigRef:
    name: my-runtime-config
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v0.47.1
  runtimeConfigRef:
    name: my-runtime-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: my-runtime-config
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        metadata:
          labels:
            my-label: my-value

```
