### ISSUE TITLE
Data provider for AWS Route53 resolver rules

### ISSUE THREAD

**Issue by Donimax** [crossplane-contrib/provider-upjet-aws#1099]
### What problem are you facing?
In order to deploy a new VPC in our customer environment, we need to retrieve rout53 resolver rule ids from another account to associate them with the new account. We currently use the Terraform provider to retrieve this data and patch it to ZoneAssociation.route53resolver.aws.upbound.io/v1beta1.

### How could Official AWS Provider help solve your problem?
For getting a data resource like in terraform for AWS provider we can do all steps in AWS provider native.

**Comment by ytsarev** [comment]
Can you please share example of provider-terraform code you are using to do so?

**Comment by Donimax** [comment]
```yaml
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: r53-resolver-rules
            base:
              apiVersion: tf.upbound.io/v1beta1
              kind: Workspace
              metadata:
                name: data-source-route53-resolver-rules
              spec:
                forProvider:
                  source: Inline
                  module: |
                    data "aws_route53_resolver_rules" "resolver_rules" {
                      for_each     = toset(var.dns_rules_match)
                      rule_type    = "FORWARD"
                      share_status = "SHARED_WITH_ME"
                      owner_id     = var.shared_services_acc_id
                      name_regex   = each.key
                    }
                    output "aws_route53_resolver_rules_data" {
                      description = "Imported Route53 reslover rules"
                      value       = distinct(flatten([
                        for rule in data.aws_route53_resolver_rules.resolver_rules:
                          rule.resolver_rule_ids
                      ]))
                    }
                    variable "shared_services_acc_id" {
                      description = "Shared services account ID for DNS"
                      type        = string
                    }
                    variable "dns_rules_match" {
                      description = "List of route53 regex rules"
                      type        = list(string)
                    }
                  vars:
                    - key: shared_services_acc_id
                  varmap:
                    dns_rules_match:
                providerConfigRef:
                  name: tf-provider-config-aws-iam
            patches:
              - fromFieldPath: spec.sharedServicesAccId
                toFieldPath: spec.forProvider.vars[0].value
              - fromFieldPath: spec.dnsRulesMatch
                toFieldPath: spec.forProvider.varmap.dns_rules_match
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.outputs.aws_route53_resolver_rules_data
                toFieldPath: status.share.r53ResolverRulesData
```
