### ISSUE TITLE
PodIdentityAssociation should prefer to derive the region information from the Cluster referenced

### ISSUE THREAD

**Issue by danielloader** [crossplane-contrib/provider-upjet-aws#1168]
### What problem are you facing?

Looking at the example contract:

```yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/podidentityassociation
  labels:
    testing.upbound.io/example-name: example-pia
  name: example-pia
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-pia
    namespace: example
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example-pia
    serviceAccount: default
```

You have to provide the region in addition to the cluster name (by means of a `clusterNameRef` or `clusterNameSelector` lookup) but the region the cluster is in is found in this object, which makes it more fragile to have to define it in isolation in an additional field.

This could be taken from either: 
``` yaml
status:
  atProvider:
    arn: arn:aws:eks:eu-west-2:012345678901:cluster/example
```

or:

``` yaml
spec:
  forProvider:
    region: eu-west-2
```

### How could Official AWS Provider help solve your problem?

Make the region field optional as an override, if not populated, pull it from the cluster XR referenced.
