### ISSUE TITLE
Provide more flexible ways to set tags

### ISSUE THREAD

**Issue by mbbush** [crossplane-contrib/provider-upjet-aws#1173]
### What problem are you facing?
I would like to be able to apply certain tags to large groups of my managed resources, without having to add patches everywhere, similar to terraform's concept of default tags.

### How could Official AWS Provider help solve your problem?
Adding a new field to the `ProviderConfig` schema could provide a way to allow users to specify this. It could also provide a way for users to opt out of the default tags, as requested in #1141.

### Proposed schema
I'm sure this could be improved, but here's a rough idea
```
spec:
  resourceTagging:
    userDefined:
      team: blue
      managed-by: crossplane
      reconciled: continuously
    builtIn:
      disabled:
        - crossplane-kind
        - crossplane-name
        - crossplane-provider-config
```
This would disable the three built-in tags, and add three additional user-defined tags to every resource which uses this providerconfig. It could provide a mechanism for introducing additional built in tags in an opt-in manner, and allow practitioners to apply different tagging configs to different groups of resources by managing different provider configs. 

Additionally, while about 2/3 of the provider-aws resources have a `spec.forProvider.tags`, _all_ of them have a `spec.providerConfigRef.name`, so I can write a template/composition/function/whatever to always set the provider config, without needing to know which resources support tags and which don't. 

### Related functionality
Some things this might impact or relate to, that would need some work to determine how/whether to handle:
* The fact that various `tags` fields have special code for handling them in upjet, even though they only apply to provider-aws
* The way we handle tags vs tags_all
