### ISSUE TITLE
[Bug]: external-name can't be set on Instance.rds.aws.upbound.io/v1beta1

### ISSUE THREAD

**Issue by mlubanski** [crossplane-contrib/provider-upjet-aws#1185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

`rds.aws.upbound.io/v1beta1` - `Instance`

### Resource MRs required to reproduce the bug

```
apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    crossplane.io/external-name: eu1lab-eks001-default-mysql-1
  name: mysql-1-d6msv-q7h8m
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 20
    applyImmediately: false
    autoMinorVersionUpgrade: true
    availabilityZone: eu-west-1b
    backupRetentionPeriod: 0
    backupWindow: 14:00-16:00
    caCertIdentifier: rds-ca-rsa2048-g1
    copyTagsToSnapshot: true
    dbSubnetGroupName: private_net_vpc-***
    deleteAutomatedBackups: true
    enabledCloudwatchLogsExports:
    - audit
    engine: mysql
    engineVersion: 8.0.35
    instanceClass: db.t4g.small
    iops: 3000
    licenseModel: general-public-license
    maintenanceWindow: Mon:11:00-Mon:14:00
    manageMasterUserPassword: true
    maxAllocatedStorage: 1000
    multiAz: false
    networkType: IPV4
    optionGroupName: default-mysql-8-0
    parameterGroupName: eu1lab-eks001-default-mysql-1
    performanceInsightsEnabled: false
    port: 3306
    publiclyAccessible: false
    region: eu-west-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageThroughput: 125
    storageType: gp3
    username: root
    vpcSecurityGroupIds:
    - sg-06d7ecbe89aabc75a
    - sg-048580a25883584ad
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: upbound-provider-aws
  publishConnectionDetailsTo:
    configRef:
      name: default
    metadata:
      labels:
        secret.crossplane.io/owner-uid: 98f13eb9-d748-4787-b0ba-bec432febf2d
    name: default-mysql-1-rdsinstance
```

### Steps to Reproduce

create `Instance` ManagedResource with custom custom name set by `crossplane.io/external-name: eu1lab-eks001-default-mysql-1` annotation

### What happened?

During above MR creation in console I was able see in EXTERNAL-NAME column `mysql-1-d6msv-q7h8m` name
In AWS Resource was named: `terraform-20240301080146611000000001`
After resource was successfully provisioned in AWS, crossplane changed value of `crossplane.io/external-name` to `db-EZPPTHUGTJANNMPS7SMQI4QGYE` (In AWS Console this value is visible as `ResourceID`)

### Crossplane Version

1.15.1

### Provider Version

1.1.0

### Kubernetes Version

1.27.x

### Kubernetes Distribution

local/kind

**Comment by shxdxwraze** [comment]
We have the same behaviour

**Comment by shxdxwraze** [comment]
https://doc.crds.dev/github.com/upbound/provider-aws/rds.aws.upbound.io/Instance/v1beta2@v1.2.1#spec-forProvider-identifier
@mlubanski try this

**Comment by alexrygalov** [comment]
@shxdxwraze thx, worked for me.
However if you describe the managed resource the external-name is still generated by crossplane.
```yaml
apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: aleks-test-01
spec:
  providerConfigRef:
    name: provider-aws
  forProvider:
    identifier: aleks-test-01
```

```bash
k get managed

NAME                                        SYNCED   READY   EXTERNAL-NAME                   AGE
instance.rds.aws.upbound.io/aleks-test-01   True     True    db-IZ3A2WLOJTEG4HBTMMJJXH4ELQ   8m2s
```
