### ISSUE TITLE
[Bug]: Instance.rds.aws.upbound.io/v1beta1 - Invalid master password

### ISSUE THREAD

**Issue by mlubanski** [crossplane-contrib/provider-upjet-aws#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

`rds.aws.upbound.io/v1beta1` - `Instance`

### Resource MRs required to reproduce the bug

```
apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    crossplane.io/external-name: eu1lab-eks001-default-mysql-1
  name: mysql-1-d6msv-q7h8m
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 20
    applyImmediately: false
    autoMinorVersionUpgrade: true
    availabilityZone: eu-west-1b
    backupRetentionPeriod: 0
    backupWindow: 14:00-16:00
    caCertIdentifier: rds-ca-rsa2048-g1
    copyTagsToSnapshot: true
    dbSubnetGroupName: private_net_vpc-***
    deleteAutomatedBackups: true
    enabledCloudwatchLogsExports:
    - audit
    engine: mysql
    engineVersion: 8.0.35
    instanceClass: db.t4g.small
    iops: 3000
    licenseModel: general-public-license
    maintenanceWindow: Mon:11:00-Mon:14:00
    autoGeneratePassword: true
    maxAllocatedStorage: 1000
    multiAz: false
    networkType: IPV4
    optionGroupName: default-mysql-8-0
    parameterGroupName: eu1lab-eks001-default-mysql-1
    performanceInsightsEnabled: false
    port: 3306
    publiclyAccessible: false
    region: eu-west-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageThroughput: 125
    storageType: gp3
    username: root
    vpcSecurityGroupIds:
    - sg-06d7ecbe89aabc75a
    - sg-048580a25883584ad
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: upbound-provider-aws
  publishConnectionDetailsTo:
    configRef:
      name: default
    metadata:
      labels:
        secret.crossplane.io/owner-uid: 98f13eb9-d748-4787-b0ba-bec432febf2d
    name: default-mysql-1-rdsinstance
```

### Steps to Reproduce

apply Instance `ManagedResource` with property `autoGeneratePassword: true`

### What happened?

Error during ManagedResource creation:
```
│   - lastTransitionTime: "2024-03-01T08:48:04Z"                                                                     │
│     message: "async create failed: failed to create the resource: [{0 creating RDS                                 │
│       DB Instance (terraform-20240301084804223200000005): InvalidParameterValue: Invalid                           │
│       master password\n\tstatus code: 400, request id: a006ee1c-2814-42d8-8f37-14c3fb3140d5                        │
│       \ []}]"
```

### Crossplane Version

1.15.0

### Provider Version

1.1.0

### Kubernetes Version

1.17.x

### Kubernetes Distribution

local/kind

### Additional Info

```
apiVersion: aws.upbound.io/v1alpha1
kind: StoreConfig
metadata:
  name: default
spec:
  defaultScope: crossplane-system
  type: Kubernetes
```

**Comment by davimmt** [comment]
It might seem redundant, but you have to specify both `.spec.publishConnectionDetailsTo`  and `.spec.forProvider.passwordSecretRef` as such:

```yaml
apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
...
spec:
  forProvider:
    ...
    passwordSecretRef:
      key: password
      name: XXX
      namespace: YYY
    ....
  publishConnectionDetailsTo:
    name: XXX
    ....
```

Note that using  `.spec.writeConnectionSecretToRef` instead of the `.spec.publishConnectionDetailsTo` gives me the following error:
```
managed/rds.aws.upbound.io/v1beta2, kind=instance  cannot create or update connection secret: refusing to modify uncontrolled secret of type "Opaque"
```
