### ISSUE TITLE
[Bug]: Instance.rds.aws.upbound.io/v1beta1 - password is not propagated to ManagedResource connection Secret when manageMasterUserPassword is set

### ISSUE THREAD

**Issue by mlubanski** [crossplane-contrib/provider-upjet-aws#1187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

`rds.aws.upbound.io/v1beta1` - `Instance`

### Resource MRs required to reproduce the bug

```
apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    crossplane.io/external-name: eu1lab-eks001-default-mysql-1
  name: mysql-1-d6msv-q7h8m
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 20
    applyImmediately: false
    autoMinorVersionUpgrade: true
    availabilityZone: eu-west-1b
    backupRetentionPeriod: 0
    backupWindow: 14:00-16:00
    caCertIdentifier: rds-ca-rsa2048-g1
    copyTagsToSnapshot: true
    dbSubnetGroupName: private_net_vpc-***
    deleteAutomatedBackups: true
    enabledCloudwatchLogsExports:
    - audit
    engine: mysql
    engineVersion: 8.0.35
    instanceClass: db.t4g.small
    iops: 3000
    licenseModel: general-public-license
    maintenanceWindow: Mon:11:00-Mon:14:00
    manageMasterUserPassword: true
    maxAllocatedStorage: 1000
    multiAz: false
    networkType: IPV4
    optionGroupName: default-mysql-8-0
    parameterGroupName: eu1lab-eks001-default-mysql-1
    performanceInsightsEnabled: false
    port: 3306
    publiclyAccessible: false
    region: eu-west-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageThroughput: 125
    storageType: gp3
    username: root
    vpcSecurityGroupIds:
    - sg-06d7ecbe89aabc75a
    - sg-048580a25883584ad
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: upbound-provider-aws
  publishConnectionDetailsTo:
    configRef:
      name: default
    metadata:
      labels:
        secret.crossplane.io/owner-uid: 98f13eb9-d748-4787-b0ba-bec432febf2d
    name: default-mysql-1-rdsinstance
```

### Steps to Reproduce

apply `Instance` ManagedResource with `manageMasterUserPassword` property set to `true`

### What happened?

After Instance is fully provision `password` key is not added to ManagedResource connection secret:
```
$ kubectl get secret -n crossplane-system default-mysql-1-rdsinstance -o json | jq ".data"
{
  "address": "dGVycmFmb3JtLTIwMjQwMzAxMDg1NDE5ODkyNzAwMDAwMDBiLmN3b2h2eWw4ejNnYS5ldS13ZXN0LTEucmRzLmFtYXpvbmF3cy5jb20=",
  "endpoint": "dGVycmFmb3JtLTIwMjQwMzAxMDg1NDE5ODkyNzAwMDAwMDBiLmN3b2h2eWw4ejNnYS5ldS13ZXN0LTEucmRzLmFtYXpvbmF3cy5jb206MzMwNg==",
  "host": "dGVycmFmb3JtLTIwMjQwMzAxMDg1NDE5ODkyNzAwMDAwMDBiLmN3b2h2eWw4ejNnYS5ldS13ZXN0LTEucmRzLmFtYXpvbmF3cy5jb20=",
  "port": "MzMwNg==",
  "username": "cm9vdA=="
}
```

### Crossplane Version

1.15.0

### Provider Version

1.1.0

### Kubernetes Version

1.17.x

### Kubernetes Distribution

local/kind
