### ISSUE TITLE
Allow writeConnectionSecretToRef to be compatible with SQL community provider

### ISSUE THREAD

**Issue by Keralin** [crossplane-contrib/provider-upjet-aws#1189]
### What problem are you facing?

Using the community [provider for SQL](https://github.com/crossplane-contrib/provider-sql/tree/master) can't connect to the cluster created if we reference the secrets generated by [writeConnectionSecretToRef](https://marketplace.upbound.io/providers/upbound/provider-aws-rds/v1.1.0/resources/rds.aws.upbound.io/Cluster/v1beta1#doc:spec-writeConnectionSecretToRef) to the provider because it will search for `password` and `username` instead of `master_username` and `attribute.master_password` (as is required in [their doc](https://github.com/crossplane-contrib/provider-sql/tree/master?tab=readme-ov-file#usage)) so it requires so manual action modifying the secret and can't be solved in a GitOps way.

How the secrets should be stored:

```yaml
apiVersion: v1
kind: Secret
data:
  endpoint: xxxxxx
  password: xxxxxx
  port: xxxxxx
  readerEndpoint: xxxxxx
  username: xxxxxx
```

How are the secrets stored:
```yaml
apiVersion: v1
kind: Secret
data:
  endpoint: xxxxxx
  attribute.master_password: xxxxxx
  port: xxxxxx
  readerEndpoint: xxxxxx
  master_username: xxxxxx
```

### How could Official AWS Provider help solve your problem?

Enabling a feature to allow configuring how that secret or parameters should be stored, thus allowing the choice to save the connection with a username and password to be compatible with the community SQL provider like other community providers do.
