### ISSUE TITLE
Resource not found error for `aws_connect_user_hierarchy_group`

### ISSUE THREAD

**Issue by turkenf** [crossplane-contrib/provider-upjet-aws#120]
### What happened?

While testing `aws_connect_user_hierarchy_group` I got the following error:

- xp
``` 
Message:               apply failed: error creating Connect User Hierarchy Group (example): ResourceNotFoundException: Resource not found:
```
- terraform
```
 Error: error creating Connect User Hierarchy Group (example): ResourceNotFoundException: Resource not found
│
│   with aws_connect_user_hierarchy_group.example,
│   on main.tf line 15, in resource "aws_connect_user_hierarchy_group" "example":
│   15: resource "aws_connect_user_hierarchy_group" "example" {
```
- cli
```
aws connect create-user-hierarchy-group --name  example --region us-east-1 --instance-id 403bcdfe-ad07-45a5-ba4e-2ac17de440cb

An error occurred (ResourceNotFoundException) when calling the CreateUserHierarchyGroup operation: Resource not found
```
Related files:

- xp example
```
kind: UserHierarchyGroup
metadata:
  annotations:
    meta.upbound.io/example-id: connect/v1beta1/userhierarchygroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example
    region: us-east-1
---
apiVersion: connect.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: connect/v1beta1/userhierarchygroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    identityManagementType: CONNECT_MANAGED
    inboundCallsEnabled: true
    instanceAlias: friendly-name-connect-${Rand.RFC1123Subdomain}
    outboundCallsEnabled: true
    region: us-east-1
````
- main.tf
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.35.0"
    }
  }
}

provider "aws" {
  # Configuration options
  region = "us-east-1"
}

resource "aws_connect_user_hierarchy_group" "example" {
  instance_id = "403bcdfe-ad07-45a5-ba4e-2ac17de440cb"
  name        = "example"

  tags = {
    "Name" = "Example User Hierarchy Group"
  }
}
```

### How can we reproduce it?

- The issue can be reproduced only with terraform
1. Run `terraform apply`
2. Wait

- For Crossplane
1. Cut resource from config/externalnamenottested.go
3. Paste it into config/externalname.go
4. Run `make generate` for CRD generation.
5. Copy `examples-generated/connect/userhierarchygroup.yaml` to `examples/connect/userhierarchygroup.yaml`
-> Commit changes
6. I added the reference configuration for `instanceIdSelector`
7. I added the resources it depends on example
8. Run `make generate` 
9. Apply CRDs with `kubectl apply -f package/crds`
10. Run `make uptest-local EXAMPLE_LIST=examples/connect/userhierarchygroup.yaml`

### What environment did it happen in?

* Universal Crossplane Version:
* Provider Version:
