### ISSUE TITLE
[Bug]: SNS Topics Not Creating

### ISSUE THREAD

**Issue by bgould-careplanner** [crossplane-contrib/provider-upjet-aws#1220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

sns.aws.upbound.io/v1beta1

### Resource MRs required to reproduce the bug

```
apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  labels:
    testing.upbound.io/example-name: sns
  name: example
spec:
  forProvider:
    region: us-west-1
```

### Steps to Reproduce

Apply the above manifest with the below versions

### What happened?

Resource fails to create due to an invalid parameter 

### Relevant Error Output Snippet

```shell
Warning  CannotObserveExternalResource  13m                   managed/sns.aws.upbound.io/v1beta1, kind=topic  failed to observe the resource: [{0 reading SNS Topic (arn:aws:sns:<no value>:xxxxx:example): operation error SNS: GetTopicAttributes, https response error StatusCode: 400, RequestID: 6af5cf45-fe35-5c0e-8e20-912ba24ff906, InvalidParameter: Invalid parameter: TopicArn Reason: A <no value> ARN must begin with arn:null, not arn:aws:sns:<no value>:xxxxx:example  []}]
```
```


### Crossplane Version

1.15.0

### Provider Version

v1.2.0

### Kubernetes Version

1.27

### Kubernetes Distribution

EKS

### Additional Info

_No response_
