### ISSUE TITLE
Resource ECR Repository leaking if provider pod restarted after deletion

### ISSUE THREAD

**Issue by turkenh** [crossplane-contrib/provider-upjet-aws#123]
### What happened?

Noticed that my MR for ECR repository gone but actual cloud resource is still there after pod restarted during deletion.

### How can we reproduce it?

1. Install provider-aws v0.18.0
2. Create an ECR repository with the following:

```yaml
apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
  name: test-1
spec:
  forProvider:
    imageScanningConfiguration:
      - scanOnPush: true
    imageTagMutability: IMMUTABLE
    region: us-east-1
    tags:
      key1: value1
```

3. Scale down the provider to 0 (with a controller config)
4. Run `kubectl delete repository.ecr test-1`
5. Scale up the provider to 1
6. Check MR
7. Check the repository from AWS console.

### What environment did it happen in?

* Universal Crossplane Version: 1.9.1-up.2
* Provider Version: v0.18.0
