### ISSUE TITLE
[Bug]: 1.3.0 aws-provider breaks pod identity credential resolution

### ISSUE THREAD

**Issue by david-kirby** [crossplane-contrib/provider-upjet-aws#1252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* aws.upbound.io/v1beta1
* pkg.crossplane.io/v1
* sqs.aws.upbound.io/v1beta1 - queue

### Resource MRs required to reproduce the bug

In short, the below manifests:
1. setup an aws-sqs provider that gets patched to have a service account named `crossplane`
2. sets up the aws-provider config as `prod` and to use IRSA for credentials (IMPORTANT NOTE: This is working with a Pod Association configuration in EKS. The IAM role is **not** configured for IRSA and instead it's configured for Pod Identity)
3. deploys a simple sqs queue
```yaml
apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: my-queue
spec:
  forProvider:
    name: my-queue
    region: us-east-1
  providerConfigRef:
    name: prod
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: prod
spec:
  credentials:
    source: IRSA
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-sqs
spec:
  package: xpkg.upbound.io/upbound/provider-aws-sqs:v1.2.1
  runtimeConfigRef:
    name: patch-service-account
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: patch-service-account
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: crossplane
          containers: []

```

### Steps to Reproduce

I had the above manifests deployed, but upon updating the sqs provider to 1.3.0 and deploying a new queue or deleting/recreating the example, the queue cannot be created.

### What happened?

Using version 1.2.1, the queue is created. After upgrading to 1.3.0, the resource does not get created. I tested this with other resources as well (sns, eks:clusterauth) and encountered the same error message whenever the provider version being used was 1.3.0

### Relevant Error Output Snippet

```shell
message: 'connect failed: cannot initialize the Terraform plugin SDK async external
        client: cannot get terraform setup: cache manager failure: cannot calculate
        the hash for the credentials file: token file name cannot be empty'
```
```


### Crossplane Version

1.15.1

### Provider Version

1.3.0

### Kubernetes Version

_No response_

### Kubernetes Distribution

_No response_

### Additional Info

_No response_

**Comment by haarchri** [comment]
Can you try the following: 

```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: demo-pod-identity
spec:
  credentials:
    source: WebIdentity
    webIdentity:
      roleARN: arn:aws:iam::12345678910:role/demo
      tokenConfig:
        fs:
          path: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
        source: Filesystem
```
