### ISSUE TITLE
[Bug]: AWS RDS Logs Cannot Be Turned Off

### ISSUE THREAD

**Issue by humoflife** [crossplane-contrib/provider-upjet-aws#1256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

rds.aws.upbound.io/v1beta1: Cluster

### Resource MRs required to reproduce the bug

rds.aws.upbound.io/v1beta1: Cluster
rds.aws.upbound.io/v1beta1: SubnetGroup
ec2.aws.upbound.io/v1beta1: Subnet
ec2.aws.upbound.io/v1beta1: VPC

### Steps to Reproduce

Create an rds.aws.upbound.io/v1beta1: Cluster. 

Enable cloudwatch logs as follows on initial install.

enabledCloudwatchLogsExport:
  - postgresql
  
 Consecutively, try to turn cloudwatch logs off.
 
 enabledCloudwatchLogsExport: []

### What happened?

The enabledCloudwatchLogsExport is not updated, and the logs are not turned off.

### Relevant Error Output Snippet

```shell
NA
```

### Crossplane Version

v1.14.3-up.1

### Provider Version

v0.47.1

### Kubernetes Version

v1.29.1

### Kubernetes Distribution

EKS

### Additional Info

This behavior may impact more than the RDS enabledCloudwatchLogsExport array. Perhaps more arrays that need to be explicitly cleared to remove a configuration are not? Perhaps this can and/or should be centrally solved in Upjet instead of for a specific provider GVK?

**Comment by humoflife** [comment]
Confirming that this issue is in the provider. Reproduced as follows through MR yaml.

Applied the following to create the cluster with logging:

```
apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/clusterendpoint
  labels:
    testing.upbound.io/example-name: default-ce
  name: example-ce
spec:
  forProvider:
    enabledCloudwatchLogsExports:
      - postgresql
    engine: aurora-postgresql
    manageMasterUserPassword: true
    masterUsername: cpadmin
    region: us-west-1
    skipFinalSnapshot: true
  writeConnectionSecretToRef:
    name: sample-rds-cluster-secret
    namespace: upbound-system
```

Then applied the following to try to turn logs off:

```
apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/clusterendpoint
  labels:
    testing.upbound.io/example-name: default-ce
  name: example-ce
spec:
  forProvider:
    enabledCloudwatchLogsExports: []
    engine: aurora-postgresql
    manageMasterUserPassword: true
    masterUsername: cpadmin
    region: us-west-1
    skipFinalSnapshot: true
  writeConnectionSecretToRef:
    name: sample-rds-cluster-secret
    namespace: upbound-system
```
See attached screenshot that shows that logs are still turned on:
![Screenshot 2024-05-01 at 1 24 00 PM](https://github.com/crossplane-contrib/provider-upjet-aws/assets/1079395/324b45c4-15c0-4038-bd3c-2c5cdaac4ce6)
