### ISSUE TITLE
[Bug]:  route53_zone_association is not working - external-name changes all the time

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-upjet-aws#1282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* route53.aws.upbound.io/ZoneAssociation

### Resource MRs required to reproduce the bug

```
    - name: zone-association
      base:
        apiVersion: route53.aws.upbound.io/v1beta1
        kind: ZoneAssociation
        spec:
          forProvider:
            region: 
            vpcId: vpc-12345678910
            vpcRegion: eu-central-1
            zoneId: 
          providerConfigRef:
            name: xxxxxx
      patches:
        - fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - fromFieldPath: spec.forProvider.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.forProvider.region
          toFieldPath: spec.forProvider.vpcRegion
        - fromFieldPath: spec.forProvider.dnsResolverVpc.id
          toFieldPath: spec.forProvider.vpcId
        - fromFieldPath: spec.forProvider.dnsResolverVpc.region
          toFieldPath: spec.forProvider.vpcRegion
        - fromFieldPath: status.eks.clusterDnsZone.id
          toFieldPath: spec.forProvider.zoneId
          policy:
            fromFieldPath: Required
```

### Steps to Reproduce

t.b.d

### What happened?

we are experiencing issues with the ZoneAssociation
provider is changing the external name from Z07140233D46T81NLRIZ3:vpc-12345678910 to Z07140233D46T81NLRIZ3:vpc-12345678910:eu-central-1 and back to Z07140233D46T81NLRIZ3:vpc-12345678910

### Crossplane Version

v1.14.x

### Provider Version

v1.3.1

### Additional Info

in terraform provider-aws you can see the following information:

The VPC is in the same region where you have configured the Terraform AWS Provider:

`% terraform import aws_route53_zone_association.example Z123456ABCDEFG:vpc-12345678`

The VPC is not in the same region where you have configured the Terraform AWS Provider:

`% terraform import aws_route53_zone_association.example Z123456ABCDEFG:vpc-12345678:us-east-2`
