### ISSUE TITLE
[Bug]: RDS Parameter Group updates parameter in loop

### ISSUE THREAD

**Issue by WolfGanGeRTech** [crossplane-contrib/provider-upjet-aws#1286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ParameterGroup.rds.aws.upbound.io

### Resource MRs required to reproduce the bug

ParameterGroup.rds.aws.upbound.io

### Steps to Reproduce

Create a new ParameterGroup for mysql 8.0 and set the property "innodb_file_per_table": 1

```yaml
apiVersion: rds.aws.upbound.io/v1beta1
kind: ParameterGroup
metadata:
  name: example-parametergroup
spec:
  forProvider:
    description: example
    family: mysql8.0
    parameter:
      - applyMethod: immediate
        name: innodb_file_per_table
        value: "1"
    region: eu-central-1
```

Crossplane will start updating AWS in loop, this increases a lot the Cloudtrail costs.

<img width="477" alt="image" src="https://github.com/crossplane-contrib/provider-upjet-aws/assets/103154194/d0058a36-91bc-479f-b9d0-bc42dc920267">

### What happened?

When a new RDS parameter group is created with property "innodb_file_per_table": 1, crossplane tries to apply this config in loop increasing a lot the cloudtrail costs.

<img width="477" alt="image" src="https://github.com/crossplane-contrib/provider-upjet-aws/assets/103154194/d0058a36-91bc-479f-b9d0-bc42dc920267">

I have used a few properties and this is the only one that is returning this problem, however I can not guarantee this is the only property that causes problems.

When I look at cloudtrail:

<img width="601" alt="image" src="https://github.com/crossplane-contrib/provider-upjet-aws/assets/103154194/39e25211-6ad3-4f63-b10e-f39c1a25d1b4">

The request shows "isModifiable": false, however this parameter shows as modifiable in the parameter group table:

<img width="1135" alt="image" src="https://github.com/crossplane-contrib/provider-upjet-aws/assets/103154194/9a48366e-6632-415b-8d41-ad1b0b220eaa">
 
So I am not sure this is the issue.

### Relevant Error Output Snippet

```shell
No errors seen in Crossplane.
```

### Crossplane Version

12.2.2

### Provider Version

0.46

### Kubernetes Version

1.27

### Kubernetes Distribution

EKS

**Comment by WolfGanGeRTech** [comment]
I was able to find the issue, basically this property doesn't allow setting the applyMethod to "immediate" (which is the default on Crossplane). So Crossplane tries to apply it and AWS gives an Ok, however doesn't really change the value, so Crossplane tries again and again.

In these cases it would be good if we could define a retry interval cause a small error in the configs can lead to huge costs.

**Comment by turkenf** [comment]
Hi @WolfGanGeRTech,

Thank you for raising this issue it can be reproducible with the provider version `1.4.0`:
```
2024-05-09T12:21:34+03:00	DEBUG	provider-aws	Diff detected	{"uid": "f57f26a5-4e88-4fcb-bef0-74d8dd0d0719", "name": "fatih-example-parametergroup", "gvk": "rds.aws.upbound.io/v1beta1, Kind=ParameterGroup", "instanceDiff": "*terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{\"parameter.178632114.apply_method\":*terraform.ResourceAttrDiff{Old:\"\", New:\"immediate\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"parameter.178632114.name\":*terraform.ResourceAttrDiff{Old:\"\", New:\"innodb_file_per_table\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"parameter.178632114.value\":*terraform.ResourceAttrDiff{Old:\"\", New:\"1\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"parameter.2584704414.apply_method\":*terraform.ResourceAttrDiff{Old:\"pending-reboot\", New:\"\", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"parameter.2584704414.name\":*terraform.ResourceAttrDiff{Old:\"innodb_file_per_table\", New:\"\", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"parameter.2584704414.value\":*terraform.ResourceAttrDiff{Old:\"1\", New:\"\", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, RawConfig:cty.NilVal, RawState:cty.NilVal, RawPlan:cty.NilVal, Meta:map[string]interface {}(nil)}"}
```

**Comment by karlderkaefer** [comment]
I have same issue. I used apply immediate 
```
spec:
  forProvider:
    family: postgres16
    parameter:
    - applyMethod: immediate
      name: idle_in_transaction_session_timeout
      value: "86400000"
```
the [aws documentation](https://docs.aws.amazon.com/prescriptive-guidance/latest/tuning-postgresql-parameters/idle-in-transaction-session-timeout.html) states this parameter can be applied immediately but when I check the status of MR parameter group it says it's in pending-reboot

```
status:
  atProvider:
    family: postgres16
    parameter:
    - applyMethod: pending-reboot
      name: idle_in_transaction_session_timeout
      value: "86400000"
```
this will cause a permanent diff as describe above
