### ISSUE TITLE
Route53 Record LB Alias Support

### ISSUE THREAD

**Issue by silverbp** [crossplane-contrib/provider-upjet-aws#1294]
### What problem are you facing?

Would like the ability to set a route53 record from a Load Balancer managed by crossplane.

### How could Official AWS Provider help solve your problem?
The alias just takes a string name, if you could provide a ref to a crossplane resource, it would make it so you could create a route53 record for the LB resource.

**Comment by turkenf** [comment]
Hi @silverbp,

Thank you for raising this issue, could you please provide us with the `apiVersion` or group names as well as the resource names related to your request?

**Comment by mtthwcmpbll** [comment]
I'd love to be able to use the Route53 Record type to create alias records pointed at existing Elastic Load Balancers as well.  I see that the [Record type in v1.9.0 of the provider](https://marketplace.upbound.io/providers/upbound/provider-aws-route53/v1.9.0/resources/route53.aws.upbound.io/Record/v1beta1) provides an `alias` block, but it's not super clear what to provide as the zoneId and name properties.

I've tried setting creating an alias record like the following:
```
---
apiVersion: route53.aws.upbound.io/v1beta2
kind: Record
metadata:
  name: test-alias
spec:
  forProvider:
    name: "test-elb-alias"
    alias:
      evaluateTargetHealth: true
      name: dualstack.a5e61abdca6b542219af2bb784fe3cba-742101654.us-east-2.elb.amazonaws.com.
      zoneId: Z0466664B8EG8JLWS1L3
    region: us-east-2
    type: A
    zoneIdRef:
      name: existing-zone-name
```

The Record eventually fails with the event:

```
[Tried to create an alias that targets dualstack.a5e61abdca6b542219af2bb784fe3cba-742101654.us-east-2.elb.amazonaws.com., type A in zone Z0466664B8EG8JLWS1L3, but the alias target name does not lie within the target zone[]
```

After some experimentation, I found that I can see the ZoneId for an alias record in the Route53 alias creation page (once I've selected the resource I want to target).  Aliases aren't in any of my created zones, so I have to go find this info manually in order to create the alias block in my Record resource.

I think the original reporter was asking for a way to use a cross resource reference to an ELB that Crossplane manages, which would let me get the name and ZoneId and push it down to this alias.  I've also found CRRs help me figure out what exactly I'm supposed to be providing for a field - is "name" an AWS ID?  An AWS ARN?  A Crossplane managed resource name?  etc.  It took some guessing with the current resource to get an alias record provisioned.
