### ISSUE TITLE
Question: Can IAM Policies be patched ? 

### ISSUE THREAD

**Issue by tcarac** [crossplane-contrib/provider-upjet-aws#1299]
Hello! 
I'd say I'm trying to achieve something basic but not sure anymore given I didn't find a lot about it searching so far.

I'm trying to kustomize patch a simple IAM policy defined as a document:
My intention really is to patch aws account IDs.
Is there a recomended way to do so without duplicating the policies per overlay ? 
```yaml
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: sample-policy
spec:
  deletionPolicy: Delete
  forProvider:
    description: Allow to manage SQS queues & DynamoDB tables
    document: >
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "dynamodb:UpdateItem",
              "dynamodb:Scan",
              "dynamodb:Query",
              "dynamodb:PutItem",
              "dynamodb:Get*",
              "dynamodb:Describe*",
              "dynamodb:BatchWriteItem",
              "dynamodb:BatchGetItem"
            ],
            "Effect": "Allow",
            "Resource": [
              "arn:aws:dynamodb:us-east-1:1111:table/run-log",
              "arn:aws:dynamodb:us-east-1:1111:table/batch-item-log",
              "arn:aws:dynamodb:us-east-1:1111:table/batch-item-log/index/RunID-index"
            ]
          },
          {
            "Action": [
              "sqs:SendMessage",
              "sqs:ReceiveMessage",
              "sqs:PurgeQueue",
              "sqs:Get*",
              "sqs:DeleteMessage",
              "sqs:ChangeMessageVisibility"
            ],
            "Effect": "Allow",
            "Resource": [
              "arn:aws:sqs:us-east-1:111:sample1.fifo",
              "arn:aws:sqs:us-east-1:111:sample2.fifo",
              "arn:aws:sqs:us-east-1:111:sample3.fifo",
              "arn:aws:sqs:us-east-1:111:sample4.fifo"
            ]
          }
        ]
      }
    name: sample-policy-document
  providerConfigRef:
    name: provider-aws-config
```

**Comment by linusyong** [comment]
Hi @tcarac, not sure if this helps.

- Create an `XRD`
  ```yaml
  apiVersion: apiextensions.crossplane.io/v1
  kind: CompositeResourceDefinition
  metadata:
    name: xpolicytests.consumable.trustbank.sg
  spec:
    group: consumable.trustbank.sg
    names:
      kind: xPolicyTest
      plural: xpolicytests
    versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                awsAccountId:
                  type: string
              required:
              - name
              - awsAccountId
      served: true
      referenceable: true
    claimNames:
      kind: PolicyTest
      plural: policytests
  ```
- Create a `Composition`
  ```yaml
  apiVersion: apiextensions.crossplane.io/v1
  kind: Composition
  metadata:
    name: x-policy-test
  spec:
    compositeTypeRef:
      apiVersion: consumable.trustbank.sg/v1alpha1
      kind: xPolicyTest
    resources:
    - name: xplane-karpenter-policy
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: Policy
        metadata:
          name: xplane-karpenter-policy
        spec:
          deletionPolicy: Delete
          forProvider:
            tags:
              Name: xplane-karpenter-policy
              Owner: linus.yong
              Environment: sandbox
          providerConfigRef:
            name: aws-provider
      patches:
      - type: CombineFromComposite
        combine:
          variables:
          - fromFieldPath: spec.name
          strategy: string
          string:
            fmt: "%s-xplane-karpenter-policy"
        toFieldPath: metadata.name
      - type: CombineFromComposite
        combine:
          variables:
          - fromFieldPath: spec.name
          strategy: string
          string:
            fmt: "%s-xplane-karpenter-policy"
        toFieldPath: spec.forProvider.tags.Name
      - type: CombineFromComposite
        combine:
          variables:
          - fromFieldPath: spec.awsAccountId
          - fromFieldPath: spec.name
          - fromFieldPath: spec.awsAccountId
          - fromFieldPath: spec.name
          strategy: string
          string: 
            fmt: |
              {
                "Statement": [
                  {
                    "Action": "iam:PassRole",
                    "Effect": "Allow",
                    "Resource": "arn:aws:iam::%s:role/%s-xplane-eks-cluster",
                    "Sid": "PassNodeIAMRole"
                  },
                  {
                    "Action": "eks:DescribeCluster",
                    "Effect": "Allow",
                    "Resource": "arn:aws:eks:ap-southeast-1:%s:cluster/%s-xplane-eks-cluster",
                    "Sid": "EKSClusterEndpointLookup"
                  }
                ],
                "Version": "2012-10-17"
              }
        toFieldPath: spec.forProvider.policy
        policy:
          fromFieldPath: Required
  ```
- Then create the `xPolicyTest`
  ```yaml
  apiVersion: consumable.trustbank.sg/v1alpha1
  kind: xPolicyTest
  metadata:
    name: my-cluster
  spec:
    name: my-cluster
    awsAccountId: "123456789012"
  ```
