### ISSUE TITLE
No data in secret for EC2 connectionDetails

### ISSUE THREAD

**Issue by dmarquez-splunk** [crossplane-contrib/provider-upjet-aws#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ec2.aws.upbound.io Instance

### Resource MRs required to reproduce the bug

Hey team

I am exploring creating ec2 instances using crossplane. I am creating a managed resource below but am encountering issues when trying to read connectionDetails about the provisioned resource. I can see the resources is synced and ready successfully and the secret is created. However there are no fields in the secret and it is completely empty. I don't see any relevant logs in the pods or events that can help explain which is leads me here. Am I doing something wrong, missing something, or is this expected?

The manifest I am using to create the instance:

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
   name: test-2
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    ami: ami-01cd4de4363ab6ee8
    availabilityZone: us-west-2b
    instanceType: t2.micro
    subnetId: <some_subnet>
  providerConfigRef:
    name: aws-irsa
  publishConnectionDetailsTo:
    name: test-secret-2
  writeConnectionSecretToRef:
    namespace: crossplane
    name: test-secret-2
```

```
 kubectl get instances
NAME     SYNCED   READY   EXTERNAL-NAME         AGE
test-2   True     True    i-05da3c7201316daa4   11m
```

```
kubectl describe secret test-secret-2 -n crossplane
Name:         test-secret-2
Namespace:    crossplane
Labels:       <none>
Annotations:  <none>

Type:  connection.crossplane.io/v1alpha1

Data
====
```

### Steps to Reproduce

Create resource using manifest above and inspect created secret

### What happened?

I expected the created secret to have data about the created resource

### Relevant Error Output Snippet

```shell
N/A
```

### Crossplane Version

1.3.1

### Provider Version

1.15.2

### Kubernetes Version

1.28.8

### Kubernetes Distribution

EKS
