### ISSUE TITLE
lifecycle.prevent_destroy  issue for resource groups: Instance trying to be destroyed after creation and we can see resources have SYNCED False after READY became True

### ISSUE THREAD

**Issue by svscheg** [crossplane-contrib/provider-upjet-aws#134]
### What happened?

During testing the resource groups we have an issue with lifecycle.prevent_destroy.
List of resources:
- [aws_appmesh_virtual_router](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_router)
- [aws_appmesh_virtual_gateway](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_gateway)
- [aws_appmesh_virtual_node](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_node)
- [aws_appmesh_virtual_service](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_service)
- [aws_appmesh_gateway_route](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_gateway_route)
- [aws_appmesh_route](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_route)
- [aws_directory_service_log_subscription](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_log_subscription)
- [aws_networkmanager_site_to_site_vpn_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_site_to_site_vpn_attachment)
- [aws_networkmanager_transit_gateway_peering](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_transit_gateway_peering)

For example will take error for aws_appmesh_virtual_node (all another resources have the same problem) - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_node

Error message:
message: 'observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
      Resource aws_appmesh_virtual_node.serviceb1 has lifecycle.prevent_destroy set,
      but the plan calls for this resource to be destroyed. To avoid this error and
      continue with the plan, either disable lifecycle.prevent_destroy or reduce the
      scope of the plan using the -target flag.'

### How can we reproduce it?

Copy generated manifest, add missing dependancy aws_appmesh_mesh, try to apply manifest.
[yaml_output.txt](https://github.com/upbound/provider-aws/files/9975855/yaml_output.txt)
[virtualnode.yaml.txt](https://github.com/upbound/provider-aws/files/9975857/virtualnode.yaml.txt)

The following manifests can be used to reproduce the issue:
```yaml
apiVersion: appmesh.aws.upbound.io/v1beta1
kind: VirtualNode
metadata:
  annotations:
    meta.upbound.io/example-id: appmesh/v1beta1/virtualnode
  labels:
    testing.upbound.io/example-name: serviceb1
  name: serviceb1
spec:
  forProvider:
    meshNameSelector:
      matchLabels:
        testing.upbound.io/example-name: simple
    region: us-west-1
    spec:
    - backend:
      - virtualService:
        - virtualServiceName: servicea.simpleapp.local
      listener:
      - portMapping:
        - port: 8080
          protocol: http
      serviceDiscovery:
      - dns:
        - hostname: serviceb.simpleapp.local

---

apiVersion: appmesh.aws.upbound.io/v1beta1
kind: Mesh
metadata:
  annotations:
    meta.upbound.io/example-id: appmesh/v1beta1/mesh
  labels:
    testing.upbound.io/example-name: simple
  name: simple
spec:
  forProvider:
    region: us-west-1
```

### What environment did it happen in?

* Universal Crossplane Version:
* Provider Version:
