### ISSUE TITLE
[Bug]: The AWS WAF classic IPSet resource is stuck and not deleted when the Claim or XR is deleted.

### ISSUE THREAD

**Issue by MichaelRSilva** [crossplane-contrib/provider-upjet-aws#1369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* waf.aws.upbound.io/v1beta1 - IPSet
* waf.aws.upbound.io/v1beta1 - WebACL

### Resource MRs required to reproduce the bug

```
...
resources:
    - name: rule
      base:
        apiVersion: waf.aws.upbound.io/v1beta1
        kind: Rule
        metadata:
          annotations:
            meta.upbound.io/example-id: waf/v1beta1/rule
          labels:
            testing.upbound.io/example-name: wafrule
          name: wafrule
        spec:
          forProvider:
            metricName: tfWAFRule
            name: tfWAFRule
            predicates:
            - dataIdSelector:
                matchLabels:
                  testing.upbound.io/example-name: ipset
              negated: false
              type: IPMatch
            region: us-east-1
    - name: ipset
      base:
        apiVersion: waf.aws.upbound.io/v1beta1
        kind: IPSet
        metadata:
          annotations:
            meta.upbound.io/example-id: waf/v1beta1/rule
          labels:
            testing.upbound.io/example-name: ipset
          name: ipset
        spec:
          forProvider:
            ipSetDescriptors:
            - type: IPV4
              value: 192.0.7.0/24
            name: tfIPSet
            region: us-east-1
...
```

### Steps to Reproduce

I'm using the provider-aws-waf to create IPSet and Rule in a composition, the Rule has a predicate pointing to one IPSet. When I delete the claim or XR, the Rule is deleted but the IPSet is getting stuck. I can see the IP addresses inside the IPSet are deleted, but the resource not.

### What happened?

The IPSet should be deleted when a `kubectl delete -f waf-xr.yaml' command is executed, but only the IPSet IPs are deleted, the resource is orphaned and still exists, as it is possible to view it in the console.

![Screenshot 2024-06-11 at 04 50 51](https://github.com/crossplane-contrib/provider-upjet-aws/assets/7951317/bc80d877-8fa7-4d79-9552-1b74fbb003e2)

When executing the command `kubectl describe ipset` it is possible to see that there are invalid attempts to delete.

![Screenshot 2024-06-11 at 05 02 14](https://github.com/crossplane-contrib/provider-upjet-aws/assets/7951317/7c9caf4e-8d36-42c3-b650-6f51160b50bb)

### Crossplane Version

1.16

### Provider Version

1.7.0

### Kubernetes Version

1.29.4-eks-036c24b

### Kubernetes Distribution

EKS
