### ISSUE TITLE
[Bug]: Nodegroup with LaunchTemplate always adds to Update History

### ISSUE THREAD

**Issue by georgblumenschein** [crossplane-contrib/provider-upjet-aws#1375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

eks.aws.upbound.io/v1beta1 - NodeGroup
ec2.aws.upbound.io/v1beta1 - Launchtemplae

### Resource MRs required to reproduce the bug

```
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: test-ng
spec:
  forProvider:
    clusterNameSelector:
      matchControllerRef: true
    versionSelector:
      matchControllerRef: true
    nodeRoleArnSelector:
      matchControllerRef: true
      matchLabels:
        role: nodegroup
    launchTemplate:
      - name: test-ng-lt
        version: "$Default"
    amiType: "AL2_x86_64"
    capacityType: SPOT
    instanceTypes:
      - m7a.large
    forceUpdateVersion: false
    releaseVersion: "1.29.0-20240227"
    scalingConfig:
      - maxSize: 2
        minSize: 0
        desiredSize: 0
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: test-ng-lt
spec:
  forProvider:
    blockDeviceMappings:
      - ebs:
        - volumeType: gp3
          volumeSize: 50
        deviceName: /dev/xvda
    monitoring:
      - enabled: true
    name: test-ng-lt
    updateDefaultVersion: true
    instanceRequirements:
      - allowedInstanceTypes:
          - m7a.large
        memoryMib:
          - min: 2048
        vcpuCount:
          - min: 2
```

### Steps to Reproduce

1. Deploy the resources
2. Wait for the NodeGroup with the LaunchTemplate to show up in the AWS console
3. Check the update history of the NodeGroup

### What happened?

Both with the $Default and the $Latest flag for the LaunchTemplate version the update history gets spammed to the point where "429: Too many Requests" on loading is returned.

I would expect that since the Default/Latest version of the LaunchTemplate is "1", it should count as synced.

Workaround: Have the version as String, so e.g. "1" as version for the LaunchTemplate

### Crossplane Version

1.16.0

### Provider Version

1.5.0

### Kubernetes Version

1.29

### Kubernetes Distribution

EKS

**Comment by haarchri** [comment]
yes we have the same issue with

```
    launchTemplate:
      - name: my-awesome-launchtemplate
        version: $Latest
```

**Comment by turkenf** [comment]
Hello folks, 

Thank you for bringing up this issue. It can be reproducible with the latest provider version:
```
DEBUG	provider-aws	Diff detected	{"uid": "604ae2df-0141-4a96-890f-54dff549d3a4", "name": "sample-eks-ng-ft", "gvk": "eks.aws.upbound.io/v1beta1, Kind=NodeGroup", "instanceDiff": "*terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{\"launch_template.0.version\":*terraform.ResourceAttrDiff{Old:\"1\", New:\"$Latest\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, RawConfig:cty.NilVal, RawState:cty.NilVal, RawPlan:cty.NilVal, Meta:map[string]interface {}(nil)}"}
```

![Screenshot 2024-06-26 at 21 34 30](https://github.com/crossplane-contrib/provider-upjet-aws/assets/103541666/3a5a0d8c-38ff-40db-818b-eb89a6dbbca5)

**Comment by turkenf** [comment]
Hi folks, after doing some investigation on this issue:

- As stated in the Terraform [document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#version), when we give `$Default` or `$Latest` values ​​to the `launchTemplate.version` field, diff occurs as expected.

    <img width="651" alt="Screenshot 2024-06-27 at 15 06 51" src="https://github.com/crossplane-contrib/provider-upjet-aws/assets/103541666/8e4aee26-8fd8-46b6-a7b9-b7dce3169f3c">
    
    During reading, the version number comes as a numerical value and since we set `launchTemplate.version: $Latest`, it enters a continuous update loop.

- After discussing the issue with the team, we realized there is no easy solution.

  If we write a `CustomDiff` function to delete the diff, it works, and the resource gets rid of the update loop. But this causes the `launchTemplate.version` field to lose its functionality and the API to work outside expectations.
  
  For example, let's set `launchTemplate.version: $Latest`, and after creating the `NodeGroup` resource, let's create a new version of `LaunchTemplate`. Since we deleted the diff for the field, the `launchTemplate.version` value will remain the same, and its functionality will be disrupted.

- I haven't tried it, but as mentioned in the document, instead of using `$Default` or `$Latest` values, we can patch the `latestVersion` or `defaultVersion` values ​​in the status of the `LaunchTemplate` resource for the `launchTemplate.version` field by using compositions. If the `LaunchTemplate` resource is not managed with Crossplane, [import](https://docs.crossplane.io/latest/guides/import-existing-resources/) the resource by setting `managementPolicies: ["Observe"]` and patch the field.

Here, our best solution would be to prevent giving `$Latest` and `$Default` values ​​to the `launchTemplate.version` field.

**Comment by flavioque** [comment]
Hi , folks,  regarding the last comment of patching up the version in a composition, it worked.


It seems that the differences between types between Launch Template Version (being a number) and NodeGroup' LaunchTemplate version (being a string) causes the NodeGroup trying always adds to Update History. 

 

The solution was to use a convert function in the patch [https://docs.crossplane.io/latest/guides/function-patch-and-transform/#convert-transforms](url) Credits to @alexlopes


    ```

  patches:

        - type: ToCompositeFieldPath

          fromFieldPath: status.atProvider.latestVersion

          toFieldPath: status.launchTemplateVersion

          transforms:

            - type: convert

              convert:

                toType: string

```
