### ISSUE TITLE
[Bug]: The IAM Role resource uses role names as external ID causing conflict between role using the same name but different paths

### ISSUE THREAD

**Issue by gadiener** [crossplane-contrib/provider-upjet-aws#1376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* iam.aws.upbound.io/v1beta1 - Role

### Resource MRs required to reproduce the bug

```yaml
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  labels:
    crossplane.io/composite: my-awesome-role
    type: service-account-role
  annotations:
    crossplane.io/external-name: demo-role
  name: demo-role
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicy: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["sts:AssumeRoleWithWebIdentity"],"Principal":{"Federated":"test"},"Condition":{"StringLike":{"test:aud":"sts.amazonaws.com","test:sub":"system:serviceaccount:demo-ns:demo-sa"}}}]}'
    description: demo-role used by service-account demo-ns:demo-sa
    forceDetachPolicies: true
    path: /my-path/demo-ns/
    permissionsBoundary: arn:aws:iam::test:policy/edge-case/my-path/boundary.assume-role
    tags:
      Stage: test
  providerConfigRef:
    name: test-test-iamrole-provider-config
```

```yaml
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  labels:
    crossplane.io/composite: my-awesome-role
    type: service-account-role
  annotations:
    crossplane.io/external-name: demo-role
  name: demo-role2
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicy: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["sts:AssumeRoleWithWebIdentity"],"Principal":{"Federated":"test"},"Condition":{"StringLike":{"test:aud":"sts.amazonaws.com","test:sub":"system:serviceaccount:demo-ns:demo-sa"}}}]}'
    description: demo-role used by service-account demo-ns:demo-sa
    forceDetachPolicies: true
    path: /my-path/demo-ns-2/
    permissionsBoundary: arn:aws:iam::test:policy/edge-case/my-path/boundary.assume-role
    tags:
      Stage: test
  providerConfigRef:
    name: test-test-iamrole-provider-config
```

note that the `crossplane.io/external-name` label value is the same for both resources while `spec.forProvider.path` have different values

### Steps to Reproduce

Create 2 roles using the same name but different paths, the `crossplane.io/external-name` uses only the role name therefore the Crossplane it's not able to differentiate between the 2 cloud resources (should we use ARNs instead or role path + name?)

### What happened?

It is not possible to create 2 roles with the same name but different role paths

### Crossplane Version

v1.15.0

### Provider Version

v1.1.1

### Kubernetes Version

v1.28.9

### Kubernetes Distribution

EKS

### Additional Info

I'd love to contribute with a fix but I'd need someone to guide me through
