### ISSUE TITLE
I can't configure `aws_apprunner_custom_domain_association` because it requires certificates with valid domains

### ISSUE THREAD

**Issue by turkenf** [crossplane-contrib/provider-upjet-aws#138]
### What happened?

While testing `aws_apprunner_custom_domain_association` I got the following error:

```
    message: 'apply failed: error waiting for App Runner Custom Domain Association
      (example.com,arn:aws:apprunner:us-east-1:569674547146:service/example/c49f2abb162244d2bfbd186def188af9)
      creation: unexpected state ''create_failed'', wanted target ''pending_certificate_dns_validation,
      binding_certificate''. last error: %!s(<nil>): '
```
- It requires certificates with valid domains and the final version of the example is below:
```
apiVersion: apprunner.aws.upbound.io/v1beta1
kind: CustomDomainAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: apprunner/v1beta1/customdomainassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    domainName: example.com
    region: us-east-1
    serviceArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: apprunner.aws.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: apprunner/v1beta1/customdomainassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-1
    serviceName: example
    sourceConfiguration:
    - imageRepository:
      - imageConfiguration:
          - port: "8000"
        imageIdentifier: public.ecr.aws/aws-containers/hello-app-runner:latest
        imageRepositoryType: ECR_PUBLIC
      autoDeploymentsEnabled: false
    tags:
      Name: example-apprunner-service

```

### How can we reproduce it?

1. Cut resource from config/externalnamenottested.go
3. Paste it into config/externalname.go
4. Run `make generate` for CRD generation.
5. Copy `examples-generated` to `examples`
-> Commit changes
6. I added the resources it depends on the example and fix example
7. Run `make generate` 
8. Apply CRDs with `kubectl apply -f package/crds`
9. Run `make uptest-local EXAMPLE_LIST=examples/appstream/fleet.yaml`

### What environment did it happen in?

Local development
