### ISSUE TITLE
[Bug]: Observe fails for VPC and Subnets with observe failed: external resource does not exist

### ISSUE THREAD

**Issue by ayanevbg** [crossplane-contrib/provider-upjet-aws#1385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ec2.aws.upbound.io/v1beta1 - VPC, Subnet

### Steps to Reproduce

1. Create a VPC

`
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  labels:
    vpc.upbound.io/name: test-vpc
  name: test-vpc
spec:
  deletionPolicy: Orphan # Do not delete the VPC after the c
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-west-1
    enableDnsHostnames: true
    tags:
      Name: test-vpc
`
      
  2. Delete the resource and try to recreate it with managementPolicies: ["Observe"]
    
`
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  labels:
    vpc.upbound.io/name: test-vpc
  name: test-vpc
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe"]
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-west-1
    enableDnsHostnames: true
    tags:
      Name: test-vpc
`

### What happened?

Unable to find VPC and Subnets with management policy set to "Observe". It gives observe failed: external resource does not exist even though the resources exist.

This can be observed even when you create a VPC first, then delete it deletion policy set to Orphan and finally with the same configuration try to create a resource with management policies set to ["Observe"]. It fails with the same error.

### Crossplane Version

1.16.0

### Provider Version

1.7.0

**Comment by ayanevbg** [comment]
Setting this annotation seems to be required.

annotations:
    crossplane.io/external-name: <VPC_ID>
    
 This did the trick for me.

**Comment by PrasanthV454** [comment]
hey @ayanevbg @mergenci 

I am trying to do this with -

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: existing-vpc
  annotations:
    crossplane.io/external-name : project-vpc
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: default
```
    
I am getting - observe failed: external resource does not exist

Can some one help me here?
