### ISSUE TITLE
[Bug]: Failing to convert AutoScalingGroup.launchTemplate from list to array

### ISSUE THREAD

**Issue by josegonzalez** [crossplane-contrib/provider-upjet-aws#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

- autoscaling.aws.upbound.io/v1beta3 - AutoscalingGroup

### Resource MRs required to reproduce the bug

```
apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: AutoscalingGroup
metadata:
  name: "dev-us-east-1-private-consul"
  namespace: "dev"
  labels:
    name: "dev-us-east-1-private-consul"
    environment: "dev"
    region: "us-east-1"
spec:
  forProvider:
    # prettier-ignore
    desiredCapacity: 3
    # prettier-ignore
    maxSize: 3
    # prettier-ignore
    minSize: 3
    launchTemplate:
      - version: "$Latest"
        idSelector:
          matchLabels:
            name: "dev-us-east-1-private-consul"
            environment: "dev"
            region: "us-east-1"
    region: "us-east-1"
    tag:
      - key: Name
        value: "dev-us-east-1-private-consul"
      - key: environment
        value: "dev"
      - key: managed-by
        value: crossplane
    vpcZoneIdentifierSelector:
      matchLabels:
        subnet-type: "private"
        environment: "dev"
        vpc-name: "dev-us-east-1"
```

### Steps to Reproduce

Apply the above manifest (with a matching template/subnet)

### What happened?

Missing `launchTemplate` property on the converted v1beta3 resource.

### Relevant Error Output Snippet

```shell
Message:               create failed: async create failed: failed to create the resource: [{0 creating Auto Scaling Group (dev-us-east-1-private-consul): operation error Auto Scaling: CreateAutoScalingGroup, https response error StatusCode: 400, RequestID: 7ebe95af-e405-4fcb-9a7a-dc53a888d835, api error ValidationError: Valid requests must contain either LaunchTemplate, LaunchConfigurationName, InstanceId or MixedInstancesPolicy parameter.  []}]
```

Spec

```

Spec:
  Deletion Policy:  Delete
  For Provider:
    Desired Capacity:  3
    Max Size:          3
    Min Size:          3
    Region:            us-east-1
    Tag:
      Key:    Name
      Value:  dev-us-east-1-private-consul
      Key:    environment
      Value:  dev
      Key:    managed-by
      Value:  crossplane
    Vpc Zone Identifier:
      subnet-12345
      subnet-67890
      subnet-45678
    Vpc Zone Identifier Refs:
      Name:  dev-us-east-1c-private
      Name:  dev-us-east-1b-private
      Name:  dev-us-east-1a-private
    Vpc Zone Identifier Selector:
      Match Labels:
        environment:  dev
        subnet-type:  private
        vpc-name:     dev-us-east-1
  Init Provider:
  Management Policies:
    *
  Provider Config Ref:
    Name:  default
```

### Crossplane Version

1.16.0

### Provider Version

1.8.0

### Kubernetes Version

Client Version: v1.30.1 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.4-eks-036c24b

### Kubernetes Distribution

EKS

### Additional Info

Works fine if I manually change it and switch to the v1beta3 resource myself with the requisite resource changes.

See https://crossplane.slack.com/archives/C05E0UE46S2/p1720556633009269 for more discussion.

Maybe related: https://github.com/crossplane-contrib/provider-upjet-aws/pull/1332
