### ISSUE TITLE
[Bug]: Unclear documentation how to configure PublicKey resources since v1.5.0

### ISSUE THREAD

**Issue by PatTheSilent** [crossplane-contrib/provider-upjet-aws#1400]
I'm assuming the fact that I used compositions is completely irrelevant but I haven't tested directly applying the MR.

It is currently unclear how a `PublicKey` (and Function but haven't used those) resource should be configured. The examples do not show the required `initProvider.encodedKeySecretRef` field and resources do not pass validation due to that field missing.

A side comment is that I don't really understand why `initProvider` fields would be required in the first place. The current documentation states:
> The initProvider defines settings Crossplane applies only when creating a new managed resource.
> Crossplane ignores settings defined in the initProvider field that change after creation.

This is fairly clear. What isn't so clear is how a resource whose sole purpose is to store an encryption key will behave if I have to set that key via an `initProvider` field.

If this is an actual requirement and not a bug introduced by accident then the documentation could use some additional clarification and the examples could be enhanced as well.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* cloudfront.aws.upbound.io/v1beta1 - PublicKey
* cloudfront.aws.upbound.io/v1beta1 - Function

### Resource MRs required to reproduce the bug

Used go templating composition 

```
---
apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: PublicKey
metadata:
  name: {{ $name }}
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: publickey
spec:
  deletionPolicy: Delete
  forProvider:
    name: {{ $name }}
    region: {{ $xr.spec.aws.region }}
    encodedKeySecretRef:
      namespace: {{ index $claim.spec.claimRef "namespace" }}
      key: {{ $xr.spec.aws.encodedKey.key }}
      name: {{ $xr.spec.aws.encodedKey.name }}
```

### Steps to Reproduce

* Apply composition that tries to create a PublicKey resource

### What happened?

* composition fails

### Relevant Error Output Snippet

```shell
cannot compose resources: cannot apply composed resource "publickey": PublicKey.cloudfront.aws.upbound.io "redacted" is invalid: [spec.initProvider.encodedKeySecretRef: Required value, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
```
```


### Crossplane Version

1.14.3

### Provider Version

1.6.1

### Kubernetes Version

1.26

### Kubernetes Distribution

EKS

### Additional Info
