### ISSUE TITLE
[Bug]: Insufficient Permissions for ProviderConfig Listing in Crossplane AWS Provider v1.6.0 with EKS

### ISSUE THREAD

**Issue by edgarsilva948** [crossplane-contrib/provider-upjet-aws#1402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

elbv2.aws.upbound.io/v1beta1 - LB
elbv2.aws.upbound.io/v1beta1 - LBTargetGroup
elbv2.aws.upbound.io/v1beta1 - LBTargetGroupAttachment
elbv2.aws.upbound.io/v1beta1 - LBListener

### Resource MRs required to reproduce the bug

```yaml 
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: ${name}-runtime-config
spec:
  deploymentTemplate:
    spec:
      replicas: 1
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              args:
                - --debug
              env:
                - name: http_proxy
                  value: "http://proxy-server:80"
                - name: https_proxy
                  value: "http://proxy-server:443"
                - name: HTTP_PROXY
                  value: "http://proxy-server:80"
                - name: HTTPS_PROXY
                  value: "http://proxy-server:443"
                - name: no_proxy
                  value: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, .svc, .cluster.local"
                - name: NO_PROXY
                  value: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, .svc, .cluster.local"
          securityContext:
            fsGroup: 2000
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: ${provider_role_arn}

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-${name}-${family}
spec:
  package: ${ecr_account_id}.dkr.ecr.${aws_region}.amazonaws.com/${repo_path}/provider-aws-${family}:${version}
  skipDependencyResolution: true
  package: xpkg.upbound.io/upbound/provider-aws-${family}:${version}
  runtimeConfigRef:
    name: ${name}-runtime-config

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-${name}
spec:
  package: ${ecr-account-id}.dkr.ecr.${aws-region}.amazonaws.com/upbound/provider-family-aws:${version}
  package: xpkg.upbound.io/upbound/provider-family-aws:${version}
  runtimeConfigRef:
    name: ${name}-runtime-config

apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-${name}
spec:
  credentials:
    source: WebIdentity
    webIdentity:
      roleARN: ${provider_role_arn}
  assumeRoleChain:
    - roleARN: "arn:aws:iam::${account_id}:role/${role_name}"
```

### Steps to Reproduce

1. Deploy Crossplane v1.16 on EKS.
2. Install the AWS provider v1.6.0 using the provided manifests.
3. Create the `DeploymentRuntimeConfig` with the provided configuration.
4. Create the family `Provider` with the provided configuration.
5. Create the elbv2 `Provider` with the provided configuration.
6. Create the elbv2 `ProviderConfig` with the provided configuration.

### Actual Behavior

The `elbv2` provider deployment succeeds, but attempts to create any resource using the provider result in failure, accompanied by permission errors in the logs. The service account used by the provider does not have sufficient permissions to list `ProviderConfig` resources, preventing resource creation.

### Expected Behavior

The AWS provider's service account should have sufficient permissions to list `ProviderConfig` resources in the `aws.upbound.io` API group. This would allow the provider to create resources without encountering errors.

### Relevant Error Output Snippet

```shell
W0715 14:09:50.615204       1 reflector.go:539] k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: failed to list *v1beta1.ProviderConfig: providerconfigs.aws.upbound.io is forbidden:User "system:serviceaccount:crossplane-system:provider-upjet-aws-elbv2-99de9eeb558d" cannot list resource "providerconfigs" in API group "aws.upbound.io" at the cluster scope
E0715 14:09:50.615332       1 reflector.go:147] k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: Failed to watch *v1beta1.ProviderConfig: failed to list *v1beta1.ProviderConfig: providerconfigs.aws.upbound.io is forbidden: User "system:serviceaccount:crossplane-system:provider-upjet-aws-elbv2-99de9eeb558d" cannot list resource "providerconfigs" in API group "aws.upbound.io" at the cluster scope
```

### Crossplane Version

v1.16.0

### Provider Version

v1.6.0

### Kubernetes Version

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6-eks-db838b0

### Kubernetes Distribution

EKS

### Additional Info

- Providers such as IAM, EKS, and EC2 are working fine and do not encounter this error.
- However, other providers, including WAF, Api Gateway, ELBv2, and CloudFront, are not working and exhibit the same permission error.

If I manually add `cluster-admin` permission to the service account, the providers work perfectly. 

```sh
kubectl create clusterrolebinding elbv2-full-access --clusterrole=cluster-admin --serviceaccount=crossplane-system:provider-upjet-aws-elbv2-99de9eeb558d
```
