### ISSUE TITLE
[Bug]: Example for Tag resource specified ARN instead of resource Id

### ISSUE THREAD

**Issue by mtthwcmpbll** [crossplane-contrib/provider-upjet-aws#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

apiVersion: ec2.aws.upbound.io/v1beta1 - Tag

### Resource MRs required to reproduce the bug

From the example in the Upbound marketplace:
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Tag
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: Requires a valid resourceId as ARN.
  name: example
spec:
  forProvider:
    key: karpenter.sh/discovery
    region: us-west-1
    resourceId: <resourceid-arn>
    value: sample-eks-cluster
```

### Steps to Reproduce

Deploy the example Tag resource from the marketplace docs, placing in a valid AWS ARN for the resourceId

### What happened?

Based off of the example, I saved some managed resource ARNs into my EnvironmentConfig and then pulled them out in a composition to add tags using the Tag resource.  The Composition failed with an error that the Id `arn:...:subnet:...` wasn't a valid Id.  On switching this out for the AWS resource Id from my MR's status, Tags successfully worked as expected.

### Crossplane Version

0.16.0

### Provider Version

1.9.0

### Kubernetes Version

v1.30.1-eks-1de2ab1

### Kubernetes Distribution

EKS

### Additional Info

This is a documentation bug, but works as expected.  It would be nice if the Tag resource used a cross-resource references similar to many of the other resources in this provider, allowing you to select by MR name, labels, etc - this would allow me to tag multiple resources and it would line up with my preconceived expectations rather than have to sort out if this is a Crossplane ID, an AWS ID, or an ARN.  I think updating the example would solve this issue and reduce the confusion though.
