### ISSUE TITLE
[Bug]: Cloudfront Distributions Don't Change Status when Deploying

### ISSUE THREAD

**Issue by blakeromano** [crossplane-contrib/provider-upjet-aws#1404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

cloudfront.aws.upbound.io/v1beta2 - Distribution

### Resource MRs required to reproduce the bug

```yaml
---
apiVersion: cloudfront.aws.upbound.io/v1beta2
kind: Distribution
metadata:
  finalizers:
  - finalizer.managedresource.crossplane.io
  name: some-cf-distro
spec:
  deletionPolicy: Delete
  forProvider:
    aliases:
    - an.alias.com
    comment: Comment
    customErrorResponse:
    - errorCachingMinTtl: 0
      errorCode: 404
      responseCode: 200
      responsePagePath: /index.html
    defaultCacheBehavior:
      allowedMethods:
      - GET
      - OPTIONS
      - HEAD
      cachePolicyId: policy-id
      cachedMethods:
      - HEAD
      - GET
      compress: true
      functionAssociation:
      - eventType: viewer-response
        functionArn: funcArn
      targetOriginId: foo
      viewerProtocolPolicy: redirect-to-https
    defaultRootObject: index.html
    enabled: true
    httpVersion: http2and3
    isIpv6Enabled: true
    loggingConfig:
      bucket: bucket
      prefix: prefix
    origin:
    - domainName: bucket.s3.us-east-1.amazonaws.com
      originAccessControlId: OACID
      originAccessControlIdRef:
        name: OACIDREF
      originAccessControlIdSelector:
        matchControllerRef: true
      originId: foo
      originPath: /path
    priceClass: PriceClass_All
    region: us-east-1
    restrictions:
      geoRestriction:
        restrictionType: none
    retainOnDelete: true
    tags:
      foo: bar
    viewerCertificate:
      acmCertificateArn: CERT
      minimumProtocolVersion: TLSv1.2_2021
      sslSupportMethod: sni-only
    waitForDeployment: true
    webAclId: ""
  initProvider:
    webAclId: ""
  managementPolicies:
  - Create
  - LateInitialize
  - Observe
  - Update
  providerConfigRef:
    name: provider
```

### Steps to Reproduce

Create a Cloudfront Distribution, Update something about the distribution that causes the state to change (origin path, webaclid, etc;), notice how the status remains healthy and ready even though in AWS Console it is set to deploying and under `status.atProvider.status` it remains to say `Deployed` it never changes to `Deploying`

### What happened?

I expect it to change to a status of `Deploying` and for the status to be reconciled but not in a ready state.

### Crossplane Version

1.16.0

### Provider Version

1.7.0

### Kubernetes Version

1.29.4

### Kubernetes Distribution

EKS

**Comment by mbbush** [comment]
@blakeromano I'm going to try to do a little bit of "teaching you how to fish" here rather than debugging this myself. 

I'm most surprised by your report that `status.atProvider.status` differs from what is in AWS. Does that remain the case if you force the resource to reconcile by e.g. adding or changing an annotation during the time when AWS says the status is `Deploying`?

I would recommend looking at the implementation of the `read` and `update` methods for this resource in terraform-provider-aws. If those don't include the AWS SDK calls to read the status and set it in the terraform state, then that's where the bug is and where it should be fixed. But that seems unlikely to be the case.

Another possible explanation is that the sequence of events is something like this:
* Managed resource is updated.
* Provider calls the `update` method in the terraform sdk, asynchronously, then lies to crossplane-runtime (which doesn't have good async support) and says reconciliation completed successfully.
* The TF provider's `update` method does the update in aws, then blocks for a long time while waiting for the status to become healthy again.
* While `update` is blocking/polling aws, calls to `read` the resource are (maybe?) suppressed due to the ongoing async operation.
* By the time `update` finishes blocking, the status is `Deployed` again, so that's what the provider puts in the terraform status the next time it updates it.

It would also be helpful to see the various states of the resource as observed on your cluster, from `kubectl get -o yaml --watch` or similar. Debug logs from the provider would also help confirm/refute my possible explanation above.

**Comment by blakeromano** [comment]
So I took the example from the Marketplace, slightly modified it to

```yaml
apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: Distribution
metadata:
  name: example-distribution
spec:
  providerConfigRef:
    name: aws-provider
  initProvider:
    webAclId: ""
  forProvider:
    comment: Some comment
    defaultCacheBehavior:
      - allowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
        cachedMethods:
          - GET
          - HEAD
        defaultTtl: 3600
        forwardedValues:
          - cookies:
              - forward: none
            queryString: false
        maxTtl: 86401
        minTtl: 0
        targetOriginId: customOrigin
        viewerProtocolPolicy: allow-all
    defaultRootObject: index.html
    enabled: true
    isIpv6Enabled: true
    orderedCacheBehavior:
      - allowedMethods:
          - GET
          - HEAD
          - OPTIONS
        cachedMethods:
          - GET
          - HEAD
          - OPTIONS
        compress: true
        defaultTtl: 86400
        forwardedValues:
          - cookies:
              - forward: none
            headers:
              - Origin
            queryString: false
        maxTtl: 31536000
        minTtl: 0
        pathPattern: /content/immutable/*
        targetOriginId: customOrigin
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          - GET
          - HEAD
          - OPTIONS
        cachedMethods:
          - GET
          - HEAD
        compress: true
        defaultTtl: 3600
        forwardedValues:
          - cookies:
              - forward: none
            queryString: false
        maxTtl: 86400
        minTtl: 0
        pathPattern: /content/*
        targetOriginId: customOrigin
        viewerProtocolPolicy: redirect-to-https
    origin:
      - customOriginConfig:
          - httpPort: 80
            httpsPort: 443
            originKeepaliveTimeout: 5
            originProtocolPolicy: https-only
            originReadTimeout: 10
            originSslProtocols:
              - TLSv1.2
        domainName: app.my.cloud
        originId: customOrigin
    priceClass: PriceClass_200
    region: us-west-1
    restrictions:
      - geoRestriction:
          - locations:
              - US
              - CA
              - GB
              - DE
            restrictionType: whitelist
    tags:
      Environment: production
    viewerCertificate:
      - cloudfrontDefaultCertificate: true
```

On my local environment. I was again able to replicate it and I attached the output from the Cloudfront Provider Pod Logs on debug and the output of `k get distributions.cloudfront.aws.upbound.io -o yaml -w`
[logs.txt](https://github.com/user-attachments/files/16277527/logs.txt)
[out.txt](https://github.com/user-attachments/files/16277529/out.txt)


Based on what I see I think this may be a terraform bug because it does seem that the async reconciliation does start and then waits but doesn't update status. 

One thing I do find interesting is the `waitForDeployment` parameter defaults to true in Crossplane. I tried setting this to false the status looks like

```yaml
status:
  atProvider:
    arn: arn:aws:cloudfront::1234:distribution/E227N9TOPC91BM
    callerReference: terraform-20240718042935473200000003
    comment: Some comment 1
    continuousDeploymentPolicyId: ""
    defaultCacheBehavior:
      allowedMethods:
      - DELETE
      - GET
      - HEAD
      - OPTIONS
      - PATCH
      - POST
      - PUT
      cachePolicyId: ""
      cachedMethods:
      - GET
      - HEAD
      compress: false
      defaultTtl: 3600
      fieldLevelEncryptionId: ""
      forwardedValues:
        cookies:
          forward: none
        queryString: false
      maxTtl: 86401
      minTtl: 0
      originRequestPolicyId: ""
      realtimeLogConfigArn: ""
      responseHeadersPolicyId: ""
      smoothStreaming: false
      targetOriginId: customOrigin
      viewerProtocolPolicy: allow-all
    defaultRootObject: index.html
    domainName: d1jhf3v9x1dr7k.cloudfront.net
    enabled: true
    etag: EWCDHBK3407TQ
    hostedZoneId: Z2FDTNDATAQYW2
    httpVersion: http2
    id: E227N9TOPC91BM
    inProgressValidationBatches: 0
    isIpv6Enabled: true
    lastModifiedTime: 2024-07-18 04:29:35.964 +0000 UTC
    orderedCacheBehavior:
    - allowedMethods:
      - GET
      - HEAD
      - OPTIONS
      cachePolicyId: ""
      cachedMethods:
      - GET
      - HEAD
      - OPTIONS
      compress: true
      defaultTtl: 86400
      fieldLevelEncryptionId: ""
      forwardedValues:
        cookies:
          forward: none
        headers:
        - Origin
        queryString: false
      maxTtl: 31536000
      minTtl: 0
      originRequestPolicyId: ""
      pathPattern: /content/immutable/*
      realtimeLogConfigArn: ""
      responseHeadersPolicyId: ""
      smoothStreaming: false
      targetOriginId: customOrigin
      viewerProtocolPolicy: redirect-to-https
    - allowedMethods:
      - GET
      - HEAD
      - OPTIONS
      cachePolicyId: ""
      cachedMethods:
      - GET
      - HEAD
      compress: true
      defaultTtl: 3600
      fieldLevelEncryptionId: ""
      forwardedValues:
        cookies:
          forward: none
        queryString: false
      maxTtl: 86400
      minTtl: 0
      originRequestPolicyId: ""
      pathPattern: /content/*
      realtimeLogConfigArn: ""
      responseHeadersPolicyId: ""
      smoothStreaming: false
      targetOriginId: customOrigin
      viewerProtocolPolicy: redirect-to-https
    origin:
    - connectionAttempts: 3
      connectionTimeout: 10
      customOriginConfig:
        httpPort: 80
        httpsPort: 443
        originKeepaliveTimeout: 5
        originProtocolPolicy: https-only
        originReadTimeout: 10
        originSslProtocols:
        - TLSv1.2
      domainName: app.my.cloud
      originAccessControlId: ""
      originId: customOrigin
      originPath: ""
    priceClass: PriceClass_200
    restrictions:
      geoRestriction:
        locations:
        - CA
        - DE
        - GB
        - US
        restrictionType: whitelist
    retainOnDelete: false
    staging: false
    status: InProgress
    tags:
      Environment: production
      crossplane-kind: distribution.cloudfront.aws.upbound.io
      crossplane-name: example-distribution-1
      crossplane-providerconfig: aws-provider
    tagsAll:
      Environment: production
      crossplane-kind: distribution.cloudfront.aws.upbound.io
      crossplane-name: example-distribution-1
      crossplane-providerconfig: aws-provider
    trustedKeyGroups:
    - enabled: false
    trustedSigners:
    - enabled: false
    viewerCertificate:
      acmCertificateArn: ""
      cloudfrontDefaultCertificate: true
      iamCertificateId: ""
      minimumProtocolVersion: TLSv1
      sslSupportMethod: ""
    waitForDeployment: false
    webAclId: ""
  conditions:
  - lastTransitionTime: "2024-07-18T04:29:37Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-07-18T04:29:35Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-07-18T04:29:36Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
```

Note the `status: InProgress` here versus when we have `waitForDeployment: true` we never see the status be anything outside of deployment. My hunch is there is a conflict in logic with these two.

I may have a not clear picture as to what is possible with Upjet but my initial thought is to essentially remove `waitForDeployment` and instead of keying off of the normal status we do in the rest of the resources we should key off of the `status.atProvider.status` and if we see that status as Deployed we should mark resource as ready otherwise it shouldn't be marked as ready.
