### ISSUE TITLE
[Bug]: Lambda Function Not Updating `sourceCodeHash` After Code Change in S3

### ISSUE THREAD

**Issue by isarns** [crossplane-contrib/provider-upjet-aws#1412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* lambda.aws.upbound.io/v1beta1 - Function

### Resource MRs required to reproduce the bug

   ```yaml
   apiVersion: lambda.aws.upbound.io/v1beta1
   kind: Function
   metadata:
     name: test
     labels:
       crossplane-name: test
   spec:
     forProvider:
       region: us-east-2
       handler: lambda_function.lambda_handler
       publish: true
       runtime: python3.9
       s3Bucket: my-bucket
       s3Key: hello.zip
       timeout: 5
       roleSelector:
         matchLabels:
           testing.upbound.io/example-name: role
   ```

### Steps to Reproduce

1. Note the initial `atProvider.sourceCodeHash` value:
   ```
   em8C9XMtWVk1kNrZOJ/5ELfRgSDPJhTaQY7iGvxKoJE=
   ```

2. Update the lambda function code and ship the new version to S3. New file hash:
   ```
   9WRqFbNkSofuQcpPlTXC5T27Ou/V0IMEX0nZTxrwFmA=
   ```

3. Observe that the `atProvider.sourceCodeHash` in the MR does not update and remains:
   ```
   em8C9XMtWVk1kNrZOJ/5ELfRgSDPJhTaQY7iGvxKoJE=
   ```

## Expected Behavior
The `sourceCodeHash` should update automatically when the code in S3 is changed without needing to delete and recreate the MR.

## Actual Behavior
The `sourceCodeHash` remains unchanged unless the MR is deleted and recreated.

### Crossplane Version

1.15.0

### Provider Version

1.9.0

### Kubernetes Version

1.28

### Kubernetes Distribution

EKS
