### ISSUE TITLE
[Bug]: Domain.opensearch enters the update loop and the diff is detected

### ISSUE THREAD

**Issue by turkenf** [crossplane-contrib/provider-upjet-aws#1420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

opensearch.aws.upbound.io/v1beta2 - Domain

### Resource MRs required to reproduce the bug

```
apiVersion: opensearch.aws.upbound.io/v1beta2
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: opensearch/v1beta2/domain
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterConfig:
      instanceType: m4.large.search
    domainName: upbound-test-domain
    ebsOptions:
      ebsEnabled: true
      volumeSize: 10
      volumeType: gp2
    engineVersion: OpenSearch_1.0
    region: us-west-1
```

### Steps to Reproduce

Install the provider and apply the above manifest. The resource takes over 20 minutes to create.

### What happened?

After the resource is created, diff is detected and enters the update loop.

### Relevant Error Output Snippet

```shell
2024-07-24T20:44:13Z	DEBUG	provider-aws	Diff detected	{"uid": "9718adbb-5ce6-4db6-9b8a-ede55f107cdc", "name": "example", "gvk": "opensearch.aws.upbound.io/v1beta1, Kind=Domain", "instanceDiff": "*terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{\"advanced_security_options.#\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, RawConfig:cty.NilVal, RawState:cty.NilVal, RawPlan:cty.NilVal, Meta:map[string]interface {}(nil)}"}
```

### Crossplane Version

1.16.0

### Provider Version

1.9.0
