### ISSUE TITLE
[Bug]: Blue/Green deployment upgrade fails on MAZ instance with error like "A Blue Green Deployment with the name 'testMAZ' already exists  []}]"

### ISSUE THREAD

**Issue by StanleyShen** [crossplane-contrib/provider-upjet-aws#1430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* ec2.aws.upbound.io/v1beta2 - Instance

### Resource MRs required to reproduce the bug

I deployed a MAZ instance with blue/green deployment enabled
```yaml
apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta2/instance
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: example-dbinstance
  name: postgresqlmaz2
spec:
  providerConfigRef:
    name: rdstest
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 1
    backupWindow: 09:46-10:16
    dbName: testmaz
    identifier: testmaz
    username: testmaz
    engine: postgres
    engineVersion: "15.6"
    parameterGroupName: "pg156"
    instanceClass: db.t3.micro
    maintenanceWindow: Mon:00:00-Mon:03:00
    dbSubnetGroupName: testmaz
    publiclyAccessible: false
    blueGreenUpdate:
      - enabled: true
    region: us-east-1
    skipFinalSnapshot: true
    multiAz: true
    storageEncrypted: true
    storageType: gp3
    autoGeneratePassword: true
    passwordSecretRef:
      key: password
      name: example-dbinstance-maz
      namespace: crossplane-system
```

And manifest for version 16
```yaml
apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta2/instance
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: example-dbinstance
  name: postgresqlmaz2
spec:
  providerConfigRef:
    name: rdstest
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 1
    backupWindow: 09:46-10:16
    dbName: testmaz
    identifier: testmaz
    username: testmaz
    engine: postgres
    engineVersion: "16"
    parameterGroupName: "pg16"
    instanceClass: db.t3.micro
    maintenanceWindow: Mon:00:00-Mon:03:00
    dbSubnetGroupName: testmaz
    publiclyAccessible: false
    blueGreenUpdate:
      - enabled: true
    region: us-east-1
    skipFinalSnapshot: true
    multiAz: true
    storageEncrypted: true
    storageType: gp3
    autoGeneratePassword: true
    passwordSecretRef:
      key: password
      name: example-dbinstance-maz
      namespace: crossplane-system
```

### Steps to Reproduce

* create a MAZ postgres instance with version 15.6
* upgrade MAZ postgres instance to version 16 

After apply manifest to upgrade MAZ instance to v16, and I see below errors when blue/green deployment get created in UI, and green environment get upgraded to v16, and then the blue/green upgrade stops with below errors
```bash
  {
    "lastTransitionTime": "2024-07-30T15:49:53Z",
    "reason": "Available",
    "status": "True",
    "type": "Ready"
  },
  {
    "lastTransitionTime": "2024-07-30T16:28:20Z",
    "message": "update failed: async update failed: failed to update the resource: [{0 updating RDS DB Instance (testmaz): creating Blue/Green Deployment: operation error RDS: CreateBlueGreenDeployment, https response error StatusCode: 400, RequestID: 1be9dd5a-956f-410
8-90f4-5b3f5d640c6b, BlueGreenDeploymentAlreadyExistsFault: A Blue Green Deployment with the name 'testmaz' already exists  []}]",
    "reason": "ReconcileError",
    "status": "False",
    "type": "Synced"
  },
  {
    "lastTransitionTime": "2024-07-30T16:28:20Z",
    "message": "async update failed: failed to update the resource: [{0 updating RDS DB Instance (testmaz): creating Blue/Green Deployment: operation error RDS: CreateBlueGreenDeployment, https response error StatusCode: 400, RequestID: 1be9dd5a-956f-4108-90f4-5b3f5d64
0c6b, BlueGreenDeploymentAlreadyExistsFault: A Blue Green Deployment with the name 'testmaz' already exists  []}]",
    "reason": "AsyncUpdateFailure",
    "status": "False",
    "type": "LastAsyncOperation"
  }
]
```

And the switch over never happens, and we have both blue/green environment in Available status in AWS console.

### What happened?

* the switch over never happens
* instance not in sync status because of above errors

### Crossplane Version

1.16.0

### Provider Version

1.10.0

### Kubernetes Version

v1.28.9-eks-036c24b

### Kubernetes Distribution

EKS
