### ISSUE TITLE
[Bug]: ClusterAuth controller doesn't inherit the feature settings

### ISSUE THREAD

**Issue by r-nasiri** [crossplane-contrib/provider-upjet-aws#1438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

eks.aws.upbound.io/v1beta1 - ClusterAuth

### Resource MRs required to reproduce the bug
```

apiVersion: eks.aws.upbound.io/v1beta1
kind: ClusterAuth
metadata:
  name: my-cluster-auth
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-clusterauth
    region: us-west-1
  managementPolicies:
  - Create
  - Observe
  - LateInitialize
```

### Steps to Reproduce

1. Create the ClusterAuth resource without the managementPolicies set
2. Make sure the ClusterAuth is created successfully.
3. Add the managementPolicies to ClusterAuth resource
4. the resource is not reconciled and generates error

### What happened?

all other resources in eks.aws.upbound.io provider allow setting the managementPolicies but ClusterAuth controller generates an error.

### Relevant Error Output Snippet

```shell
spec.managementPolicies is set to a non-default value but the feature is not enabled: [Create LateInitialize Observe]
```

### Crossplane Version

1.16.0

### Provider Version

1.10.0

### Kubernetes Version

1.29

### Kubernetes Distribution

EKS
