### ISSUE TITLE
[Bug]: The old family Provider and ProviderRevision left when manually installed

### ISSUE THREAD

**Issue by pierluigilenoci** [crossplane-contrib/provider-upjet-aws#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

No resources affected

### Resource MRs required to reproduce the bug

No resources needed

### Steps to Reproduce

To reproduce the problem:

1. Install the providers WITHOUT family provider
2. Once the automatic family provider appears, try to install the family provider manually
3. Find a way to make the automatic family Provider and ProviderRevision manifests disappear

### What happened?

I expect the automatically installed version will disappear when the family provider is installed manually.

Of course, everything works on a clean cluster.
I am looking for a way to switch from automatic to manual family provider without reinstalling Crossplane in a cluster where there are already MRs used in production.

This is a follow-up bug concerning #1088

More details in the Slack discussion: https://crossplane.slack.com/archives/C05E0UE46S2/p1722852504359609

### Relevant Error Output Snippet

```shell
kubectl get providers.pkg.crossplane.io
NAME                          INSTALLED   HEALTHY   PACKAGE                                                          AGE
provider-aws-cloudwatchlogs   True        True      xpkg.upbound.io/upbound/provider-aws-cloudwatchlogs:v1.6.0       283d
provider-aws-dynamodb         True        True      xpkg.upbound.io/upbound/provider-aws-dynamodb:v1.6.0             109d
provider-aws-ec2              True        True      xpkg.upbound.io/upbound/provider-aws-ec2:v1.6.0                  389d
provider-aws-elasticache      True        True      xpkg.upbound.io/upbound/provider-aws-elasticache:v1.6.0          389d
provider-aws-iam              True        True      xpkg.upbound.io/upbound/provider-aws-iam:v1.6.0                  389d
provider-aws-mq               True        True      xpkg.upbound.io/upbound/provider-aws-mq:v1.6.0                   389d
provider-aws-rds              True        True      xpkg.upbound.io/upbound/provider-aws-rds:v1.6.0                  389d
provider-aws-s3               True        True      xpkg.upbound.io/upbound/provider-aws-s3:v1.6.0                   389d
provider-family-aws           True        True      xpkg.upbound.io/upbound/provider-family-aws:v1.6.0               5d1h
provider-kubernetes           True        True      xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.0   301d
provider-sql                  True        True      xpkg.upbound.io/crossplane-contrib/provider-sql:v0.9.0           287d
provider-terraform            True        True      xpkg.upbound.io/upbound/provider-terraform:v0.16.0               389d
upbound-provider-family-aws   True        False     xpkg.upbound.io/upbound/provider-family-aws:v1.10.0              3d20h
```
```

### Crossplane Version

v1.16.0-up.1

### Provider Version

1.6.0

### Kubernetes Version

v1.27.15

### Kubernetes Distribution

EKS

### Additional Info

This is a follow-up bug concerning #1088

**Comment by darioef** [comment]
Same problem here.

Tried @haarchri suggestion but the manual provider doesn't come to a HEALTY: True state because it says that the automatic one still exists.

```
status:
  conditions:
    - lastTransitionTime: '2024-08-09T12:18:03Z'
      message: >-
        cannot resolve package dependencies: cannot initialize dependency graph
        from the packages in the lock: node
        xpkg.upbound.io/upbound/provider-family-aws already exists
      reason: UnknownPackageRevisionHealth
      status: Unknown
      type: Healthy
```

I need to manually install the provider-family-aws because I realized that I'm running it on version v0.38.0, while the other providers (S3, Route53, etc.) are on version v1.0.0. Honestly, I don't know what happened, but it seems that even if I update the version of the Upbound AWS Providers image, provider-family-aws still remains on the old version and continues to install automatically with that version.

**Comment by haarchri** [comment]
Can you remove you Lock Lock resource remove the finalizer

**Comment by dario-fernandez-osanasalud** [comment]
You're the man. It worked!

So, the steps are the same as https://github.com/crossplane-contrib/provider-upjet-aws/issues/1452#issuecomment-2275922781 but you need to remove the Lock resource after you install the manual-provider-family-aws.

Thanks for your help.

**Comment by darioef** [comment]
You're the man. It worked!

So, the steps are the same as https://github.com/crossplane-contrib/provider-upjet-aws/issues/1452#issuecomment-2275922781 but you need to remove the Lock resource after you install the manual-provider-family-aws.

Thanks for your help.

**Comment by turkenh** [comment]
The complication here originated from deploying the same provider package twice (one already existing as a dependency and another installed manually). In the PR description, both `provider-family-aws` and `upbound-provider-family-aws` try to deploy `xpkg.upbound.io/upbound/provider-family-aws` under the hood and conflict with each other.

Ideally, if you have the family provider already deployed as a dependency and you want to change something, e.g. configure a `DeploymentRuntimeConfig`, the path to go should be editing/patching the already existing provider instead of deploying a separate `Provider` object with a different name. In the scenario here, the provider named `upbound-provider-family-aws` could be modified with `spec.runtimeConfigRef` in the first place.

**Comment by darioef** [comment]
Thanks for your explanation, in fact, another reason why I want to manually install the provider-family-aws is that when it's installed via a Provider dependency (e.g., the S3 provider), it doesn't respect the configured DeploymentRuntimeConfig and instead applies the default one. I need to use my RuntimeConfig because I've set tolerations and other deployment settings there.

I think this comment talk about the same problem: https://github.com/crossplane-contrib/provider-upjet-aws/issues/1088#issuecomment-2211198483

**Comment by pierluigilenoci** [comment]
@haarchri, thank you a lot.

I managed to clean the clusters but not with little difficulty because the suggestion was not 100% working.

The complete list of operations needed were:
- set the revisionActivationPolicy to Manual in both installed Family Providers
- remove the finalizer inside the lock file
- delete the Lock (if not already gone after removing the finalizer)
- delete the old Provider and ProviderRevision

Often, this was enough. Sometimes, I had to do it twice to clean the cluster.

@turkenh, this is not a complication but a plausible scenario.

If anyone initially installs the AWS Family provider but then realizes, for whatever reason, the need to assign a DeploymentRuntimeConfig to the automatically created provider and finish precisely in this situation.

Manually editing the provider is not a plausible solution in a fully GitOps approach, so a more integrated solution makes profound sense.

Furthermore, users should be able to choose their provider's name without impositions or hard-coded names.

This bug is far from being solved because what we have is just a workaround, not a fix for the problem.

**Comment by pierluigilenoci** [comment]
![8b0c4526d4275ea4fbf27c30d0d01d72](https://github.com/user-attachments/assets/6460cbf0-817e-49de-a985-fe731820c182)

**Comment by tennix** [comment]
> [@haarchri](https://github.com/haarchri), thank you a lot.
> 
> I managed to clean the clusters but not with little difficulty because the suggestion was not 100% working.
> 
> The complete list of operations needed were:
> 
> * set the revisionActivationPolicy to Manual in both installed Family Providers
> * remove the finalizer inside the lock file
> * delete the Lock (if not already gone after removing the finalizer)
> * delete the old Provider and ProviderRevision
> 
> Often, this was enough. Sometimes, I had to do it twice to clean the cluster.
> 
> [@turkenh](https://github.com/turkenh), this is not a complication but a plausible scenario.
> 
> If anyone initially installs the AWS Family provider but then realizes, for whatever reason, the need to assign a DeploymentRuntimeConfig to the automatically created provider and finish precisely in this situation.
> 
> Manually editing the provider is not a plausible solution in a fully GitOps approach, so a more integrated solution makes profound sense.
> 
> Furthermore, users should be able to choose their provider's name without impositions or hard-coded names.
> 
> This bug is far from being solved because what we have is just a workaround, not a fix for the problem.

Yes, this workaround is very inconvenient in a fully GitOps approach. I found another workaround solution by setting provider `spec.skipDependencyResultion: true`. Without dependency resolution, we need to manually resolve the dependency. Usually this means we need to add provider-family `Provider` which is what we need. In a GitOps environment, the dependency resolution can be verified in a local `kind` cluster environment.

**Comment by pierluigilenoci** [comment]
![Image](https://github.com/user-attachments/assets/92459a16-9691-4981-b855-82d52c96aabe)

**Comment by ulucinar** [comment]
Hi @pierluigilenoci,
I gave your scenario a try using UXP v2.1.1-up.1:
- Installed a smaller scoped AWS provider package using the following manifest:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:v2.2.0
  runtimeConfigRef:
    name: config-aws

---

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: config-aws
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            args:
            - -d
```
- After a while, the smaller scoped provider package and the AWS family provider package both become ready:
```shell
> kubectl get providers.pkg

NAME                          INSTALLED   HEALTHY   PACKAGE                                              AGE
provider-aws-iam              True        True      xpkg.upbound.io/upbound/provider-aws-iam:v2.2.0      95s
upbound-provider-family-aws   True        True      xpkg.upbound.io/upbound/provider-family-aws:v2.2.0   91s
```
The family provider package (`upbound-provider-family-aws`) gets automatically installed because the smaller scoped provider package declares a dependency on it and we have not set `spec.skipDependencyResolution` to `true` in `providers.pkg.crossplane.io/provider-aws-iam` above.
- Now I provision a `ProviderConfig` (legacy cluster-scoped) and an MR using the following manifest (secret not shown):
```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: creds
      name: aws-creds
      namespace: crossplane-system
    source: Secret

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: sample-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
```
- After a while, the MR should become sync'ed & ready:
```yaml
> kubectl get managed

NAME                                  SYNCED   READY   EXTERNAL-NAME   AGE
role.iam.aws.upbound.io/sample-role   True     True    sample-role     4s
```
- Now comes the interesting part. I attempt to manually install the AWS family provider package using the same source with the following manifest:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: manual-provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v2.2.0
  runtimeConfigRef:
    name: config-aws
```
Please note that it refers to the already existing `DeploymentRuntimeConfig` object.
- Now, Crossplane's package manager attempts to install the new package and while doing so, attempts to update the [`Lock.pkg.crossplane.io`](https://github.com/crossplane/crossplane/blob/9da017c13044e2ee8d0a826901179d933c1f9d5d/apis/pkg/v1beta1/lock.go#L201) object that it uses to track installed packages and their dependencies.
But the dependency graph should be a DAG and thus, no cycles are allowed. Nodes representing packages are defined by their sources and not the Kubernetes resource names. So, the `Provider.pkg` objects with names `manual-provider-family-aws` and `upbound-provider-family-aws` correspond to the same dependency node in the DAG, resulting in a cycle. You will observe that all the `Provider.pkg` objects installed so far are in unhealthy state:
```shell
> kubectl get providers.pkg

NAME                          INSTALLED   HEALTHY   PACKAGE                                              AGE
manual-provider-family-aws    True        False     xpkg.upbound.io/upbound/provider-family-aws:v2.2.0   8m34s
provider-aws-iam              True        False     xpkg.upbound.io/upbound/provider-aws-iam:v2.2.0      19m
upbound-provider-family-aws   True        False     xpkg.upbound.io/upbound/provider-family-aws:v2.2.0   18m
```
And if you describe one of them, you will observe:
```shell
> kubectl describe providers.pkg manual-provider-family-aws

...
Status:
  Conditions:
    Last Transition Time:  2025-11-21T18:10:18Z
    Message:               Package revision health is "False" with message: cannot resolve package dependencies: cannot initialize dependency graph from the packages in the lock: node xpkg.upbound.io/upbound/provider-family-aws already exists
...
```
Please note how the error message identifies the node detected in a cycle as `xpkg.upbound.io/upbound/provider-family-aws` (the "source" of the package).


Now, we would like to remove the auto-installed dependency (`Provider.pkg.crossplane.io/upbound-provider-family-aws`) and keep `manual-provider-family-aws`, as it refers to a non-default `DeploymentRuntimeConfig` with the specific runtime configuration we would like to achieve. The way to do so is:

- First, we need to disable auto-dependency resolution for the provider package that declared the dependency on the AWS provider family package:
```shell
> kubectl patch providers.pkg.crossplane.io provider-aws-iam --type=merge -p='{"spec":{"skipDependencyResolution": true}}'
```
- Now, attempt to delete the auto-installed dependency:
```shell
> kubectl delete providers.pkg upbound-provider-family-aws

provider.pkg.crossplane.io "upbound-provider-family-aws" deleted
```
- Now, if you observe the provider package statuses,  you will see that the manually installed provider package in in unhealthy state:
```shell
> k get providers.pkg

NAME                         INSTALLED   HEALTHY   PACKAGE                                              AGE
manual-provider-family-aws   True        False     xpkg.upbound.io/upbound/provider-family-aws:v2.2.0   18m
provider-aws-iam             True        True      xpkg.upbound.io/upbound/provider-aws-iam:v2.2.0      28m

> kubectl describe providers.pkg  manual-provider-family-aws

...
Status:
  Conditions:
    Last Transition Time:  2025-11-21T18:27:20Z
    Message:               Package revision health is "False" with message: cannot establish control of object: providerconfigs.aws.upbound.io is already controlled by ProviderRevision upbound-provider-family-aws-0e8a4558ea96 (UID d92e1574-0fc0-47ef-9f3b-3834901339cb)
...
```
This is probably a variant of https://github.com/crossplane/crossplane/issues/6761. Please note that what you are trying to achieve here (installing two `Providers.pkg` with the same source) is not allowed, but the assumption is the user accidentally does this and is trying to recover from this situation...
- Now, if you remove the existing owner reference on the CRD causing the failure, the package should become healthy. 
```shell
> kubectl patch crd providerconfigs.aws.upbound.io --type=merge -p='{"metadata":{"ownerReferences":[]}}'

customresourcedefinition.apiextensions.k8s.io/providerconfigs.aws.upbound.io patched

> kubectl get providers.pkg

NAME                         INSTALLED   HEALTHY   PACKAGE                                              AGE
manual-provider-family-aws   True        True      xpkg.upbound.io/upbound/provider-family-aws:v2.2.0   25m
provider-aws-iam             True        True      xpkg.upbound.io/upbound/provider-aws-iam:v2.2.0      35m
```
- This causes `customresourcedefinition.apiextensions.k8s.io/providerconfigs.aws.upbound.io` to be deleted and reinstalled and the `ProviderConfig.providerconfigs.aws.upbound.io` object to be also deleted. You will need to reprovision it.
```shell
> kubectl apply -f providerconfig.yaml

> kubectl get managed

NAME                                  SYNCED   READY   EXTERNAL-NAME   AGE
role.iam.aws.upbound.io/sample-role   True     True    sample-role     30m
```

As discussed above, the proper way to achieve your intent is to install the smaller scoped provider by disabling dependency resolution:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:v2.2.0
  skipDependencyResolution: true
  runtimeConfigRef:
    name: config-aws

---

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: manual-provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v2.2.0
  runtimeConfigRef:
    name: config-aws

---

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: config-aws
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            args:
            - -d
```

This discussion is for how you can recover from the error state in case you accidentally installed two family provider packages of the same source, one installed via dependency resolution and the other being manually installed.
