### ISSUE TITLE
[Bug]: MQ Broker resource enters an infinite update loop if adjacent MQ Configuration is updated

### ISSUE THREAD

**Issue by anagarlau** [crossplane-contrib/provider-upjet-aws#1454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* mq.aws.upbound.io/v1beta1 - Configuration
* mq.aws.upbound.io/v1beta2 - Broker

### Resource MRs required to reproduce the bug

* Configuration  1

```
apiVersion: mq.aws.upbound.io/v1beta1
kind: Configuration
metadata:
  name: example
spec:
  forProvider:
    # Due to an existing Terrajet limitation, we cannot use "metadata.name" for "name"
    # Details can be found in https://github.com/crossplane/terrajet/issues/280
    name: example-config-new
    region: eu-central-1
    data: |
      <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
      <broker xmlns="http://activemq.apache.org/schema/core">
        <plugins>
          <forcePersistencyModeBrokerPlugin persistenceFlag="true"/>
          <statisticsBrokerPlugin/>
          <timeStampingBrokerPlugin ttlCeiling="86400000" zeroExpirationOverride="86400000"/>
        </plugins>
      </broker>
    description: Example Configuration
    engineType: ActiveMQ
    engineVersion: 5.16.7
  providerConfigRef:
    name: my-provider-config
```

* Broker 1
```
apiVersion: mq.aws.upbound.io/v1beta2
kind: Broker
metadata:
  name: example-conf
spec:
  forProvider:
    autoMinorVersionUpgrade: true
    brokerName: example-broker-conf
    configuration:
      id: <configuration id>
      revision: 2
    deploymentMode: SINGLE_INSTANCE
    engineType: ActiveMQ
    engineVersion: 5.16.7
    hostInstanceType: mq.m5.large
    publiclyAccessible: false
    region: eu-central-1
    securityGroupRefs:
      - name: <sg-name>
    storageType: EFS
    subnetIds:
      - <subnetId>
  initProvider:
    user:
    - passwordSecretRef:
        key: password
        name:  example-secret 
        namespace: my-namespace
      username: admin
  writeConnectionSecretToRef:
    name: conf-broker
    namespace: my-namespace
  providerConfigRef:
    name: my-provider-config
```

* Configuration  2 

```
apiVersion: mq.aws.upbound.io/v1beta1
kind: Configuration
metadata:
  name: example
spec:
  forProvider:
    # Due to an existing Terrajet limitation, we cannot use "metadata.name" for "name"
    # Details can be found in https://github.com/crossplane/terrajet/issues/280
    name: example-config-new
    region: eu-central-1
    data: |
      <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
      <broker xmlns="http://activemq.apache.org/schema/core">
        <plugins>
          <forcePersistencyModeBrokerPlugin persistenceFlag="true"/>
          <statisticsBrokerPlugin/>
          <timeStampingBrokerPlugin ttlCeiling="87400000" zeroExpirationOverride="86400000"/>
        </plugins>
      </broker>
    description: Example Configuration
    engineType: ActiveMQ
    engineVersion: 5.16.7
  providerConfigRef:
    name: my-provider-config
```
* Broker 2
```
apiVersion: mq.aws.upbound.io/v1beta2
kind: Broker
metadata:
  name: example-conf
spec:
  forProvider:
    autoMinorVersionUpgrade: true
    brokerName: example-broker-conf
    configuration:
      id: <configuration id>
      revision: 3
    deploymentMode: SINGLE_INSTANCE
    engineType: ActiveMQ
    engineVersion: 5.16.7
    hostInstanceType: mq.m5.large
    publiclyAccessible: false
    region: eu-central-1
    securityGroupRefs:
      - name: <sg-name>
    storageType: EFS
    subnetIds:
      - <subnetId>
  initProvider:
    user:
    - passwordSecretRef:
        key: password
        name:  example-secret 
        namespace: my-namespace
      username: admin
  writeConnectionSecretToRef:
    name: conf-broker
    namespace: my-namespace
  providerConfigRef:
    name: my-provider-config
```

### Steps to Reproduce

Steps to Reproduce
* Install the provider-aws-mq
* Apply the first yaml file (Configuration 1)
* Wait until the Configuration is created
* Apply the first Broker yaml file (Broker 1)
* Wait until the Broker is created
* Apply the second Configuration yaml file (Configuration 2) to create a new revision (diff ) 
* Diff in ttlCeiling:         ` <timeStampingBrokerPlugin ttlCeiling="86400000" zeroExpirationOverride="86400000"/>  to <timeStampingBrokerPlugin ttlCeiling="87400000" zeroExpirationOverride="86400000"/>**`
*  Wait until the Configuration revision  is created
* Update Broker with the newest configuration revision (3)
 

### What happened?

When trying to update the Broker with the latest Configuration revision, the Broker enters the update loop and continuously sends update calls until the Broker is rebooted and the update loop is exited. 

```
Events  
 Normal   UpdatedExternalResource         41s (x**2818** over 22m)  managed/mq.aws.upbound.io/v1beta1, kind=broker  Successfully requested update of external resource      
``` 
 

### Crossplane Version

v1.16.0

### Provider Version

v1.9.0

### Kubernetes Version

v1.28.11

### Kubernetes Distribution

EKS

### Additional Info

* This bug is similar to the effect setting consoleAccess in MQ User has => infinite update loop
* Also reminiscent of this: https://github.com/crossplane-contrib/provider-upjet-aws/pull/1325/commits/29aa8ba500eb58d7dd788607afcec3a6eec0f773
