### ISSUE TITLE
[Bug]: Elasticache Cluster `autoMinorVersionUpgrade` should be bool

### ISSUE THREAD

**Issue by excalq** [crossplane-contrib/provider-upjet-aws#1464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* elasticache.aws.upbound.io/v1beta1 - Cluster

### Resource MRs required to reproduce the bug

```
apiVersion: elasticache.platform.example.io/v1alpha1
kind: Cache
metadata:
  name: test-elasticache-claim
  namespace: testing
spec:
  parameters:
    name: test-elasticache
    region: us-east-2
    engine: redis
    engineVersion: "7.1"
    family: redis7.1
    nodeType: cache.t3.small
    numCacheNodes: 1 # Must be 1 for Redis
    applyImmediately: true
    autoMinorVersionUpgrade: "true"
...
```

### Steps to Reproduce

The CRD for Elasticache's parameter, `autoMinorVersionUpgrade` expects a `string` value (e.g. "true"), when this should be boolean, as exists in the similar RDS CRDs and in EC's Terraform AWS provider.

Upbound Provider Docs: https://marketplace.upbound.io/providers/upbound/provider-aws-elasticache/v1.11.0/resources/elasticache.aws.upbound.io/Cluster/v1beta1#doc:spec-forProvider-autoMinorVersionUpgrade

Source definition: https://github.com/crossplane-contrib/provider-upjet-aws/blob/main/apis/elasticache/v1beta1/zz_cluster_types.go#L45

Terraform Provider source: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/cluster.go#L66

### What happened?

The cluster resources fails to create, with the observed error as follows.

### Relevant Error Output Snippet

```shell
The composite resource emits the following error: `(combined from similar events): cannot compose resources: cannot apply composed resource "cluster": failed to create typed patch object (/test-elasticache-claim-6zhln-65c7x; elasticache.aws.upbound.io/v1beta1, Kind=Cluster): .spec.forProvider.autoMinorVersionUpgrade: expected string, got &value.valueUnstructured{Value:true}`
```

### Crossplane Version

1.15

### Provider Version

1.10.0

### Kubernetes Version

v1.29.6-eks-db838b0

### Kubernetes Distribution

EKS
