### ISSUE TITLE
[Bug]: IRSA can no longer default to the node role

### ISSUE THREAD

**Issue by vibe** [crossplane-contrib/provider-upjet-aws#1466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Resource MRs required to reproduce the bug

```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: IRSA
```

### Steps to Reproduce

* Deploy AWS Provider with a default config with credentials source set to IRSA.

### What happened?

Related to Issue #1252 

Versions prior to 1.3, allowed configuring IRSA with no further annotations, which defaulted to the using the node role.

Not sure I quite follow the "why", but the new cache implementation *requires* `AWS_WEB_IDENTITY_TOKEN_FILE` to exist otherwise it will fail.

https://github.com/crossplane-contrib/provider-upjet-aws/blob/dedf6569b6084e25515a449ea2266a394538fb52/internal/clients/creds_cache.go#L188-L189

### Crossplane Version

1.6

### Provider Version

1.11

### Additional Info

EKS
