### ISSUE TITLE
[Bug]: Nodegroup late-initializes scaling config provided only in InitProvider

### ISSUE THREAD

**Issue by turkenh** [crossplane-contrib/provider-upjet-aws#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* eks NodeGroup

### Resource MRs required to reproduce the bug

A NodeGroup with only `spec.initProvider.scalingConfig` (desired/initial/max size) but no `spec.forProvider.scalingConfig`.

### Steps to Reproduce

1. Create a `NodeGroup` with only `spec.initProvider.scalingConfig` but no `spec.forProvider.scalingConfig`
2. Get the resource back once it is ready
3. Check whether there is a `spec.forProvider.scalingConfig`

### What happened?

`spec.forProvider.scalingConfig` late initialized with the values we provided in `spec.initProvider.scalingConfig`

This result in conflicts with the auto scalers where both are trying to desired node size.

### Relevant Error Output Snippet

```shell
N/A
```

### Crossplane Version

v1.16.0-up.1

### Provider Version

v1.8.0

**Comment by haarchri** [comment]
what we doing today looks like:

```
...
spec:
  initProvider:
    scalingConfig:
      - desiredSize: 5
  forProvider:
    scalingConfig:
      - minSize: 1
        maxSize: 10
```
