### ISSUE TITLE
[Bug]: RDS Cluster capacity does not support half steps for Aurora serverless

### ISSUE THREAD

**Issue by tvandinther** [crossplane-contrib/provider-upjet-aws#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* rds.aws.upbound.io/v1beta1 - Cluster

### Resource MRs required to reproduce the bug

Minimal example:
```
apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: database
spec:
  forProvider:
    engine: aurora-postgresql
    engineVersion: "16.1"
    engineMode: serverless
    skipFinalSnapshot: false
    scalingConfiguration:
      - minCapacity: 0.5
        maxCapacity: 1
        autoPause: true
        secondsUntilAutoPause: 300
```

### Steps to Reproduce

Apply this MR on v1.12.0 of the provider-aws-rds.

### What happened?

ParseInt errors on the value `0.5`. Half steps are supported by AWS for serverless Aurora.

### Relevant Error Output Snippet

```shell
E0830 09:22:15.461803       1 runtime.go:79] Observed a panic: &errors.errorString{s:"Error reading level state: strconv.ParseInt: parsing \"0.5\": invalid syntax"} (Error reading level state: strconv.ParseInt: parsing "0.5": invalid syntax)
```
```


### Crossplane Version

1.16.0

### Provider Version

1.12.0

### Kubernetes Version

1.30

### Kubernetes Distribution

EKS

### Additional Info

_No response_
