### ISSUE TITLE
[Bug]: Elasticache Parameter Group Name Is Not Required in CRD

### ISSUE THREAD

**Issue by blakeromano** [crossplane-contrib/provider-upjet-aws#1486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* elasticache.aws.upbound.io/v1beta1 - ParameterGroup

### Resource MRs required to reproduce the bug

```yaml
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ParameterGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1beta1/parametergroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    family: redis2.8
    parameter:
      - name: activerehashing
        value: yes
      - name: min-slaves-to-write
        value: "2"
    region: us-west-1
```

### Steps to Reproduce

Apply this resource and see how it fails due to the `name` not being set.

### What happened?

Nothing in docs https://marketplace.upbound.io/providers/upbound/provider-aws-elasticache/v1.13.0/resources/elasticache.aws.upbound.io/ParameterGroup/v1beta1 or in the CRD https://github.com/crossplane-contrib/provider-upjet-aws/blob/main/package/crds/elasticache.aws.upbound.io_parametergroups.yaml#L107-L108 denotes that the name parameter should be required however in the underlying TF provider https://registry.terraform.io/providers/hashicorp/aws/5.66.0/docs/resources/elasticache_parameter_group it clearly notes that `name` is required. 

You can also see in TF code https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/parameter_group.go#L62 that it does list it as required.

I am assuming the fail on the validation is occuring from a webhook but I am curious why we don't see the CRD pick up the required field on `name` but it does see it on `region`

### Relevant Error Output Snippet

```shell
* spec: Invalid value: "object": spec.forProvider.name is a required parameter
```
```


### Crossplane Version

1.16.0

### Provider Version

1.13.0

### Kubernetes Version

1.29

### Kubernetes Distribution

Kind, EKS

### Additional Info

_No response_
