### ISSUE TITLE
I can't configure `aws_appsync_domain_name` and `aws_appsync_domain_name_api_association` because it requires certificates with valid domains

### ISSUE THREAD

**Issue by turkenf** [crossplane-contrib/provider-upjet-aws#150]
### What happened?

When testing `aws_appsync_domain_name` I got the following error:

```
    message: 'apply failed: error creating Appsync Domain Name: BadRequestException:
      Certificate is invalid.: '
```
A valid domain is needed to validate the certificate. The final version of the example is below:

```
apiVersion: appsync.aws.upbound.io/v1beta1
kind: DomainName
metadata:
  annotations:
    crossplane.io/external-name: example-dns.upbound-providers.io
    meta.upbound.io/example-id: appsync/v1beta1/domainname
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    certificateArnSelector:
      matchLabels:
        testing.upbound.io/example-name: certificate
    region: us-east-1
---
apiVersion: acm.aws.upbound.io/v1beta1
kind: Certificate
metadata:
  name: example-dns
  labels:
    testing.upbound.io/example-name: certificate
spec:
  forProvider:
    region: us-east-1
    domainName: example-dns.upbound-providers.io
    tags:
      Environment: test
    validationMethod: DNS

```

### How can we reproduce it?

1. Cut resource from config/externalnamenottested.go
3. Paste it into config/externalname.go
4. Run `make generate` for CRD generation.
5. Copy `examples-generated` to `examples`
6. I added the resources it depends on the example and fix example
7. Run `make generate` 
8. Apply CRDs with `kubectl apply -f package/crds`
9. Run `make uptest UPTEST_EXAMPLE_LIST=examples/appsync/domainname.yaml`

### What environment did it happen in?

Local development
