### ISSUE TITLE
[Bug]: InvalidParameterValue: Invalid master password error on RDS Instance creation when passwordSecretRef is not provided with autoGeneratePassword

### ISSUE THREAD

**Issue by wmgroot** [crossplane-contrib/provider-upjet-aws#1520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

rds.aws.upbound.io/v1beta3 - Instance

### Resource MRs required to reproduce the bug
```
---
apiVersion: rds.aws.upbound.io/v1beta3
kind: Instance
metadata:
  name: my-db
spec:
  forProvider:
    allocatedStorage: 20
    allowMajorVersionUpgrade: false
    applyImmediately: true
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 30
    caCertIdentifier: rds-ca-rsa2048-g1
    dbName: db
    dbSubnetGroupName: my-subnetgroup
    deletionProtection: false
    engine: mysql
    engineVersion: 8.0.35
    instanceClass: db.t3.micro
    multiAz: false
    parameterGroupName: default.mysql8.0
    # required but not documented as such
    # passwordSecretRef:
    #   key: password
    #   name: password
    #   namespace: my-namespace
    region: us-east-2
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    username: user
  providerConfigRef:
    name: crossplane-aws-rds-config
  writeConnectionSecretToRef:
    name: db-connection
    namespace: my-namespace
```

### Steps to Reproduce

Apply the example RDS Instance resource, and describe it to view the error below.

### What happened?

The error given by the provider does not point the user to the actual problem that needs to be addressed, which is the lack of a provided `passwordSecretRef`. The documentation does not list this field as required when using `autoGeneratePassword: true`.

I believe the rds provider should be able to validate that `passwordSecretRef` is set when using `autoGeneratePassword: true` and provide the user with an error message making that dependency clear.

### Relevant Error Output Snippet

```shell
Warning  CannotCreateExternalResource  6s                 managed/rds.aws.upbound.io/v1beta2, kind=instance  async create failed: failed to create the resource: [{0 creating RDS DB Instance (terraform-202410101501311888000004bc): InvalidParameterValue: Invalid master password
           status code: 400, request id: 80173e01-0780-4728-9197-baec5e1b6618  []}]
```
```


### Crossplane Version

v1.16.0

### Provider Version

v1.14.0

### Kubernetes Version

1.30.4

### Kubernetes Distribution

EKS

### Additional Info

_No response_
