### ISSUE TITLE
[Bug]: Cloudfront InvalidArgument: The parameter name must be non-null

### ISSUE THREAD

**Issue by sterziev88** [crossplane-contrib/provider-upjet-aws#1527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

cloudfront.aws.upbound.io/v1beta1 - Distribution

### Resource MRs required to reproduce the bug

```
apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: Distribution
metadata:
  annotations: {}
  labels: {}
  name: test-cf
spec:
  deletionPolicy: Orphan
  forProvider:
    aliases:
      - test3
      - test2
    defaultCacheBehavior:
      - allowedMethods:
          - DELETE
          - GET
        cachePolicyId: CachingOptimized
        cachedMethods:
          - GET
          - HEAD
        viewerProtocolPolicy: redirect-to-https
    enabled: true
    origin:
      - domainName: test.test.s3.us-east-1.amazonaws.com
    region: eu-west-1
    restrictions:
      - geoRestriction:
          - restrictionType: none
    tags:
      crossplane-kind: distribution.cloudfront.aws.upbound.io
      crossplane-name: test-cf
      crossplane-providerconfig: test
    viewerCertificate:
      - cloudfrontDefaultCertificate: true
  initProvider: {}
  managementPolicies:
    - '*'
  providerConfigRef:
    name: test
```

### Steps to Reproduce

I am trying to create cloudfront with S3 static website as origin. 

### What happened?

When I deploy my manifest I receive an error: 
        create failed: async create failed: failed to create the resource: [{0
        creating CloudFront Distribution: operation error CloudFront:
        CreateDistributionWithTags, https response error StatusCode: 400,
        RequestID: c14c69dc-a864-4ddd-bdc5-f10af23813eb, InvalidArgument: The
        parameter name must be non-null.  []}]

I don't know which is that parameter name ......

### Relevant Error Output Snippet

```shell
create failed: async create failed: failed to create the resource: [{0
        creating CloudFront Distribution: operation error CloudFront:
        CreateDistributionWithTags, https response error StatusCode: 400,
        RequestID: c14c69dc-a864-4ddd-bdc5-f10af23813eb, InvalidArgument: The
        parameter name must be non-null.  []}]
```

### Crossplane Version

1.14.2

### Provider Version

1.15.0

### Kubernetes Version

1.30

### Kubernetes Distribution

EKS
