### ISSUE TITLE
[Bug]: Cannot create KMS Key Alias by using selectors

### ISSUE THREAD

**Issue by niralmehtasb1** [crossplane-contrib/provider-upjet-aws#1550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias

### Resource MRs required to reproduce the bug

key.kms.aws.upbound.io/v1beta1

### Steps to Reproduce

1. Create a MR `key.kms.aws.upbound.io/v1beta1`
2. Create a MR `Alias.kms.aws.upbound.io/v1beta1` and try to associate to the KMS Key created above using `spec.forProvider.targetKeyIdRef`

### What happened?

Ideally it should be able to lookup KMSKeyId and populate `Spec.ForProvider.TargetKeyID` and create the MR `Alias.kms.aws.upbound.io/v1beta1`

### Relevant Error Output Snippet

```shell
The Alias never gets created with an error message in the MR that says:

`message: 'cannot resolve references: mg.Spec.ForProvider.TargetKeyID: referenced
      field was empty (referenced resource may not yet be ready)'
    reason: ReconcileError
    status: "False"
`
```

### Crossplane Version

v1.17.2

### Provider Version

v1.14.0

### Kubernetes Version

v1.31.0

### Kubernetes Distribution

EKS

### Additional Info
(Probably same as https://github.com/crossplane-contrib/provider-upjet-aws/issues/1523)
_No response_

**Comment by turkenf** [comment]
Hi @niralmehtasb1,

Thank you, I can easily create resources with the following MRs:
```
apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/alias
  labels:
    testing.upbound.io/example-name: a
  name: a
spec:
  forProvider:
    region: us-west-1
    targetKeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: a
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/alias
  labels:
    testing.upbound.io/example-name: a
  name: a
spec:
  forProvider:
    region: us-west-1
``` 

Please make sure your resources are in the same region and the label and selector match. I am closing this issue for now; if you still have problems, you can reopen the issue by sharing your MRs.
