### ISSUE TITLE
[Bug]:  ssm.aws.upbound.io/Parameter/v1beta1 - unable to create a Parameter with Type: SecureString

### ISSUE THREAD

**Issue by emoby** [crossplane-contrib/provider-upjet-aws#1559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

provider-aws-ssm/v1.16.0/resources/ssm.aws.upbound.io/Parameter/v1beta1

### Resource MRs required to reproduce the bug

ssm-parameter-store-ss.yaml
```
apiVersion: ssm.aws.upbound.io/v1beta1
kind: Parameter
metadata:
  name: crossplane-system-ps-secure-string
  namespace: crossplane-system
  annotations:
    crossplane.io/parameter-name: /k8s/crossplane-system/ps-secure-string
spec:
  forProvider:
    region: us-east-1
    type: SecureString
  providerConfigReg:
    name: default
```

### Steps to Reproduce

```
k create -f ssm-parameter-store-ss.yaml
```

### What happened?

I'm trying to create a SecureString ssm parameter, and it fails with an api error Validation from AWS.  Suggestions on how to provide a placeholder for the create process?

### Relevant Error Output Snippet

```shell
message: 'create failed: async create failed: failed to create the resource: [{0
      creating SSM Parameter (crossplane-system-ps-secure-string): operation error SSM:
      PutParameter, https response error StatusCode: 400, RequestID: <redacted>,
      api error ValidationException: 1 validation error detected: Value at ''value''
      failed to satisfy constraint: Member must have length greater than or equal
      to 1  []}]'
    reason: ReconcileError
    status: "False"
    type: Synced
```
```


### Crossplane Version

1.18.0

### Provider Version

v1.16.0

### Kubernetes Version

Kubernetes Version:
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.1-eks

### Kubernetes Distribution

EKS

### Additional Info

_No response_

**Comment by emoby** [comment]
```
Kubernetes Version:
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.1-eks
```
Kubernetes Distribution
```
EKS
```

**Comment by turkenf** [comment]
Hi @emoby,

You can use the following YAML to create the resource:
```
apiVersion: ssm.aws.upbound.io/v1beta1
kind: Parameter
metadata:
  name: crossplane-system-ps-secure-string
  namespace: crossplane-system
  annotations:
    crossplane.io/parameter-name: /k8s/crossplane-system/ps-secure-string
spec:
  forProvider:
    region: us-east-1
    type: SecureString
    valueSecretRef:
      key: example-key
      name: parameter-secret
      namespace: upbound-system
  providerConfigReg:
    name: default
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: ssm/v1beta1/parameter
  labels:
    testing.upbound.io/example-name: foo
  name: parameter-secret
  namespace: upbound-system
type: Opaque
stringData:
  example-key: "Upbound!"
```
