### ISSUE TITLE
[Bug]: Elasticache ReplicationGroup not adjusting replica count 

### ISSUE THREAD

**Issue by KhasDenis** [crossplane-contrib/provider-upjet-aws#1563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* elasticache.aws.upbound.io/v1beta2 - ReplicationGroup

### Resource MRs required to reproduce the bug

```
apiVersion: elasticache.aws.upbound.io/v1beta2
kind: ReplicationGroup
metadata:
  name: elasticcache-dkh
spec:
  deletionPolicy: Orphan
  forProvider:
    applyImmediately: true
    atRestEncryptionEnabled: true
    authTokenSecretRef:
      key: password
      name: elasticcache-dkh-secret
      namespace: default
    authTokenUpdateStrategy: ROTATE
    autoGenerateAuthToken: false
    autoMinorVersionUpgrade: "true"
    automaticFailoverEnabled: false
    description: elasticcache-dkh- Replication Group
    engine: redis
    engineVersion: "7.0"
    ipDiscovery: ipv4
    maintenanceWindow: sun:23:00-mon:00:00
    multiAzEnabled: false
    networkType: ipv4
    nodeType: cache.m5.large
    numCacheClusters: 2
    parameterGroupName: elasticcache-dkh
    port: 6379
    region: eu-central-1
    securityGroupIds:
    - sg-05cb53f9b298ee781
    snapshotWindow: 02:30-03:30
    subnetGroupName: nebula-npg-eks-ec-sub-nprd
    transitEncryptionEnabled: true
    transitEncryptionMode: required
  initProvider:
    authTokenUpdateStrategy: ROTATE
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: elasticcache-dkh-output
    namespace: default
```

### Steps to Reproduce

- Apply manifest from above
- Wait till resource created
- Change numCacheClusters from 2 to 3

### What happened?

If I apply provided manifest elasticache redis cluster is created successfully with cluster mode disabled and two nodes primary and replica. But if now I edit ReplicationGroup changing numCacheClusters from 2 to 3 additional node comes to create/delete loop in AWS. ReplicationGroup stays SYNCED and READY in the cluster.

### Crossplane Version

1.16.0

### Provider Version

1.9.0

### Kubernetes Version

1.30

### Kubernetes Distribution

EKS
