### ISSUE TITLE
[Bug]: Route53 Zone external name not being set after creation

### ISSUE THREAD

**Issue by awprice** [crossplane-contrib/provider-upjet-aws#1567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* route53.aws.upbound.io/v1beta1 - Zone

### Resource MRs required to reproduce the bug

```
apiVersion: route53.aws.upbound.io/v1beta1
kind: Zone
metadata:
  name: example
spec:
  forProvider:
    name: mycompany.test
    region: us-west-1
```

### Steps to Reproduce

- Apply MR (Zone) to cluster
- Hosted Zone is created in AWS Route53 by provider
- MR becomes synced: true and ready: true

### What happened?

 - External name annotation is never added to MR
 - Crossplane will eventually create duplicate hosted zones if the provider is restarted

### Crossplane Version

v1.16.1

### Provider Version

v1.17.0

### Kubernetes Version

v1.29.8

### Kubernetes Distribution

EKS

### Additional Info

This issue is similar to https://github.com/crossplane-contrib/provider-upjet-aws/issues/1482

**Comment by turkenf** [comment]
Hi @awprice,

Thank you for bringing up this issue. I could not reproduce the issue with the provided information. 
```
apiVersion: route53.aws.upbound.io/v1beta1
kind: Zone
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-11-30T10:53:06Z"
    crossplane.io/external-create-succeeded: "2024-11-30T10:53:06Z"
    crossplane.io/external-name: Z04762493SW6AYLIXTUYH
    ...
```

Have you made any changes to resource management policies? This is a known issue if you disable late initialize: https://github.com/crossplane/crossplane/issues/5918
