### ISSUE TITLE
[Bug]: writeConnectionSecretToRef on ServerlessCache Does Not Write Data to Secret

### ISSUE THREAD

**Issue by vargaadam** [crossplane-contrib/provider-upjet-aws#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

elasticache.aws.upbound.io/v1beta1 - ServerlessCache

### Resource MRs required to reproduce the bug

```
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ServerlessCache
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1beta1/serverlesscache
  labels:
    testing.upbound.io/example-name: example
  name: example-random
spec:
  forProvider:
    cacheUsageLimits:
      - dataStorage:
          - maximum: 10
            unit: GB
        ecpuPerSecond:
          - maximum: 5000
    description: Test Server
    engine: memcached
    majorEngineVersion: "1.6"
    region: us-west-1
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    writeConnectionSecretToRef:
      name: example-random
      namespace: default
```

### Steps to Reproduce

- Apply the resource using kubectl apply -f serverless-cache.yaml.
- Check the contents of the referenced secret (example-random).

### What happened?

It appears that the writeConnectionSecretToRef functionality in the ServerlessCache resource is not functioning as expected. When specifying a secret reference in writeConnectionSecretToRef, the secret is created, but it remains empty. This behavior is inconsistent with the expected functionality, where connection details (e.g., endpoint, username, password) should be written to the specified secret.

### Crossplane Version

v1.17.0

### Provider Version

v1.17.0

### Kubernetes Version

v1.29.0

### Kubernetes Distribution

1.31

### Additional Info

The issue may be connected to this configuration:
[config.go#L178](https://github.com/crossplane-contrib/provider-upjet-aws/blob/cc7b958eb41f4466d707cedf8862d8369e15e43c/config/elasticache/config.go#L178).
