### ISSUE TITLE
Add support for EKS Auto Mode

### ISSUE THREAD

**Issue by moonorb** [crossplane-contrib/provider-upjet-aws#1587]
### What problem are you facing?
AWS released EKS Auto mode functionality

### What could help solve your problem?
Adding Auto mode support to "provider-aws-eks" would be great. Thank you.

**Reference doc:**
+ https://aws.amazon.com/eks/auto-mode/

**Reference PR for TF:** 
+ https://github.com/hashicorp/terraform-provider-aws/pull/40370

**Comment by mergenci** [comment]
Thanks for the references @moonorb 🙏 Now that the upstream feature has been released with v5.79.0, it should be available with the next Terraform provider version bump. We don't have a fixed schedule, but we aim to catch up with minor version Terraform provider releases within a month or two.

**Comment by Lock128** [comment]
Any chance to pull this into the first release of 2025? ;)

**Comment by kingdonb** [comment]
I see that https://github.com/crossplane-contrib/provider-upjet-aws/pull/1629 was merged and the latest release of upjet-aws (v1.19.0) has Terraform v5.82.2, and the API docs now mention EKS Auto Mode.

Any chance someone has tested this and can say if it works? (I'm assuming it works, and reporting in here because it looks like this issue could be closed... but I haven't tested it yet, would it make sense to document how it works before this is closed?)

I'm looking through the Terraform docs - there's an example here:

https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v20.33.1/examples/eks-auto-mode
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/examples/eks-auto-mode

I am new at Crossplane, but I've been tasked with updating my team's EKSClaim to support EKS Auto Mode. I will do my best to get this implemented based on the docs available. I understand that upjet providers wrap terraform providers, so these docs should be of some help (but it would be awesome if someone who knows Crossplane a little bit more than I do, or someone who has been waiting for this feature to land, could chime in and let us know how it worked for you...)

**Comment by Lock128** [comment]
I've been able to test this one and it works as expected! ;)

In my composition I put this config in my claim for

```
          apiVersion: eks.aws.upbound.io/v1beta1
          kind: Cluster
```
(using go templating)
```
{{ if $spec.automode }}
              computeConfig:
                - enabled: true
                  nodePools:
                    - system
                    - general-purpose 
                  nodeRoleArn: "arn:aws:iam::{{ $spec.awsaccountId }}:role/{{ $spec.clusterName }}-nodeinstancerole"
              storageConfig:
                - blockStorage:
                  - enabled: true
              kubernetesNetworkConfig:
                - elasticLoadBalancing:
                  - enabled: true
                  ipFamily: ipv6
              bootstrapSelfManagedAddons: false
{{ end }}
```
