### ISSUE TITLE
[Bug]: VPCEndpoint needs to suppress LateInitialziation

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane-contrib/provider-upjet-aws#1596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* apiVersion: ec2.aws.upbound.io/v1beta2 - VPCEndpoint

### Resource MRs required to reproduce the bug

```yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  labels:
    testing.upbound.io/example-name: vpc1
  name: vpc1
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-west-2
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCEndpoint
metadata:
  labels:
    testing.upbound.io/example-name: ec2
  name: borrelli-ec2
spec:
  forProvider:
    region: us-west-2
    serviceName: com.amazonaws.us-west-2.ec2
    vpcEndpointType: Interface
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc1
  managementPolicies:
  - Observe
  - Create
  - Update
  - Delete
  # initProvider:
  #   subnetConfiguration:
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCEndpointSubnetAssociation
metadata:
  labels:
    testing.upbound.io/example-name: sn_ec2
  name: sn-ec2
spec:
  forProvider:
    region: us-west-2
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet1
    vpcEndpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ec2
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCEndpointSubnetAssociation
metadata:
  labels:
    testing.upbound.io/example-name: sn_ec2
  name: sn-ec2-2
spec:
  forProvider:
    region: us-west-2
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet2
    vpcEndpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ec2
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCEndpointSubnetAssociation
metadata:
  labels:
    testing.upbound.io/example-name: sn_ec2
  name: sn-ec2-3
spec:
  forProvider:
    region: us-west-2
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet3
    vpcEndpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ec2
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    testing.upbound.io/example-name: subnet1
  name: subnet1
spec:
  forProvider:
    cidrBlock: 10.0.1.0/24
    region: us-west-2
    availabilityZone: us-west-2a
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    testing.upbound.io/example-name: subnet2
  name: subnet2
spec:
  forProvider:
    cidrBlock: 10.0.2.0/24
    region: us-west-2
    availabilityZone: us-west-2b
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    testing.upbound.io/example-name: subnet3
  name: subnet3
spec:
  forProvider:
    cidrBlock: 10.0.3.0/24
    region: us-west-2
    availabilityZone: us-west-2c
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc1
```

### Steps to Reproduce

- Apply manifest above
- `kubectl get vpcendpoint.ec2.aws.upbound.io/borrelli-ec2 -o yaml`, note spec is populated with Subnets from the attachments

### What happened?

When `VPCEndpointSubnetAssociation` are defined, the `VPCEndpoint` will lateInitialize the spec with the fields. Since it takes several minutes for `VPCEndpointSubnetAssociation` to become ready, this can lead to a situation where the `VPCEndpoint` tries to update itself, which can trigger AWS API errors. 

A workaround is to use managementPolicies:

```yaml
  managementPolicies:
  - Observe
  - Create
  - Update
  - Delete
``` 

### Crossplane Version

1.17.3

### Provider Version

1.17.0

### Kubernetes Distribution

Upbound
