### ISSUE TITLE
[Bug]: SSA doesn't delete the fields that are part of another field that goes through version conversion

### ISSUE THREAD

**Issue by r-nasiri** [crossplane-contrib/provider-upjet-aws#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

all resources that have version conversion

### Resource MRs required to reproduce the bug

```
apiVersion: ec2.aws.upbound.io/v1beta2
kind: LaunchTemplate
metadata:
  name: ssa-test1
spec:
  forProvider:
    imageId: ami-074be47313f84fa38
    instanceInitiatedShutdownBehavior: terminate
    instanceType: t3.micro
    name: example
    region: us-west-2
    instanceMarketOptions:
      marketType: spot
      spotOptions:
        maxPrice: "0.06"
    tags:
      example: "true"
  managementPolicies:
  - Create
  - Update
  - Delete
  - Observe
  providerConfigRef:
    name: aws-provider-config         
```

### Steps to Reproduce

- Create a LaunchTemplate using v1beta2 version as provided in the example using SSA.
- Make sure the resource is created
- Remove `spotOptions` from manifest and update using SSA.
- MR should not have the `spotOptions` anymore.

### What happened?

when removing a field that was converted from array to object type in new versions, those fields are not removed when using server side apply. If you change the manifest to v1beta1 version(Storage version), it works as expected.

### Crossplane Version

1.16.0

### Provider Version

1.18.2

### Kubernetes Version

1.29

### Kubernetes Distribution

EKS
