### ISSUE TITLE
[Bug]: instanceRefresh is added back to AutoscalingGroup after removal

### ISSUE THREAD

**Issue by r-nasiri** [crossplane-contrib/provider-upjet-aws#1631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* autoscaling.aws.upbound.io/v1beta3 - AutoscalingGroup

### Resource MRs required to reproduce the bug

```
apiVersion: autoscaling.aws.upbound.io/v1beta3
kind: AutoscalingGroup
metadata:
  name: test-asg
spec:
  forProvider:
    desiredCapacity: 0
    launchTemplate:
      id: lt-0ecc4c9aa799d7176
      version: "5"
    maxSize: 1
    minSize: 0
    instanceRefresh:
      preferences:
        instanceWarmup: "300"
        maxHealthyPercentage: 110
        minHealthyPercentage: 90
      strategy: Rolling
    region: us-west-2
    vpcZoneIdentifier:
    - subnet-04f72f198556cbb2c
  managementPolicies:
  - Create
  - Update
  - Delete
  - Observe
  - LateInitialize
  providerConfigRef:
    name: aws-provider-config
```

### Steps to Reproduce

- Create a AutoscalingGroup using the provided manifest. It should include `instanceRefresh` field.
- Make sure the AutoscalingGroup is created and `instanceRefresh` shows up in `status.atProvider`
- Remove `instanceRefresh` from the manifest and apply it again.
- `instanceRefresh`  is not removed and has previous values.

### What happened?

When the `LateInitialize` is enabled, removing `instanceRefresh` doesn't update the ASG and gets added back because this is an async operation and spec.atProvider doesn't get updated right away and gets added back by LateInitialize process. I think this field should be added to LateInitialize IgnoreFields.

### Crossplane Version

1.16.0

### Provider Version

1.18.2

### Kubernetes Version

1.29

### Kubernetes Distribution

EKS
