### ISSUE TITLE
[Bug]: rds.aws.upbound.io/v1beta3 Instance not updating

### ISSUE THREAD

**Issue by sidpalas** [crossplane-contrib/provider-upjet-aws#1652]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

rds.aws.upbound.io/v1beta3 - Instance

### Resource MRs required to reproduce the bug

```
apiVersion: rds.aws.upbound.io/v1beta3
kind: Instance
metadata:
  name: sid-test
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 30
    autoMinorVersionUpgrade: false
    availabilityZone: us-gov-west-1c
    backupRetentionPeriod: 7
    backupTarget: region
    backupWindow: 09:57-10:27
    caCertIdentifier: rds-ca-rsa4096-g1
    copyTagsToSnapshot: true
    dbName: name
    dbSubnetGroupName: MY_SUBNET
    deleteAutomatedBackups: false
    deletionProtection: true
    engine: postgres
    engineLifecycleSupport: open-source-rds-extended-support
    engineVersion: "16.6"
    iamDatabaseAuthenticationEnabled: false
    identifier: sid-test
    instanceClass: db.m5.xlarge
    kmsKeyId: MY_KEY_ARN
    licenseModel: postgresql-license
    maintenanceWindow: sun:13:00-sun:13:30
    maxAllocatedStorage: 1000
    monitoringInterval: 5
    monitoringRoleArn: MY_ROLE_ARN
    multiAz: false
    networkType: IPV4
    optionGroupName: default:postgres-16
    parameterGroupName: default.postgres16
    passwordSecretRef:
      key: password
      name: MY_SECRET
      namespace: MY_SECRET_NAMESPACE
    performanceInsightsEnabled: true
    performanceInsightsKmsKeyId: MY_KMS_KEY_ARN
    performanceInsightsRetentionPeriod: 7
    port: 5432
    publiclyAccessible: false
    region: us-gov-west-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp3
    username: postgres
    vpcSecurityGroupIds:
      - MY_SECURITY_GROUP_ID
  managementPolicies:
    - "*"
  providerConfigRef:
    name: MY_PROVIDER_CONFIG
```

### Steps to Reproduce

1. Create an MR for the Instance
2. Make an update to the MR spec (e.g. `spec.forProvider.instanceClass`)
 

### What happened?

I am able to successfully create an RDS instance using the following configuration shared in the MR section of this Issue.

It creates successfully and shows as SYNCED + READY
```
❯ k get instances.rds.aws.upbound.io sid-test
NAME       SYNCED   READY   EXTERNAL-NAME                   AGE
sid-test   True     True    db-Q3JQTFXX35XU63OXCYCOTINCTM   107m
```

After creation, modifying the spec (e.g. changing `spec.forProvider.instanceClass` has no affect:
```
❯ k get instances.rds.aws.upbound.io sid-test -o yaml | yq '.spec.forProvider.instanceClass' && k get instances.rds.aws.upbound.io sid-test -o yaml | yq '.status.atProvider.instanceClass'
db.m5.xlarge
db.m5.large
```

I also tested modifying the instance class via the AWS console and `.status.atProvider.instanceClass` was successfully updated to indicate that change.

This started occurring after upgrading my version of the provider from `v0.47.1` -> `v1.19.0` (I added the .spec.forProvider.identifier field to all existing Instance resources). This behavior exists for Instances created prior to that upgrade and new Instances.

### Relevant Error Output Snippet

```shell
There is no error, the resources appears to be happy/healthy but it never applies the update.

Describing the resource shows:

  Normal  UpdatedExternalResource  3m46s (x61 over 95m)  managed/rds.aws.upbound.io/v1beta2, kind=instance  Successfully requested update of external resource
```

### Crossplane Version

1.17.3

### Provider Version

1.19.0

### Kubernetes Version

v1.30.8-eks-2d5f260

### Kubernetes Distribution

EKS
