### ISSUE TITLE
[Bug]:  No endpoints available for service "upbound-provider-aws-s3"

### ISSUE THREAD

**Issue by reiinoldo** [crossplane-contrib/provider-upjet-aws#1656]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

* s3.aws.upbound.io/v1beta1

### Resource MRs required to reproduce the bug

```yaml
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: mybucket
  namespace: dev-reporting
spec:
  forProvider:
    region: us-east-1
```

### Steps to Reproduce

`kubectl apply -f .\base\s3-bucket.yaml`
output: bucket.s3.aws.upbound.io/mybucket created
`kubectl describe Bucket`
output: Error from server: conversion webhook for s3.aws.upbound.io/v1beta1, Kind=Bucket failed: Post "https://upbound-provider-aws-s3.crossplane-system.svc:9443/convert?timeout=30s": no endpoints available for service "upbound-provider-aws-s3"

### What happened?

When trying to create a S3 Bucket seems that there an outstage from the upbound-provider-aws-s3 endpoints

### Relevant Error Output Snippet

```shell
 Error from server: conversion webhook for s3.aws.upbound.io/v1beta1, Kind=Bucket failed: Post "https://upbound-provider-aws-s3.crossplane-system.svc:9443/convert?timeout=30s": no endpoints available for service "upbound-provider-aws-s3"
```

### Crossplane Version

v1.17.2

### Provider Version

v1.17.0

### Kubernetes Version

v1.31.1
