### ISSUE TITLE
[Bug]: MQUser Infinite Update Loop and Broker stuck in "Pending Modifications"

### ISSUE THREAD

**Issue by anagarlau** [crossplane-contrib/provider-upjet-aws#1657]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

* mq.aws.upbound.io/v1alpha1/users 

### Resource MRs required to reproduce the bug
```
---
apiVersion: mq.aws.upbound.io/v1beta2
kind: Broker
metadata:
  annotations:
    meta.upbound.io/example-id: mq/v1beta2/broker
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applyImmediately: true
    brokerName: example-broker
    configuration:
      id: # ....
      revision: # ...
    engineType: ActiveMQ
    engineVersion: 5.17.6
    hostInstanceType: mq.t2.micro
    region: eu-central-1
    securityGroupRefs:
    - name: sg-test
  providerConfigRef:
    name: default
  initProvider: 
    user:
    - passwordSecretRef:
        key: password
        name: mq-admin-secret
        namespace: default
      username: admin
---
apiVersion: mq.aws.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: mq/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example
  name: mquser1
spec:
  providerConfigRef:
    name: default
  forProvider:
    brokerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    consoleAccess: false
    passwordSecretRef:
      key: password
      name: mquser1
      namespace: default
    username: mquser1
    groups:
      - users
      - dev
    region: eu-central-1
---
apiVersion: mq.aws.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: mq/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example
  name: mquser2
spec:
  providerConfigRef:
    name: default
  forProvider:
    brokerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    consoleAccess: false
    passwordSecretRef:
      key: password
      name: mquser2
      namespace: default
    username: mquser2
    groups:
      - users
      - dev
    region: eu-central-1
---
apiVersion: mq.aws.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: mq/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example
  name: mquser3
spec:
  providerConfigRef:
    name: default
  forProvider:
    brokerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    consoleAccess: false
    passwordSecretRef:
      key: password
      name: mquser3
      namespace: default
    username: mquser3
    groups:
      - users
      - dev
    region: eu-central-1
```

### Steps to Reproduce

- create an ActiveMQ broker
- create at least 2 MQUsers in quick succession (e.g., apply a file containing 3 users).
-  **ensure that users are assigned to the same groups**  

### What happened?

- Expected: As is typically the case with configurations or users, rebooting the broker should stop the update loop.
- Actual: Instead, the update loop for users continues, and the broker continuously shows "Pending modifications" for users in the AWS Console. Multiple reboots yield the same result.
- This behavior sometimes stops when at least one of the two groups is removed from an MQUser manifest, or when the users do not share more than one group. However, in most cases, assigning users to separate groups is the safest way to stop the loop.
- Probable cause: This is most likely a race condition, as it seems that the group assignments are being overwritten during updates.

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

v1.17

### Provider Version

v1.17.0, v1.20.0

### Kubernetes Version

v1.30.0

### Kubernetes Distribution

EKS
