### ISSUE TITLE
[Bug]: Unable to update Route, Multiple Targets in AWS Route Object Spec causing unstable Route updates

### ISSUE THREAD

**Issue by kirank-7** [crossplane-contrib/provider-upjet-aws#1679]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

ec2.aws.upbound.io/v1beta2 - Route

### Resource MRs required to reproduce the bug

1) 
```yaml
apiVersion: ec2.aws.upbound.io/v1beta2
kind: Route
metadata:
  name: my-customroute-1
  namespace: default
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-east-1
    destinationCidrBlock: 8.8.8.8/32
    gatewayId: igw-0a1b2c3d4e5f67890
    routeTableId: rtb-1234567890abcdef0
  providerConfigRef:
    name: default
```

2)
```yaml
apiVersion: ec2.aws.upbound.io/v1beta2
kind: Route
metadata:
  name: my-customroute-1
  namespace: default
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-east-1
    destinationCidrBlock: 8.8.8.8/32
    transitGatewayId: tgw-1a2b3c4d5e6f78901
    routeTableId: rtb-1234567890abcdef0
  providerConfigRef:
    name: default
```

3)
```yaml
apiVersion: ec2.aws.upbound.io/v1beta2
kind: Route
metadata:
  name: my-customroute-1
  namespace: default
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-east-1
    destinationCidrBlock: 8.8.8.8/32
    gatewayId: 
    transitGatewayId: tgw-1a2b3c4d5e6f78901
    routeTableId: rtb-1234567890abcdef0
  providerConfigRef:
    name: default
```

4)
```yaml
apiVersion: ec2.aws.upbound.io/v1beta2
kind: Route
metadata:
  name: my-customroute-1
  namespace: default
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-east-1
    destinationCidrBlock: 8.8.8.8/32
    gatewayId: ""
    transitGatewayId: tgw-1a2b3c4d5e6f78901
    routeTableId: rtb-1234567890abcdef0
  providerConfigRef:
    name: default
```

### Steps to Reproduce

1. Create Route with IGW Target
2. Update Route with TGW Target and no IGW Target 
3. Update Route with TGW Target and IGW Target set to nothing
4. Set IGW to Empty String ""

### What happened?

Expected Behavior:
 
- When updating a route target (e.g., from IGW to TGW), only one target should be allowed in the spec of the Route object.

- The provider should correctly update the route in AWS without having multiple targets in the spec.

- If an existing route is to be updated, it should reflect the intended target and not throw errors or continuously apply updates with both targets.
 
Actual Behavior:
 
- In steps 2 and 3, the spec contains two targets (gatewayId and transitGatewayId). This leads to Crossplane continuously updating the route between the two targets in AWS, causing instability.

- In step 4, the route configuration with an empty gatewayId results in an invalid spec value error.

Step 3 throws errors when trying to apply the route.

 

### Relevant Error Output Snippet

```shell
cannot patch the managed resource via server-side apply: Route.ec2.aws.upbound.io "my-customroute-1" is invalid: spec.forProvider.gatewayId: Invalid value: "null": spec.forProvider.gatewayId in body must be of type string: "null"
```

### Crossplane Version

v1.18.2

### Provider Version

v1.19.0

### Additional Info

To work around this issue, the only solution currently is to adopt the existing route into the cluster, delete it, and recreate the route with the desired target. However, if this functionality were working properly, the workflow would be much simpler, as we could update the route without needing to delete and recreate it.
