### ISSUE TITLE
[Bug]: unmarshal error during upgrade from v1.18.3 to v1.19.0 with same scheme version for ReplicationGroup.elasticache.aws.upbound.io/v1beta2

### ISSUE THREAD

**Issue by ilyashzerban** [crossplane-contrib/provider-upjet-aws#1682]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

elasticache.aws.upbound.io/v1beta2 - ReplicationGroup

### Resource MRs required to reproduce the bug

```
apiVersion: elasticache.aws.upbound.io/v1beta2
kind: ReplicationGroup
metadata:
  name: tagging-store-cache
spec:
  forProvider:
    description: ***
    engine: redis
    nodeType: cache.r7g.large
    numCacheClusters: 3
    port: 6379
    region: ***
    multiAzEnabled: true
    automaticFailoverEnabled: true
    subnetGroupName: ***
    transitEncryptionEnabled: true
    securityGroupIdRefs:
      - name: ***

```

### Steps to Reproduce

apply the above example at version v1.18.3 and upgrade the provider to v1.19.0. 

### What happened?

The AWS Elastic Provider Controller fails to unmarshal the `boolean` type to `string` due to schema changes in v1.19.0. 
Additionally, these fields are not explicitly mentioned in the manifest, causing unmarshaling failures from status fields. As a result, upgrading the provider requires deleting and reapplying the replication group CRD and resource, potentially leading to resource failures during GVK upgrades.

### Relevant Error Output Snippet

```shell
W0210 11:37:06.814431       1 reflector.go:539] k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: failed to list *v1beta2.ReplicationGroup: json: cannot unmarshal bool into Go struct field ReplicationGroupObservation.items.status.atProvider.atRestEncryptionEnabled of type string
```

### Crossplane Version

v1.18.2

### Provider Version

v1.19.0

### Kubernetes Version

v1.30.3

### Kubernetes Distribution

EKS

### Additional Info

A breaking change in the schema, such as altering the type of a field without updating the scheme version, can lead to failures during upgrades. I hope next time, you can ensure backward compatibility by maintaining the existing scheme and providing a clear migration path to a new version if necessary.
