### ISSUE TITLE
[Bug]: Reconciliation failing if external system adds tags to the resource

### ISSUE THREAD

**Issue by karloscarrijozup** [crossplane-contrib/provider-upjet-aws#1709]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

eks.aws.upbound.io/v1beta1 - Cluster

### Resource MRs required to reproduce the bug

```yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
spec:
  managementPolicies: ["Observe", "Create", "Update", "Delete"]
  forProvider:
    accessConfig:
      - authenticationMode: API_AND_CONFIG_MAP
        bootstrapClusterCreatorAdminPermissions: false
    bootstrapSelfManagedAddons: true
    enabledClusterLogTypes:
      - api
      - audit
      - authenticator
    encryptionConfig:
      - provider: []
        resources:
          - secrets
    kubernetesNetworkConfig:
      - ipFamily: ipv4
        serviceIpv4Cidr: 172.20.0.0/16
    upgradePolicy:
      - supportType: EXTENDED
    vpcConfig:
      - subnetIds: []
        endpointPrivateAccess: true
  initProvider:
    tags:
      key: value
```

### Steps to Reproduce

- Apply the resource
- Default tags are added, and also the initProvider tags
- External system adds additional tags
- Reconciliation error

### What happened?

Hello everyone,

I've been struggling with this error for quite some time and have tried various solutions, but nothing seems to work. I have an external system (custodian) that automatically adds a couple of tags to every EKS cluster created in our AWS accounts. Unfortunately, this causes the Crossplane reconciliation loop to fail with a deserialization error.

To address this, I tried adding tags in initProvider and removing the LateInitialization from the managementPolicies. However, this approach doesn't work because the Upbound provider still adds a few default tags in forProvider.tags (e.g., crossplane-providerconfig, crossplane-kind, and crossplane-name). As a result, even if I set my own tags to be ignored after creation, the default tags still cause conflicts.

I understand that there is an ongoing discussion about this issue (#1141 ), which proposes an option to disable these default tags. In theory, this could resolve the problem. However, after searching through Crossplane's issues, discussions, and PRs, I found that the recommended solution is what I have already tried—using initProvider.

If anyone has encountered a similar issue or has any suggestions, I would greatly appreciate your help. Thank you!

### Relevant Error Output Snippet

```shell
Warning  CannotUpdateExternalResource  61s (x2589 over 43h)  managed/eks.aws.upbound.io/v1beta1, kind=cluster  (combined from similar events): async update failed: failed to update the resource: [{0 updating tags for EKS (Elastic Kubernetes) Cluster (arn:aws:eks:us-east-1:xxxxxxxxxxx:cluster/stk-tenant-cloud-dev): untagging resource (arn:aws:eks:us-east-1:xxxxxxxxxxx:cluster/stk-tenant-cloud-dev): operation error EKS: UntagResource, https response error StatusCode: 403, RequestID: 219822a8-05ac-4830-babd-e116926e774b, deserialization failed, failed to decode response body, invalid character '\n' in string literal  ]}]
```

### Crossplane Version

1.18.2

### Provider Version

1.19.0
