### ISSUE TITLE
Cognito UserPool resource missing field userPoolTier

### ISSUE THREAD

**Issue by davad** [crossplane-contrib/provider-upjet-aws#1713]
Setting the 'userPoolTier' gives the following error:
`strict decoding error: unknown field "spec.forProvider.userPoolTier"`
 
This affects:
* cognitoidp.aws.upbound.io/v1beta2 - UserPool

Example resource:
```yaml
apiVersion: cognitoidp.aws.upbound.io/v1beta2
kind: UserPool
metadata:
  annotations:
    meta.upbound.io/example-id: cognitoidp/v1beta1/useringroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
    region: us-east-1
    userPoolTier: LITE
```

### Background

I'm not sure if this counts as a bug, feature request, or resource request. AWS added this field to their API within [the last couple of months](https://aws.amazon.com/about-aws/whats-new/2024/11/new-feature-tiers-essentials-plus-amazon-cognito/).

Cognito user pools are now tierd based on the features (and cost) you want to access. The original feature set is in the 'Lite' plan. New features are in 'Essential' and 'Plus'. By default, new user pools are created with the 'Essential' plan.

I'm not sure when the AWS API was updated, or when they started defaulting new User Pools to the 'Essential' plan. But I see that the Terraform provider added support for the field about two months ago (v5.83.0).
