### ISSUE TITLE
[Bug]: KMS Key does not get external-name set unless LateInitialize is set - recreated onevery restart

### ISSUE THREAD

**Issue by chlunde** [crossplane-contrib/provider-upjet-aws#1715]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

* keys.kms.aws.upbound.io - maybe more

without setting LateInitialize the external-name annotation is not set. This in turn means the resource is recreated on every restart.

### Resource MRs required to reproduce the bug

```yaml
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  name: with-lateinit
spec:
  forProvider:
    deletionWindowInDays: 30
    description: 'foo'
    enableKeyRotation: true
    multiRegion: false
    region: eu-north-1
    rotationPeriodInDays: 365
    tags:
      foo: bar
  initProvider: {}
  managementPolicies:
  - Observe
  - Update
  - Create
  - LateInitialize
  providerConfigRef:
    name: default
```

```yaml
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  name: without-lateinit
spec:
  forProvider:
    deletionWindowInDays: 30
    description: 'foo'
    enableKeyRotation: true
    multiRegion: false
    region: eu-north-1
    rotationPeriodInDays: 365
    tags:
      foo: bar
  initProvider: {}
  managementPolicies:
  - Observe
  - Update
  - Create
  providerConfigRef:
    name: default
```

### Steps to Reproduce

```
k create -f keys.yaml

k get keys.kms.aws.upbound.io
NAME                          SYNCED   READY   EXTERNAL-NAME                          AGE
with-lateinit                 True     True    f60c847b-d91e-40f2-a8a2-41904f8ac21e   11s
without-lateinit              True     True                                           11s

k get keys.kms.aws.upbound.io without-lateinit -o json | jq .status.atProvider.id
"1234"


k delete po -n crossplane-system -l pkg.crossplane.io/provider=provider-aws-kms
pod "upbound-provider-aws-kms-f20ad3237da8-779f8665c5-sbsrq" deleted


k get keys.kms.aws.upbound.io without-lateinit -o json | jq .status.atProvider.id
"4567"
```

### What happened?

external-name is not set and we discovered a lot of KMS keys when the provider ran in a dev environment on spot nodes

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

1.18.2

### Provider Version

1.20.1

### Kubernetes Version

v1.31.5

### Kubernetes Distribution

EKS

### Additional Info

```
upbound-provider-aws-kms-f20ad3237da8-779f8665c5-fl96m package-runtime 2025-03-04T14:55:36Z	DEBUG	provider-aws	Successfully requested creation of external resource	{"controller": "managed/kms.aws.upbound.io/v1beta1, kind=key", "request": {"name":"without-lateinit"}, "uid": "2e52f289-2230-4b25-b979-acef2595e82f", "version": "2018464295", "external-name": "", "external-name": ""}

upbound-provider-aws-kms-f20ad3237da8-779f8665c5-fl96m package-runtime 2025-03-04T14:55:36Z	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/kms.aws.upbound.io/v1beta1, kind=key", "request": {"name":"without-lateinit"}, "uid": "2e52f289-2230-4b25-b979-acef2595e82f", "version": "2018472865", "external-name": "", "requeue-after": "2025-03-04T15:00:24Z"}

upbound-provider-aws-kms-f20ad3237da8-779f8665c5-fl96m package-runtime 2025-03-04T14:55:37Z	DEBUG	provider-aws	ongoing async operation	{"uid": "2e52f289-2230-4b25-b979-acef2595e82f", "name": "without-lateinit", "gvk": "kms.aws.upbound.io/v1beta1, Kind=Key", "opType": "create"}
upbound-provider-aws-kms-f20ad3237da8-779f8665c5-fl96m package-runtime 2025-03-04T14:55:37Z	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/kms.aws.upbound.io/v1beta1, kind=key", "request": {"name":"without-lateinit"}, "uid": "2e52f289-2230-4b25-b979-acef2595e82f", "version": "2018472865", "external-name": "", "requeue-after": "2025-03-04T15:00:31Z"}
upbound-provider-aws-kms-f20ad3237da8-779f8665c5-fl96m package-runtime 2025-03-04T14:55:44Z	DEBUG	provider-aws	Async create ended.	{"trackerUID": "2e52f289-2230-4b25-b979-acef2595e82f", "resourceName": "without-lateinit", "gvk": "kms.aws.upbound.io/v1beta1, Kind=Key", "error": null, "tfID": "3175c5da-ee60-4c15-99e1-3fdabb2f5c95"}
upbound-provider-aws-kms-f20ad3237da8-779f8665c5-fl96m package-runtime 2025-03-04T14:55:44Z	DEBUG	provider-aws	Reconcile request has been requeued.	{"gvk": "kms.aws.upbound.io/v1beta1, Kind=Key", "name": "without-lateinit", "rateLimiterName": "", "when": "0s"}
```
