### ISSUE TITLE
[Bug]: Create DomainPolicy with Domain referenced with matchControllerRef fails

### ISSUE THREAD

**Issue by nashtapu-tibco** [crossplane-contrib/provider-upjet-aws#1716]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

DomainPolicy.opensearch.aws.upbound.io/v1beta1
Domain.opensearch.aws.upbound.io/v1beta2
are part of same composite

### Resource MRs required to reproduce the bug

Domain.opensearch.aws.upbound.io/v1beta1 yaml 

```
  apiVersion: opensearch.aws.upbound.io/v1beta2
  kind: Domain
  metadata:
    annotations:
    name: domain1
  spec:
    deletionPolicy: Delete
    forProvider:
      advancedSecurityOptions:
        enabled: true
        internalUserDatabaseEnabled: true
        masterUserOptions:
          masterUserName: admin
          masterUserPasswordSecretRef:
            key: password
            name: secret-name
            namespace: crossplane-system
      clusterConfig:
        dedicatedMasterEnabled: false
        instanceCount: 2
        instanceType: t3.medium.search
      domainEndpointOptions:
        enforceHttps: true
      domainName: domain1
      ebsOptions:
        ebsEnabled: true
        volumeSize: 10
        volumeType: gp2
      encryptAtRest:
        enabled: true
      ipAddressType: ipv4
      nodeToNodeEncryption:
        enabled: true
      offPeakWindowOptions:
        enabled: true
        offPeakWindow:
          windowStartTime:
            hours: 6
      region: us-west-2
      snapshotOptions:
        automatedSnapshotStartHour: 0
      softwareUpdateOptions: {}
```

DomainPolicy.opensearch.aws.upbound.io/v1beta1

```
  apiVersion: opensearch.aws.upbound.io/v1beta1
  kind: DomainPolicy
  metadata:
    name: domainPolicy1
  spec:
    deletionPolicy: Delete
    forProvider:
      accessPolicies: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": [
                  "*"
                ]
              },
              "Action": "es:*",
              "Resource": "arn:aws:es:us-west-2:{account}:domain/domain1/*"
            }
          ]
        }
      domainName: domain1
      domainNameRef:
        name: domain1
      domainNameSelector:
        matchControllerRef: true
```

### Steps to Reproduce

Deploy the domain and domainpolicy above in the same composite.

### What happened?

Domain gets created successfully but the domainPolicy fails to create.

### Relevant Error Output Snippet

```shell
message: 'async create failed: failed to create the resource: [{0 updating OpenSearch
        Domain Policy (): operation error OpenSearch: UpdateDomainConfig, https response
        error StatusCode: 400, RequestID: <RequestID>, ValidationException:
        2 validation errors detected: Value ''arn:aws:es:us-west-2:<account>:domain/domain1''
        at ''domainName'' failed to satisfy constraint: Member must satisfy regular
        expression pattern: [a-z][a-z0-9\-]+; Value ''arn:aws:es:us-west-2:<account>:domain/domain1''
        at ''domainName'' failed to satisfy constraint: Member must have length less
```

### Crossplane Version

1.13.0

### Provider Version

v1.20.0

### Kubernetes Version

1.31

### Kubernetes Distribution

EKS
