### ISSUE TITLE
[Bug]: error during upgrade from v1.17.0 to v1.21.0 for ReplicationGroup.elasticache.aws.upbound.io/v1beta2 - atRestEncryptionEnabled property type was chenged from boolean to string

### ISSUE THREAD

**Issue by mlubanski** [crossplane-contrib/provider-upjet-aws#1738]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

* elasticache.aws.upbound.io/v1beta2 - ReplicationGroup

### Resource MRs required to reproduce the bug

```yaml
apiVersion: elasticache.aws.upbound.io/v1beta2
kind: ReplicationGroup
metadata:
  annotations:
    crossplane.io/composition-resource-name: replicationgroup
    crossplane.io/external-create-pending: "2024-09-26T11:43:21Z"
    crossplane.io/external-create-succeeded: "2024-09-26T11:43:21Z"
    crossplane.io/external-name: eu1lab-eks001-37e7c918-sample-redis
  finalizers:
  - finalizer.managedresource.crossplane.io
  name: sample-redis-9b5gl-nrt6n
  ownerReferences:
  - apiVersion: cache.aws.crossplane.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XRedisCluster
    name: sample-redis-9b5gl
    uid: 7641d3bb-c0b9-4a02-9f93-d83d7db3cfcf
spec:
  deletionPolicy: Delete
  forProvider:
    applyImmediately: false
    atRestEncryptionEnabled: true
    authTokenSecretRef:
      key: redis_auth_token
      name: sample-redis-auth-token-generated
      namespace: crossplane-demo
    authTokenUpdateStrategy: ROTATE
    autoGenerateAuthToken: true
    autoMinorVersionUpgrade: "false"
    automaticFailoverEnabled: true
    description: eu1lab-eks001-crossplane-demo-sample-redis
    engine: redis
    engineVersion: "7.0"
    ipDiscovery: ipv4
    maintenanceWindow: mon:07:00-mon:08:00
    multiAzEnabled: false
    networkType: ipv4
    nodeType: cache.t4g.micro
    numCacheClusters: 2
    numNodeGroups: 1
    parameterGroupName: eu1lab-eks001-37e7c918-sample-redis
    port: 6379
    region: eu-west-1
    replicasPerNodeGroup: 1
    securityGroupIds:
    - sg-xxxxx
    snapshotRetentionLimit: 2
    snapshotWindow: 06:00-07:00
    subnetGroupName: private-subnets-vpc-xxxxxx
    transitEncryptionEnabled: true
    transitEncryptionMode: required
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: upbound-provider-aws
  writeConnectionSecretToRef:
    name: crossplane-demo-sample-redis-redisconfig
    namespace: crossplane-system
status:
  atProvider:
    applyImmediately: false
    arn: arn:aws:elasticache:eu-west-1:xxxx:replicationgroup:eu1lab-eks001-37e7c918-sample-redis
    atRestEncryptionEnabled: true
    authTokenUpdateStrategy: ROTATE
    autoMinorVersionUpgrade: "false"
    automaticFailoverEnabled: true
    clusterEnabled: false
    clusterMode: disabled
    dataTieringEnabled: false
    description: eu1lab-eks001-crossplane-demo-sample-redis
    engine: redis
    engineVersion: "7.0"
    engineVersionActual: 7.0.7
    id: eu1lab-eks001-37e7c918-sample-redis
    ipDiscovery: ipv4
    kmsKeyId: ""
    maintenanceWindow: mon:07:00-mon:08:00
    memberClusters:
    - eu1lab-eks001-37e7c918-sample-redis-001
    - eu1lab-eks001-37e7c918-sample-redis-002
    multiAzEnabled: false
    networkType: ipv4
    nodeType: cache.t4g.micro
    numCacheClusters: 2
    numNodeGroups: 1
    parameterGroupName: eu1lab-eks001-37e7c918-sample-redis
    port: 6379
    primaryEndpointAddress: master.eu1lab-eks001-37e7c918-sample-redis.viorjt.euw1.cache.amazonaws.com
    readerEndpointAddress: replica.eu1lab-eks001-37e7c918-sample-redis.viorjt.euw1.cache.amazonaws.com
    replicasPerNodeGroup: 1
    securityGroupIds:
    - sg-xxxxx
    snapshotRetentionLimit: 2
    snapshotWindow: 06:00-07:00
    subnetGroupName: private-subnets-vpc-xxxxx
    transitEncryptionEnabled: true
    transitEncryptionMode: required
```

### Steps to Reproduce

I have a Composition which was setting `atRestEncryptionEnabled`

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xredisclusters.cache.aws.crossplane.com
  name: redisclusters.cache.aws.crossplane.com-v1alpha1
spec:
  compositeTypeRef:
    apiVersion: cache.aws.crossplane.com/v1alpha1
    kind: XRedisCluster
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  mode: Pipeline
  pipeline:
  - step: generate-rediscluster
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          apiVersion: elasticache.aws.upbound.io/v1beta2
          kind: ReplicationGroup
          metadata:
            annotations:
              {{ setResourceNameAnnotation "replicationgroup" }}     
              crossplane.io/external-name: {{ $redisClusterName }}
          spec:
            providerConfigRef:
              name: upbound-provider-aws
            forProvider:
              atRestEncryptionEnabled: true
           ...
```

After I upgraded to latest upbound aws provider I started getting in ealsticache sub-provider below errors:

![Image](https://github.com/user-attachments/assets/ed008695-4db8-499a-8189-ec1a5c39ad0c)

I checked docs and noticed that in provider version [1.17.0](https://marketplace.upbound.io/providers/upbound/provider-aws-elasticache/v1.17.0/resources/elasticache.aws.upbound.io/ReplicationGroup/v1beta2) property had type `boolean` but in [latest version](https://marketplace.upbound.io/providers/upbound/provider-aws-elasticache/v1.21.0/resources/elasticache.aws.upbound.io/ReplicationGroup/v1beta2) this property type was changed to `string`

I updated my Composition to:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xredisclusters.cache.aws.crossplane.com
  name: redisclusters.cache.aws.crossplane.com-v1alpha1
spec:
  compositeTypeRef:
    apiVersion: cache.aws.crossplane.com/v1alpha1
    kind: XRedisCluster
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  mode: Pipeline
  pipeline:
  - step: generate-rediscluster
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          apiVersion: elasticache.aws.upbound.io/v1beta2
          kind: ReplicationGroup
          metadata:
            annotations:
              {{ setResourceNameAnnotation "replicationgroup" }}     
              crossplane.io/external-name: {{ $redisClusterName }}
          spec:
            providerConfigRef:
              name: upbound-provider-aws
            forProvider:
              atRestEncryptionEnabled: "true"
           ...
```

Afterwards I had still same error, I tried on my ReplicationGroup MR object delete `atRestEncryptionEnabled` property (from both `spec.forProvider` and `status.atProvider`). Property `status.atProvider.atRestEncryptionEnabled` is coming back as a `boolean` type

In CompositeResource I can see below event:

```
   Warning  ComposeResources  4m4s (x55 over 29m)  defined/compositeresourcedefinition.apiextensions.crossplane. │
│ io  cannot compose resources: cannot apply composed resource "replicationgroup": failed to create manager for e │
│ xisting fields: failed to convert new object (/sample-redis-9b5gl-nrt6n; elasticache.aws.upbound.io/v1beta2, Ki │
│ nd=ReplicationGroup) to smd typed: .status.atProvider.atRestEncryptionEnabled: expected string, got &value.valu │
│ eUnstructured{Value:true}
```

On provider Pod I am getting below error (pods is being restarted over an over again):

```
 E0317 11:10:08.093056       1 reflector.go:150] k8s.io/client-go@v0.30.0/tools/cache/reflector.go:232: Failed to watch │
│  *v1beta2.ReplicationGroup: failed to list *v1beta2.ReplicationGroup: json: cannot unmarshal bool into Go struct field │
│  ReplicationGroupObservation.items.status.atProvider.atRestEncryptionEnabled of type string                            │
│ W0317 11:10:19.468293       1 reflector.go:547] k8s.io/client-go@v0.30.0/tools/cache/reflector.go:232: failed to list  │
│ *v1beta2.ReplicationGroup: json: cannot unmarshal bool into Go struct field ReplicationGroupObservation.items.status.a │
│ tProvider.atRestEncryptionEnabled of type string                                                                       │
│ E0317 11:10:19.468328       1 reflector.go:150] k8s.io/client-go@v0.30.0/tools/cache/reflector.go:232: Failed to watch │
│  *v1beta2.ReplicationGroup: failed to list *v1beta2.ReplicationGroup: json: cannot unmarshal bool into Go struct field │
│  ReplicationGroupObservation.items.status.atProvider.atRestEncryptionEnabled of type string
```

### What happened?

After upgrading to latest elasticache provider property `atRestEncryptionEnabled` type in `ReplicationGroup` CRD was changed from `boolean` to `string`. Can't reconcile my CompositeResources/ManagedResources anymore

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

1.19.0

### Provider Version

1.21.0

### Kubernetes Version

1.30.10

### Kubernetes Distribution

EKS
