### ISSUE TITLE
[Bug]: eks-pod-identity-agent eks addon keeps UPDATING

### ISSUE THREAD

**Issue by jorgephiguera** [crossplane-contrib/provider-upjet-aws#1744]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

eks.aws.upbound.io/v1beta1 - Addon

### Resource MRs required to reproduce the bug

```yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
  name: eks-pod-identity-agent
spec:
  forProvider:
    addonName: eks-pod-identity-agent
    addonVersion: v1.3.5-eksbuild.2
    clusterNameRef:
      name: mycluster
    region: myregion
  providerConfigRef:
    name: aws-appolow
```

### Steps to Reproduce

The addon is always in UPDATING state, via web interface and aws cli

### What happened?

The addon it is always in UPDATING status. When the update process ends, start a new one. But I do not know what is really doing  because aws eks describe-addon shows me the same output when active than when updating. It only changes the "status" and "modifiedAt" fields. For example, the eks-pod-identity-agent daemonset is not restarted at every update process.
This situation does not permit to update the eks cluster

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

v1.18.3

### Provider Version

v1

### Kubernetes Version

v1.30.9-eks-8cce635

### Kubernetes Distribution

EKS
