### ISSUE TITLE
[Bug]: Dynamodb index autoscale is always overridden by provider

### ISSUE THREAD

**Issue by arturkasperek** [crossplane-contrib/provider-upjet-aws#1760]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

table.dynamodb.aws.upbound.io/v1beta2

### Resource MRs required to reproduce the bug

Table
Awsappautoscalingtarget

### Steps to Reproduce

Create a below resource:
```
apiVersion: dynamodb.aws.upbound.io/v1beta2
kind: Table
metadata:
  name: test-table
spec:
  deletionPolicy: Delete
  forProvider:
    attribute:
    - name: id
      type: S
    - name: query
      type: S
    - name: search_type
      type: S
    billingMode: PROVISIONED
    globalSecondaryIndex:
    - hashKey: search_type
      name: query-index
      projectionType: ALL
      rangeKey: query
    hashKey: id
    region: us-east-1
  initProvider:
    globalSecondaryIndex:
    - readCapacity: 1500
      writeCapacity: 500
    readCapacity: 1500
    writeCapacity: 500
  providerConfigRef:
    name: production
```

and later turn on autoscaling - I think you can make it manually for purpose of a demo.

Please notice that after some time there are a lot of `Successfully requested update of external resource` events. 

### What happened?

Even with this `initProvider` config:
```
  initProvider:
    globalSecondaryIndex:
    - readCapacity: 1500
      writeCapacity: 500
    readCapacity: 1500
    writeCapacity: 500
```
crossplane provider still update the `globalSecondaryIndex` read and write capacity.
Interesting note, for main table `readCapacity` and `writeCapacity` works fine and crossplane doesn't make any updates.
It seems crossplane has some problem with the fact that `globalSecondaryIndex` is an array

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

v1.17.1-up.1

### Provider Version

v1.21.1

### Kubernetes Version

v1.30.10

### Kubernetes Distribution

EKS

**Comment by mbudnek** [comment]
If anyone else stumbles over this issue, the solution I found is to disable the `LateInitialize` management policy so that Crossplane doesn't set the read and write capacity fields in `spec.forProvider` after creating the table.  i.e.
```
apiVersion: dynamodb.aws.upbound.io/v1beta2
kind: Table
metadata:
  name: test-table
spec:
  managementPolicies: ["Create", "Delete", "Update", "Observe"]
  ...
```
https://docs.crossplane.io/latest/concepts/managed-resources/#managementpolicies
