### ISSUE TITLE
[Bug]: RDS Aurora PostgreSQL Cluster with restoreToPointInTime Fails to Create ClusterInstance Since v1.19.0

### ISSUE THREAD

**Issue by farzanSmd** [crossplane-contrib/provider-upjet-aws#1764]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

rds.aws.upbound.io/v1beta2

### Resource MRs required to reproduce the bug

Cluster
ClusterInstance
ClusterParameterGroup
Secret

### Steps to Reproduce

1. Create Aurora PostgreSQL Cluster with restoreToPointInTime:

```
apiVersion: rds.aws.upbound.io/v1beta2
kind: Cluster
spec:
  forProvider:
    engine: aurora-postgresql
    engineVersion: "16.4"
    region: eu-west-1
    restoreToPointInTime:
      sourceClusterIdentifier: source-cluster-1
      restoreType: full-copy
      useLatestRestorableTime: true
    ...
```

### What happened?

Since provider-aws-rds version v1.19.0, creating an RDS Cluster using the restoreToPointInTime option results in only the Cluster being created, but no ClusterInstance is provisioned.

This functionality worked correctly until v1.18.5, where both the Cluster and ClusterInstance were successfully created. 

I tested in following versions where it didn't work:
- v1.19.0
- v.1.20.0
- v.1.21.1

### Relevant Error Output Snippet

```shell
In k8s ClusterInstance log, getting following warning:

cannot resolve references: mg.Spec.ForProvider.ClusterIdentifier: referenced field was empty (referenced resource may not yet be ready)
```

### Crossplane Version

1.19.0

### Provider Version

1.19.0

### Kubernetes Version

1.32.0

### Kubernetes Distribution

EKS
