### ISSUE TITLE
[Bug]: Conversion Webhook Failure in AWS Kinesis Provider

### ISSUE THREAD

**Issue by saarrabe** [crossplane-contrib/provider-upjet-aws#1770]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

streams.kinesis.aws.upbound.io/v1beta1, v1beta2

### Resource MRs required to reproduce the bug

Just try and creating the kinesisStream
below is an example of the resource my argo-app was creating
```
apiVersion: kinesis.aws.upbound.io/v1beta1
kind: Stream
metadata:
  annotations:
    crossplane.io/external-name: new-test-stream
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: new-test-stream
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-west-2
    retentionPeriod: 24
    shardLevelMetrics:
      - IncomingBytes
      - OutgoingBytes
    shardCount: 2
    streamModeDetails:
      - streamMode: PROVISIONED
  providerConfigRef:
    name: dev
```

### Steps to Reproduce

Just try and creating the kinesisStream
mentioned the crd type above

### What happened?

The conversion webhook for Kinesis Stream CRD (streams.kinesis.aws.upbound.io) fails with "Address is not allowed" error, preventing proper management of Kinesis resources and causing Argo CD sync failures.
```Error from server: conversion webhook for kinesis.aws.upbound.io/v1beta1, Kind=Stream failed: Post "https://provider-aws-kinesis.crossplane-system.svc:9443/convert?timeout=30s": Address is not allowed ``` 

#### Impact
1) Unable to fetch or manage Kinesis Stream resources via kubectl
2) StreamConsumer resources cannot resolve references to Stream resources (though after the mitigation steps stremConsumer still doesnt seem to work)
3) Argo CD applications fail to sync
4) Provider's informer cache fails to sync

### Relevant Error Output Snippet

```shell
from server: conversion webhook for kinesis.aws.upbound.io/v1beta1, Kind=Stream failed: Post "https://provider-aws-kinesis.crossplane-system.svc:9443/convert?timeout=30s": Address is not allowed  

and argo cd cant reach the create crd as well
```

### Crossplane Version

 1.14.9

### Provider Version

 v1.16.0, v1.21.0, v1.6.0

### Kubernetes Version

Client Version: v1.23.3 Server Version: v1.28.15-eks-bc803b4

### Kubernetes Distribution

EKS

### Workarounds Applied
Successfully mitigated by:
Patching the CRD to disable 
```
kubectl patch crd streams.kinesis.aws.upbound.io --type=json -p '[{"op":"replace","path":"/spec/conversion/strategy","value":"None"},{"op":"remove","path":"/spec/conversion/webhook"}]'
```
