### ISSUE TITLE
[Bug]: Cannot create NodeGroup with launch template

### ISSUE THREAD

**Issue by doncorsean** [crossplane-contrib/provider-upjet-aws#1784]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

eks.aws.upbound.io/v1beta2 - NodeGroup

### Resource MRs required to reproduce the bug
```
apiVersion: eks.aws.upbound.io/v1beta2
kind: NodeGroup
metadata:
  name: test
spec:
  forProvider:
    region: us-east-1
    clusterNameRef:
      name: devops-platform
    nodeRoleArn: arn:aws:iam::<account-id>:role/devops-platform-nodegroup
    subnetIds:
    - subnet-1
    - subnet-2
    - subnet-3
    scalingConfig:
      maxSize: 10
    launchTemplate:
      name: devops-platform-lt
      version: $Default
---
apiVersion: ec2.aws.upbound.io/v1beta2
kind: LaunchTemplate
metadata:
  name: devops-platform-lt
spec:
  forProvider:
    name: devops-platform-lt
    region: us-east-1
    updateDefaultVersion: true
    instanceType: t3.large
    securityGroupNameSelector:
      matchLabels:
        role: devops-platform-nodepool
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 20
```
### Steps to Reproduce

apply above

### What happened?

No NodeGroup created due to aws api error returned by provider

### Relevant Error Output Snippet

```shell
Message: async create failed: failed to create the resource: [{0 creating EKS Node Group (devops-platform:test): operation error EKS: CreateNodegroup, https response error StatusCode: 400, RequestID: dfgdfgfshg-6618-4bc5-sfhg4-sfgsfgfdhsfh, InvalidRequestException: The parameter groupName cannot be used with the parameter subnet  []}]
```

### Crossplane Version

1.19.0

### Provider Version

xpkg.upbound.io/upbound/provider-aws-eks:v1

### Kubernetes Version

1.32

### Kubernetes Distribution

EKS

### Additional Info

NodeGroups  create fine unless I supply a launch template then returns this groupName error. Any ideas?
