### ISSUE TITLE
[Bug]: Keyspace table "Diff detected" when there's a space as the difference in the column type

### ISSUE THREAD

**Issue by gburke-ppb** [crossplane-contrib/provider-upjet-aws#1785]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

apiVersion: Table.keyspaces.aws.upbound.io/v1beta2                                                                                                                                                                                                      kind: Table

Tested on version 1.21.0

### Steps to Reproduce

```
apiVersion: keyspaces.aws.upbound.io/v1beta2                                                                                                                                                                                                      kind: Table
...
spec:
  forProvider:
   ...
    schemaDefinition:
      column:
      - name: some_name
        type: map<text,text>
   ...
```
With `map<text,text>`, with no spaces!

The table is created fine.

In the status, the `type` for this column shows as `map<text, text>`, with a space.

At the DEBUG level in the `provider-aws-keyspaces` pods there's a `Diff detected` because `map<text, text>` != 
 `map<text,text>`

(extracted and formatted)
```
    "schema_definition.0.column.1726152564.name":*terraform.ResourceAttrDiff{
      Old:"", 
      New:"my_column", 
      NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0
    },
    "schema_definition.0.column.1726152564.type":*terraform.ResourceAttrDiff{
      Old:"", 
      New:"map<text,text>",      <<<<<<<<<<<<<<<<<<<
      NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0
    },
    

    "schema_definition.0.column.4190854449.name":*terraform.ResourceAttrDiff{
      Old:"my_column", 
      New:"", 
      NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0
    },
    "schema_definition.0.column.4190854449.type":*terraform.ResourceAttrDiff{
      Old:"map<text, text>",       <<<<<<<<<<<<<<<<<<<
      New:"", 
      NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0
    },
```

### What happened?

Lots of messages regarding "Diff Detected" in the logs, and the output to `kubectl get tables.keyspaces.aws.upbound.io` shows `SYNCED` as `False`.

### Relevant Error Output Snippet

```shell
See above
```

### Crossplane Version

1.19.0

### Provider Version

1.21.0

### Kubernetes Version

Server Version: v1.32.3-eks-bcf3d70

### Kubernetes Distribution

EKS 1.32.0
