### ISSUE TITLE
[Bug]: ThrottlingException when using Opensearch

### ISSUE THREAD

**Issue by aiell0** [crossplane-contrib/provider-upjet-aws#1809]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

I am getting the following in my AWS account when attempting to use the OpenSearch Domain and DomainPolicy resources:

`failed to update the resource: [{0 updating OpenSearch Domain Policy (domain-policy-name-here): ThrottlingException: Rate exceeded status code: 400, request id: b5321bd5-5564-4d62-a073-bda230367ebb []}]`

These errors are flapping and are causing our notification systems to go on the fritz on a regular basis. Is there any way to configure the polling on a per-resource basis? I have set the polling via this github issue I found but it doesn't seem to have worked: https://github.com/crossplane-contrib/provider-upjet-aws/issues/799.

### Resource MRs required to reproduce the bug

```
apiVersion: opensearch.aws.upbound.io/v1beta1
kind: Domain
metadata:
  name: example
spec:
  deletionPolicy: Orphan
  forProvider:
    advancedOptions:
      override_main_response_version: 'true'
    clusterConfig:
      - instanceCount: 2
        instanceType: t3.small.search
        zoneAwarenessConfig:
          - availabilityZoneCount: 2
    domainName: example
    ebsOptions:
      - ebsEnabled: true
        volumeSize: 50
        volumeType: gp3
    encryptAtRest:
      - enabled: true
    engineVersion: OpenSearch_2.13
    region: us-east-1
    softwareUpdateOptions:
      - autoSoftwareUpdateEnabled: false
    vpcOptions:
      - securityGroupIdRefs:
          - name: foo
          - name: bar
        subnetIds:
          - foobar
  providerConfigRef:
    name: crossplane-provider-config
```

### Steps to Reproduce

1. Deploy a few of these manifests in one AWS account.

### What happened?

I frequently get throttled which causes ArgoCD to call the application degraded. It's causing flappiness.

### Relevant Error Output Snippet

```shell
failed to update the resource: [{0 updating OpenSearch Domain Policy (domain-policy-name-here): ThrottlingException: Rate exceeded status code: 400, request id: b5321bd5-5564-4d62-a073-bda230367ebb []}]
```

### Crossplane Version

1.16.5

### Provider Version

1.11.0

### Kubernetes Version

1.29

### Kubernetes Distribution

EKS

### Additional Info

I'm open to the idea that this may just be AWS's fault, but I think there needs to be a configuration to allow the opensearch provider to call less frequently. OpenSearch clusters don't change that much so I think this should be fine, but this may be a bigger lift than I think.
