### ISSUE TITLE
[Bug]: LBListener: Terraform validation fails during reconciliation when using `targetGroupArnSelector`

### ISSUE THREAD

**Issue by aswnrana** [crossplane-contrib/provider-upjet-aws#1811]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

"lblisteners.elbv2.aws.upbound.io/v1beta1"
"lblisteners.elbv2.aws.upbound.io/v1beta2"

### Description
This issue covers scenarios where managed resources get stuck in continuous reconciliation loops after successful initial creation via composition. The provider repeatedly attempts to update the resource but fails validation, even though the resource exists and is functional in the cloud provider. This typically occurs when there's a mismatch between how the provider handles initial creation versus subsequent reconciliation of resources with reference selectors.

## Composition manifest

[composition.txt](https://github.com/user-attachments/files/20944934/composition.txt) (File is too large to directly paste here, download this and change the extension to `.yaml`)

## Functions
```
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/upbound/function-go-templating:v0.10.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-environment-configs
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.3.0

```

## Managed Resource
 *Directly provisioned resources are not causing issues*
```
apiVersion: elbv2.aws.upbound.io/v1beta2
kind: LBListener
metadata:
  labels:
    listenerDnat: mr-debug
  name: mr-debug-test
spec:
  forProvider:
    defaultAction:
    - targetGroupArnSelector:
        matchLabels:
          targetGroupDnat: mr-debug-test
      type: forward
    loadBalancerArnSelector:
      matchLabels:
        dnatNlbIb: fancy-aws-network
      policy:
        resolution: Required
        resolve: Always
    port: 80
    protocol: TCP
    region: eu-central-1
---
apiVersion: elbv2.aws.upbound.io/v1beta2
kind: LBTargetGroup
metadata:
  annotations:
  labels:
    targetGroupDnat: mr-debug-test
  name: test
spec:
  forProvider:
    name: mr-debug-test
    port: 80
    protocol: TCP
    region: eu-central-1
    targetType: ip
    vpcIdSelector:
      matchLabels:
        networks.aws.platform.upbound.io/network-id: configuration-aws-network

```

### Steps to Reproduce

- Apply the provided Composition, functions and XRD (make sure to replace the vpcId and subnets): 
`kubectl apply -f composition.yaml`
- Create a claim to trigger the composition:
```
kubectl apply -f - <<EOF
apiVersion: connectivity.cse-upbound.cloud/v1alpha1
kind: DNATNetwork
metadata:
  name: fancy-aws-network
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: default
  forProvider:
    region: eu-central-1
    defaultNetwork: true
    port: "5432"
    description: "Test DB resource"
    targetRdsInstances:
      - instanceIdentifier: rds-test-1-2-3.eu-central-1.rds.amazonaws.com
    sourceAddress:
      - fromAWSaccount: 10.162.0.0/16
      - fromAWSaccount: 10.202.0.0/16
    networkRef:
      id: fancy-aws-network
EOF
```

- Wait for resources to create (~2-3 minutes):
`kubectl get managed -l crossplane.io/composite=fancy-aws-network`

- Observe the LBListener reconciliation errors:
`kubectl describe lblisteners.elbv2.aws.upbound.io fancy-aws-network-lb-list`

### Expected Result
All resources reconcile successfully without errors

### Actual Result
- LB and TargetGroup create successfully
- LBListener creates in AWS but shows continuous reconciliation errors:
cannot patch the managed resource via server-side apply: 
`spec.forProvider.defaultAction is a required parameter`
- Resource works but configuration updates don't apply

### Relevant Error Output Snippet

- Continuous reconciliation loop with errors:
  ```
  cannot patch the managed resource via server-side apply: LBListener.elbv2.aws.upbound.io "xxx" is invalid: 
  spec: Invalid value: "object": spec.forProvider.defaultAction is a required parameter
  ```
- Event logs showing thousands of reconciliation attempts:
  ```
  Warning  CannotUpdateManagedResource  10m (x2649 over 22m)  managed/elbv2.aws.upbound.io/v1beta1, kind=lblistener
  ```
- Terraform-level validation errors:
  ```
  Invalid Attribute Combination: Either "default_action[0].target_group_arn" or "default_action[0].forward" must be specified
  ```

### Crossplane Version

1.20.0-up.1

### Provider Version

v1.23.1

### Kubernetes Version

v1.32.2

### Kubernetes Distribution

Kind
