### ISSUE TITLE
sns: `TopicSubscription` throws bad error on bad topic reference

### ISSUE THREAD

**Issue by AaronME** [crossplane-contrib/provider-upjet-aws#337]
### What happened?
Deployed a topic and subscription in different zones (by accident). The error message that was returned implies that the TopicArn field is invalid, instead of stating that the topic could not be found.

### How can we reproduce it?

```yaml
---
apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: example-sns-topic
spec:
  forProvider:
    region: us-east-1
---
apiVersion: sns.aws.upbound.io/v1beta1
kind: TopicSubscription
metadata:
  name: example-sns-topic-email
spec:
  forProvider:
    endpoint: "test@example.com"
    protocol: email
    region: us-west-1
    topicArnRef:
      name: example-sns-topic
```

Note that the regions do not match. This is on purpose for this demo.

Apply the above and you will get the following error:
"apply failed: error creating SNS Topic Subscription: InvalidParameter: Invalid parameter: TopicArn"

### What environment did it happen in?

* Universal Crossplane Version: 1.10.1-up.1
* Provider Version: provider-aws 0.23.0
