### ISSUE TITLE
ElastiCache Cluster CRD does not create a K8s secret

### ISSUE THREAD

**Issue by shivasdp** [crossplane-contrib/provider-upjet-aws#426]
### What happened?

When creating a CacheCluster CRD for redis, no kubernetes secret is created containing the details required for establishing a connection to redis, e.g.

    endpoint url
    port
    authtoken or username+password

Refer to the bug which is there in community edition 
https://github.com/crossplane-contrib/provider-aws/issues/551 

### How can we reproduce it?

```yaml
---
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: "test-cache-cluster"
spec:
  forProvider:
    region: us-east-1
    tags:
      Application: TEST-UM
      Group: QA
      Environment: QA
    engine: redis
    nodeType: cache.t2.micro
    numCacheNodes: 1
    parameterGroupNameRef:
      name: "test-cache-param-grp-1"
    subnetGroupNameRef:
      name: "test-cache-sn-grp1"
    securityGroupIds:
    - sg-004209965c448fbe3
  providerConfigRef:
    name: qa-proconf
  
  writeConnectionSecretToRef:
    name: cache-cluster-qa-redis-secret
    namespace: test

```
```sh
# k get -n test secret cache-cluster-qa-redis-secret

NAME                             TYPE                                DATA   AGE
cache-cluster-qa-redis-secret   connection.crossplane.io/v1alpha1   0      30h
```

### What environment did it happen in?

* Universal Crossplane Version: 1.10.1
* Provider Version: provider-aws:v0.20.0

* Kubernetes version : Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:36:26Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes distribution : AWS EKS
