### ISSUE TITLE
SSM Parameters should support  paths in names

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane-contrib/provider-upjet-aws#441]
### What problem are you facing?

Currently the AWS SSM parameter resource is using [config.NameAsIdentifier](https://github.com/upbound/provider-aws/blob/46abcb23986d0e7cafd4012382a6292f53e57746/config/externalname.go#L1856), which means that the k8s name is used. 

However, it is common in AWS SSM parameters to have path based naming like `/abc/xyz/parameter`.  These kinds of names are not allowed in Kubernetes objects. 

<https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-su-create.html>

### How could Official AWS Provider help solve your problem?

Have a `spec.forProvider.name` to support path based naming.

**Comment by svscheg** [comment]
Need to investigate if we can use some another confirmation for this resource to have a spec.forProvider.name.

**Comment by stevendborrelli** [comment]
Please note that a workaround is the use the `crossplane.io/external-name` annotation to set the path directly. For example: 

```yaml
apiVersion: ssm.aws.upbound.io/v1beta1
kind: Parameter
metadata:
    annotations:
         crossplane.io/external-name: /team1/primaryRegion
spec:
  forProvider:
      dataType: text
      insecureValue: us-east
      region: us-east-1
```
