### ISSUE TITLE
cognito: `UserPool` CRD has many parameters as array while they are not

### ISSUE THREAD

**Issue by yibo-long** [crossplane-contrib/provider-upjet-aws#443]
### What happened?

Many parameters in [cognitoidp.aws.upbound.io/v1beta1.UserPool](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.27.0/resources/cognitoidp.aws.upbound.io/UserPool/v1beta1) are specified as an array while it actually should be object since they should only be either set once or optional.

Those are what we got issues while trying to use:

 * [accountRecoverySetting](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.27.0/resources/cognitoidp.aws.upbound.io/UserPool/v1beta1#doc:spec-forProvider-accountRecoverySetting). Terraform [account_recovery_setting](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#account_recovery_setting) is optional.
 * [verificationMessageTemplate](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.27.0/resources/cognitoidp.aws.upbound.io/UserPool/v1beta1#doc:spec-forProvider-verificationMessageTemplate). Terraform [verification_message_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#verification_message_template) is optional
 * [passwordPolicy](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.27.0/resources/cognitoidp.aws.upbound.io/UserPool/v1beta1#doc:spec-forProvider-passwordPolicy). Terraform [password_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#password_policy) is optional.
 * [softwareTokenMfaConfiguration](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.27.0/resources/cognitoidp.aws.upbound.io/UserPool/v1beta1#doc:spec-forProvider-softwareTokenMfaConfiguration). Terraform [software_token_mfa_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#software_token_mfa_configuration) is optional.
 * [adminCreateUserConfig](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.27.0/resources/cognitoidp.aws.upbound.io/UserPool/v1beta1#doc:spec-forProvider-adminCreateUserConfig). Terraform [admin_create_user_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#admin_create_user_config) is optional.
 * [emailConfiguration](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.27.0/resources/cognitoidp.aws.upbound.io/UserPool/v1beta1#doc:spec-forProvider-emailConfiguration). Terraform [email_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#email_configuration) is optional.

### How can we reproduce it?

We have composition like this:

```
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cognito.aws.span.io
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.span.io/v1alpha1
    kind: XCognito
  resources:
  - name: UserPool
    base:
      apiVersion: cognitoidp.aws.upbound.io/v1beta1
      kind: UserPool
      spec:
        forProvider:
          name: ""
          accountRecoverySetting:
            recoveryMechanism:
              name: verified_email
              priority: 1
          adminCreateUserConfig:
            allowAdminCreateUserOnly: true
...
```

While trying to use this composition, it got those errors:

```
cannot render composed resource from resource template at index 0: cannot use dry-run create to name composed resource: UserPool.cognitoidp.aws.upbound.io "*****" is invalid: [spec.forProvider.accountRecoverySetting: Invalid value: "object": spec.forProvider.accountRecoverySetting in body must be of type array: "object", spec.forProvider.adminCreateUserConfig: Invalid value: "object": spec.forProvider.adminCreateUserConfig in body must be of type array: "object" ... ]
```

So it requires an array like for those config while it doesn't make sense as an array:

```
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cognito.aws.span.io
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.span.io/v1alpha1
    kind: XCognito
  resources:
  - name: UserPool
    base:
      apiVersion: cognitoidp.aws.upbound.io/v1beta1
      kind: UserPool
      spec:
        forProvider:
          name: ""
          accountRecoverySetting:
          - recoveryMechanism:
            - name: verified_email
              priority: 1
          adminCreateUserConfig:
          - allowAdminCreateUserOnly: true
```

### What environment did it happen in?

* Universal Crossplane Version: 1.11.0
* Provider Version: v0.27.0
