### ISSUE TITLE
Validate Regions

### ISSUE THREAD

**Issue by plumbis** [crossplane-contrib/provider-upjet-aws#459]
### What problem are you facing?
If a resource specifies the wrong region it looks like a DNS issue with the pod. 

For example, creating this ec2 instance:
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: upbound-docs-quickstart
spec:
  forProvider:
    # Canonical, Ubuntu, 22.04 LTS, amd64 jammy image build on 2023-01-15
    ami: ami-0ab0629dba5ae551d 
    instanceType: t2.micro
    region: us-east2
```

Will produce this error
```
 Warning  CannotObserveExternalResource  76s (x8 over 12m)  managed/ec2.aws.upbound.io/v1beta1, kind=instance  cannot run refresh: refresh failed: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 9, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.us-east2.amazonaws.com/": dial tcp: lookup sts.us-east2.amazonaws.com on 10.96.0.10:53: no such host:
```

The error is correct, the host doesn't exist, but it's an issue with the `spec.forProvider.region`. 

### How could Official AWS Provider help solve your problem?
The provider should validate the provided region and log a warning that the region is unknown (bonus points for the log saying `Did you mean...`)
