### ISSUE TITLE
Request for `aws_route53_zone_association`  resource

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-upjet-aws#510]
### What resource do you need?

Terraform Resource Name: `aws_route53_zone_association`

Manages a Route53 Hosted Zone VPC association. VPC associations can only be made on private zones.

See the `aws_route53_vpc_association_authorization` resource for setting up cross-account associations

### What is your use case?
cross-account route53 private zones and a central resolver

**Comment by nagavijayan-nagarathinam** [comment]
Note From Terraform:

Unless explicit association ordering is required (e.g., a separate cross-account association authorization), usage of this resource is not recommended. Use the vpc configuration blocks available within the [aws_route53_zone resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone) instead.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone_association

**Comment by ytsarev** [comment]
We previously discussed it here https://github.com/upbound/provider-aws/pull/463#issuecomment-1413613595

CC @sergenyalcin @ulucinar

**Comment by ulucinar** [comment]
Hi @haarchri,
Would using the `aws_route53_vpc_association_authorization` be sufficient for your use case so that:
- The VPC, which resides in a different account than the route53 zone, is associated with the zone via the [`spec.forProvider.vpc`](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.29.0/resources/route53.aws.upbound.io/Zone/v1beta1#doc:spec-forProvider-vpc) of `route53.Zone`. 
- And via the [`route53.VPCAssociationAuthorization`](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.29.0/resources/route53.aws.upbound.io/VPCAssociationAuthorization/v1beta1), we do the authorization.

What I suspect here is that specifying a VPC in a different account than the `route53.Zone` in the `vpc` slice will simply not work. This is something we need to check.

**Comment by haarchri** [comment]
we specifying at the moment on our private zones the local vpc, and 2 vpcs from different network accounts with our resolvers - and currently it is not working

**Comment by patrickleet** [comment]
I also need this resource for the same reason

**Comment by kb2001** [comment]
We have a need for this feature to solve the same problem

**Comment by haarchri** [comment]
https://marketplace.upbound.io/providers/upbound/provider-aws-route53/v0.36.0/resources/route53.aws.upbound.io/VPCAssociationAuthorization/v1beta1

**Comment by AliAllomani** [comment]
I believe we are facing the same issue with cross account route53 hosted zone vpc association

Where `Zone` resource conflicts with `ZoneAssociation` resource

`Zone` removes the additional VPCs from the hosted zone after reconciliation
`ZoneAssociation` re-adds the VPC to the hosted zone

Based on https://marketplace.upbound.io/providers/upbound/provider-aws-route53/v0.44.0/resources/route53.aws.upbound.io/Zone/v1beta1

`initProvider` supports only `vpc.vpcRegion`, therefore we cannot add `vpcId` or `vpcIdSelector` to avoid updating the associated VPCs with the hosted zone

**Example**

```yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: test-vpc-ali-123
  labels:
    vpc: test-vpc-ali-123
spec:
  forProvider:
    region: eu-central-1
    cidrBlock: 172.16.0.0/16
    tags:
      Name: test-vpc-ali-123
  providerConfigRef:
    name: account-a

---
apiVersion: route53.aws.upbound.io/v1beta1
kind: Zone
metadata:
  labels:
    zone: example
  name: example
spec:
  forProvider:
    name: test-vpc-ali-123.example.com
    region: eu-central-1
  initProvider:
    vpc:
      - vpcIdSelector:
          matchLabels:
            vpc: test-vpc-ali-123
  providerConfigRef:
    name: account-a

---
apiVersion: route53.aws.upbound.io/v1beta1
kind: VPCAssociationAuthorization
metadata:
  name: example
spec:
  forProvider:
    region: eu-central-1
    # VPC ID in account-b
    vpcId: vpc-06b4d61c63b8f5d68
    # Zone ID in account-a
    zoneIdSelector:
      matchLabels:
        zone: example
  providerConfigRef:
    name: account-a

---
apiVersion: route53.aws.upbound.io/v1beta1
kind: ZoneAssociation
metadata:
  name: example
spec:
  forProvider:
    region: eu-central-1
    # VPC ID in account-b
    vpcId: vpc-06b4d61c63b8f5d68
    # Zone ID in account-a
    zoneIdSelector:
      matchLabels:
        zone: example
  providerConfigRef:
    name: account-b
```
 
**CloudTrail events from Account A**

![image](https://github.com/upbound/provider-aws/assets/17993914/f1fb840d-8449-4e37-9d96-d36578eaeb42)

**CloudTrail events from Account B**

![image](https://github.com/upbound/provider-aws/assets/17993914/97ee6bdd-6101-4e72-bd45-18f9e63c87e4)
