### ISSUE TITLE
`external-name` intermittently changes

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane-contrib/provider-upjet-aws#610]
### What happened?

For some managed objects (such as `subnets.ec2.aws.upbound.io`) the external name gets updated from the explicitly set (e.g. `private-subnet-0-us-east-2-main`) to the actual subnet-id (as per AWS):

![image](https://user-images.githubusercontent.com/7312236/225913933-ea5884cd-cab7-417b-8d4f-feb338ad61c4.png)

### How can we reproduce it?

Composition including some AWS resource (e.g. `kind: Subnet`) and patch setting the `external-name` annotation such as:

```
    - name: private-subnet-0
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels: &labels
            type: subnet
            nx-subnet-visibility: private
            nx-component: eks
        spec:
          forProvider:
            mapPublicIpOnLaunch: false
            tags:
              <<: *labels
              kubernetes.io/role/internal-elb: "1"
      patches:
        - *commonParametersPatch
        [... REDACTED ...]
        - &setName
          type: CombineFromComposite
          toFieldPath: metadata.name
          combine:
            variables:
            - fromFieldPath: spec.resourceConfig.region
            - fromFieldPath: spec.parameters.clusterName
            strategy: string
            string:
              fmt: "private-subnet-0-%s-%s"
        - <<: *setName
          toFieldPath: metadata.annotations["crossplane.io/external-name"]
        - <<: *setName
          toFieldPath: spec.forProvider.tags.Name
```

### What environment did it happen in?

* Universal Crossplane Version: crossplane:v1.11.2 
* Provider Version: xpkg.upbound.io/upbound/provider-aws:v0.31.0 
* Kubernetes version: v1.25.6
