### ISSUE TITLE
Cannot set `external-name` to security group

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane-contrib/provider-upjet-aws#614]
### What happened?

When `external-name` annotation is set to a security group, AWS provider fails to create/import the object with the following error:

```
Invalid id: "system-nodegroup-us-east-2-main" (expecting "sg-...") 
```

### How can we reproduce it?

Have a securitygroup added in a composition which adds the `external-name` annotation, as for example:
```
    - name: sg-system-nodegroup
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            description: Allow everything IN from local, everything OUT
      patches:
        - type: PatchSet
          patchSetName: common-patches
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.vpcId
          toFieldPath: spec.forProvider.vpcId
        - &setName
          type: CombineFromComposite
          toFieldPath: metadata.name
          combine:
            variables:
            - fromFieldPath: spec.resourceConfig.region
            - fromFieldPath: spec.parameters.clusterName
            strategy: string
            string:
              fmt: "system-nodegroup-%s-%s"
        - <<: *setName
          toFieldPath: spec.forProvider.tags.Name
        - <<: *setName
          toFieldPath: metadata.annotations["crossplane.io/external-name"]
        - <<: *setName
          toFieldPath: spec.forProvider.name
```

### What environment did it happen in?

* Universal Crossplane Version: v1.11.2
* Provider Version: v0.31.0
* Kubernetes Version: 1.25.6
