### ISSUE TITLE
The `WebIdentity` didn't work outside of the EKS

### ISSUE THREAD

**Issue by cychiang** [crossplane-contrib/provider-upjet-aws#621]
### What happened?

When using `WebIdentity` in `ProviderConfig` outside of the EKS will result an error that the `terraform-provider-aws` is not able to locate default aws config. 

The issue is related to the existed bug in [here](https://github.com/hashicorp/terraform-provider-aws/issues/27019). Basically, when using EKS with IRSA, the `pod-identity` from AWS will inject required environment variables to build up the aws config. So the `terraform` is able to build the aws config from the environment variables provided by the `pod-identity`. 

However, when using `WebIdentity` outside of the EKS, we will need to specify the `AWS_WEB_IDENTITY_TOKEN_FILE` for the token in the [environment variable](https://github.com/upbound/provider-aws/blob/main/internal/clients/provider_config.go#L351), and let `ProviderConfig` to assign `AWS_ROLE_ARN` when provision AWS resources. Here comes the issue, `terraform-provider-aws` didn't accept partially configuration either all set from the environment variables or all from the `.tf` code.

### How can we reproduce it?

Please reference [here](https://github.com/hashicorp/terraform-provider-aws/issues/27019) for reproduce steps. 

### Potential solution
By adding a parameter for token path in `WebIdentity` struct and remove the step to configure environment variable `AWS_WEB_IDENTITY_TOKEN_FILE` in provider might solve the issue. But I think the issue is somehow related to #613 

Setup a dummy env `AWS_ROLE_ARN` to the provider works as well because the role will be override from the `ProviderConfig` anyway.

**Comment by nabuskey** [comment]
With the issue mentioned above resolved, it looks like it is now possible to specify the token file with a small code change. Currently, the `webIdentity` configuration options are tied to IRSA but it should not be this way because underlying [STS call ](https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#STS.AssumeRoleWithWebIdentity)is not tied to EKS.

**Comment by dee-kryvenko** [comment]
Google search leads here, but workaround is missing. Here's what worked for me. I re-created runtime environment that would look like it is IRSA by using `ControllerConfig`:

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: upbound-provider-aws
spec:
  env:
    - name: AWS_REGION
      value: {{ .Values.region }}
    - name: AWS_DEFAULT_REGION
      value: {{ .Values.region }}
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /run/secrets/aws/token
    - name: AWS_ROLE_ARN
      value: {{ .Values.roleARN | quote }}
  volumes:
    - name: aws
      projected:
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            path: token
  volumeMounts:
    - name: aws
      mountPath: /run/secrets/aws
      readOnly: true
```

And then - reference it from the provider:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws
spec:
  package: xpkg.upbound.io/upbound/provider-aws:{{ .Values.version }}
  controllerConfigRef:
    name: upbound-provider-aws
```

`ProviderConfig` then can be told that we are in IRSA environment:

```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.configName }}
spec:
  credentials:
    # See https://github.com/upbound/provider-aws/issues/621
    # source: WebIdentity
    # webIdentity:
    #   roleARN: {{ .Values.roleARN | quote }}
    # Instead, for now we are using ControllerConfig to mimic IRSA setup
    source: IRSA
```
