### ISSUE TITLE
rds: `Instance` says it created successfully when it didn't

### ISSUE THREAD

**Issue by negz** [crossplane-contrib/provider-upjet-aws#635]
### What happened?

I created an RDS instance without specifying a username or password. When I `kubectl describe` the instance I see:

```
  Normal  CreatedExternalResource  2m6s (x5 over 4m51s)    managed/rds.aws.upbound.io/v1beta1, kind=instance  Successfully requested creation of external resource
```

But also newer events:

```
  Normal  PendingExternalResource  2m24s (x20 over 4m48s)  managed/rds.aws.upbound.io/v1beta1, kind=instance  Waiting for external resource existence to be confirmed
```

And also:

```
    Last Transition Time:  2023-03-30T03:17:21Z
    Message:               apply failed: "password": required field is not set:
"username": required field is not set:
    Reason:  ApplyFailure
    Status:  False
    Type:    LastAsyncOperation
```

This is misleading. The provider is telling me it successfully requested creation of the external resource, but it has not.

### How can we reproduce it?

Apply the following MR:

```yaml
$ cat xp/oreilly-instance.yaml
apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: what-is-crossplane
spec:
  forProvider:
    region: us-west-1
    instanceClass: db.t3.micro
    allocatedStorage: 20
    engine: postgres
```

### What environment did it happen in?

* Universal Crossplane Version: OSS Crossplane v1.11.1
* Provider Version: v0.31.0
