### ISSUE TITLE
Load Balancer not creating after deleting

### ISSUE THREAD

**Issue by saichaitanya11** [crossplane-contrib/provider-upjet-aws#652]
### What happened?

I am trying to create a load balancer (ELB) using managed resource. The load balancer got created, but after deleting from the AWS Console, it is not creating again. The READY and SYNCED status remain true in the shell. Similarly, during a service deployment I have a load balancer created, but facing the same issue there also. Deleting the load balancer which got created during the service from the AWS Console is not creating again.

_Load Balancer Script_

`apiVersion: elb.aws.upbound.io/v1beta1
kind: ELB
metadata:
  name: lb-03042023
spec:
  forProvider:
    availabilityZones:
      - us-east-1b
    listener:
      - instancePort: 8000
        instanceProtocol: http
        lbPort: 80
        lbProtocol: http
    region: us-east-1
  providerConfigRef:
    name: default`

<img width="238" alt="image" src="https://user-images.githubusercontent.com/70645368/230063050-e5c769b2-68ab-446a-92f1-6f532b41316e.png">

_Service Script_

`apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-api
spec:
  type: LoadBalancer
  selector:
    app: nginxwebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80`

### How can we reproduce it?

1. Create a service file or a managed resource file for an ELB.
2. Apply the file and verify under load balancers if the resource is created.
3. Delete the same from the Console and wait for some time.
4. Verify again if the resource is getting created.

### What environment did it happen in?

* Universal Crossplane Version: v1.1.11
* Provider Version: xpkg.upbound.io/upbound/provider-aws:v0.21.0
* OS: Linux 
* Kubernetes Version: v1.24

**Comment by svscheg** [comment]
The issue is reproducible on the latest master, using Load Balancer Script:
```
apiVersion: elb.aws.upbound.io/v1beta1
kind: ELB
metadata:
  name: examplesvetatesting
spec:
  forProvider:
    availabilityZones:
      - us-west-1b
    listener:
      - instancePort: 8000
        instanceProtocol: http
        lbPort: 80
        lbProtocol: http
    region: us-west-1
```

output with error:
```
 - lastTransitionTime: "2023-04-19T20:09:20Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-04-19T19:58:33Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-04-19T20:10:02Z"
    message: "apply failed: creating ELB Classic Load Balancer (examplesvetatesting):
      ValidationError: Only one of SubnetIds or AvailabilityZones may be specified\n\tstatus
      code: 400, request id: cbc9d9f6-61c3-47d3-841c-6f64cca7d3fd: "
    reason: ApplyFailure
    status: "False"
    type: LastAsyncOperation
  - lastTransitionTime: "2023-04-19T20:10:02Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
```
