### ISSUE TITLE
`security_group_rule` import not working InvalidPermission.Duplicate

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-upjet-aws#656]
### What happened?
we created security_group_rule with provider-jet-aws and started migration to official provider-aws

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    crossplane.io/external-name: sgrule-1856709650
  name: alb-dev-securitygroup-ingress
spec:
  deletionPolicy: Orphan
  forProvider:
    cidrBlocks:
    - 1.2.3.4/32
    - 45.45.45.0/22
    - 103.103.103.0/22
    fromPort: 443
    protocol: tcp
    region: eu-central-1
    securityGroupId: sg-12345678910e10
    securityGroupIdRef:
      name: alb-dev-securitygroup
    toPort: 443
    type: ingress
  providerConfigRef:
    name: xxxx
```

```
we got the following error:
    Message:               apply failed: [WARN] A duplicate Security Group rule was found on (sg-12345678910e10). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error: InvalidPermission.Duplicate: the specified rule "peer: 1.2.3.4/32, TCP, from port: 443, to port: 443, ALLOW" already exists
             status code: 400, request id: ab6a1a5c-fe9f-48ca-9ca0-34ffa602ea62: 
```

it looks like this issue only happen for `type: ingess` `security_group_rule`

```
NAME                             READY   SYNCED   EXTERNAL-NAME       AGE
alb-dev-securitygroup-egress     True    True     sgrule-206570049    2m12s
alb-dev-securitygroup-ingress    False   True     sgrule-1856709650   2m12s
alb-qa-securitygroup-egress      True    True     sgrule-1614198747   2m12s
alb-qa-securitygroup-ingress     False   True     sgrule-2371296659   2m11s
```

### What environment did it happen in?

* Crossplane Version: 1.11.3
* Provider Version: v0.31.0
* Kubernetes Version:  
* Kubernetes Distribution:

**Comment by svscheg** [comment]
The issue is prioritised and now in the Backlog. Label needs:triage will be deletes from issue.

**Comment by haarchri** [comment]
@svscheg  perhaps its fixed with https://github.com/upbound/provider-aws/pull/685 ? - using the new resources ?

**Comment by turkenf** [comment]
Hi @haarchri,

I could not reproduce this issue with the provided information, I can successfully import resources using the examples below:
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    crossplane.io/external-name: sgrule-127223177
  name: example1-ingress
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-central-1
    cidrBlocks:
      - 10.0.0.0/16
    fromPort: 443
    protocol: tcp
    securityGroupIdRef:
      name: test-vpc
    toPort: 443
    type: ingress
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    crossplane.io/external-name: sgrule-3560852184
  name: example1-egress
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-central-1
    cidrBlocks:
      - 103.103.100.0/22
    fromPort: 443
    protocol: tcp
    securityGroupIdRef:
      name: test-vpc
    toPort: 443
    type: egress
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    crossplane.io/external-name: sgrule-1153586460
  name: example2-ingress
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-central-1
    cidrBlocks:
      - 1.2.3.4/32
    fromPort: 443
    protocol: tcp
    securityGroupIdRef:
      name: test-vpc
    toPort: 443
    type: ingress
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    crossplane.io/external-name: sgrule-1557800833
  name: example2-egress
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-central-1
    cidrBlocks:
      - 45.45.44.0/22
    fromPort: 443
    protocol: tcp
    securityGroupIdRef:
      name: test-vpc
    toPort: 443
    type: egress
```

- kubectl get managed
```
NAME                                                    READY   SYNCED   EXTERNAL-NAME       AGE
securitygrouprule.ec2.aws.upbound.io/example1-egress    True    True     sgrule-3560852184   18m
securitygrouprule.ec2.aws.upbound.io/example1-ingress   True    True     sgrule-127223177    18m
securitygrouprule.ec2.aws.upbound.io/example2-egress    True    True     sgrule-1557800833   18m
securitygrouprule.ec2.aws.upbound.io/example2-ingress   True    True     sgrule-1153586460   18m
```

Could you please provide other `SecurityGroupRule` examples that you use?
