### ISSUE TITLE
SSM Parameter stores the ARN in forProvider instead of atProvider

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane-contrib/provider-upjet-aws#678]
### What happened?

SSM Parameter stores the ARN of the generated resource in `forProvider` instead of `atProvider`. 

### How can we reproduce it?

Apply the following yaml 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: parameter-secret
  namespace: upbound-system
data:
  example-key: dGVzdGtleQ==
type: Opaque
---
apiVersion: ssm.aws.upbound.io/v1beta1
kind: Parameter
metadata:
  annotations:
    meta.upbound.io/example-id: ssm/v1beta1/parameter
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    region: us-west-1
    type: String
    valueSecretRef:
      key: example-key
      name: parameter-secret
      namespace: upbound-system
```

Then verify that the arn is in the `forProvider` section:

```
spec:
    deletionPolicy: Delete
    forProvider:
      arn: arn:aws:ssm:us-west-1:609897127049:parameter/foo
      dataType: text
      region: us-west-1
      tags:
        crossplane-kind: parameter.ssm.aws.upbound.io
        crossplane-name: foo
        crossplane-providerconfig: default
      tier: Standard
      type: String
      valueSecretRef:
        key: example-key
        name: parameter-secret
        namespace: upbound-system
    providerConfigRef:
      name: default
  status:
    atProvider:
      id: foo
      tagsAll:
        crossplane-kind: parameter.ssm.aws.upbound.io
        crossplane-name: foo
        crossplane-providerconfig: default
      version: 1
```

### What environment did it happen in?

* Crossplane Version: universal-crossplane-1.11.3-up.1  
* Provider Version:  xpkg.upbound.io/upbound/provider-aws:v0.32.1 
* Kubernetes Version:  
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes Distribution:  kind

**Comment by turkenf** [comment]
This issue can be reproduced.
After the Observe Only support, we see the references of `forProvider` in `atProvider`. In this case we should not see the `arn` reference in `forProvider`.  The following `spec` is from v0.34.0:
```
spec:
  deletionPolicy: Delete
  forProvider:
    arn: arn:aws:ssm:us-west-1:569674547146:parameter/foo
    dataType: text
    region: us-west-1
    tags:
      crossplane-kind: parameter.ssm.aws.upbound.io
      crossplane-name: foo
      crossplane-providerconfig: default
    tier: Standard
    type: String
    valueSecretRef:
      key: example-key
      name: parameter-secret
      namespace: upbound-system
  managementPolicy: FullControl
  providerConfigRef:
    name: default
status:
  atProvider:
    allowedPattern: ""
    arn: arn:aws:ssm:us-west-1:569674547146:parameter/foo
    dataType: text
    description: ""
    id: foo
    keyId: ""
    tags:
      crossplane-kind: parameter.ssm.aws.upbound.io
      crossplane-name: foo
      crossplane-providerconfig: default
    tagsAll:
      crossplane-kind: parameter.ssm.aws.upbound.io
      crossplane-name: foo
      crossplane-providerconfig: default
    tier: Standard
    type: String
    version: 1
```
