### ISSUE TITLE
LaunchTemplate creation failing when using updateDefaultVersion field

### ISSUE THREAD

**Issue by bhavinkotak** [crossplane-contrib/provider-upjet-aws#694]
### What happened?
LaunchTemplate resource creation is failing when using updateDefaultVersion flag. Provider is adding defaultVersion field on its own, creating conflict with updateDefaultVersion field. It gives the error - `cannot run refresh: refresh failed: Conflicting configuration arguments: "default_version": conflicts with update_default_version Conflicting configuration arguments: "update_default_version": conflicts with default_version`

### How can we reproduce it?
launch_template resource block which is used; however in the rendered resource block - it's adding `defaultVersion: 1` field
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: launch-template-1
spec:
  deletionPolicy: Delete
  forProvider:
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          - deleteOnTermination: 'true'
            encrypted: 'true'
            volumeSize: 150
            volumeType: gp3
    iamInstanceProfile:
      - arn: >-
          arn:aws:iam::xxxxx:instance-profile/nodegroup-role
    imageId: ami-06666dbb84908f946
    instanceType: m5.12xlarge
    maintenanceOptions:
      - autoRecovery: default
    metadataOptions:
      - httpEndpoint: enabled
        httpPutResponseHopLimit: 1
        httpTokens: optional
    monitoring:
      - enabled: true
    name: launch-template-1
    region: us-west-2
    tagSpecifications:
      - resourceType: instance
        tags:
          Name: cluster
          k8s.io/cluster-autoscaler/enabled: 'true'
    updateDefaultVersion: true
    userData: >-XXXXXXXXXXX=
    vpcSecurityGroupIds:
      - sg-XX
      - sg-XXX
  managementPolicy: FullControl
  providerConfigRef:
    name: upbound-aws-provider
```

### What environment did it happen in?

* Crossplane Version: 1.12.1
* Provider Version: 0.34.0
* Kubernetes Version: 1.23
* Kubernetes Distribution: EKS
