### ISSUE TITLE
EC2 Instance ebs_block_device should be immutable

### ISSUE THREAD

**Issue by dg-nvm** [crossplane-contrib/provider-upjet-aws#720]
### What happened?

When EBS-backed instance is created, it's EBS disk will be added to ebs_block_device field in TF. If EBS volume is added through VolumeAttachment, which creates another entry, next reconciliation will try to override VolumeAttachment and recreate instance.

### How can we reproduce it?

1. Create EBS volume in us-east-1 using CP or AWS Console.
2. Create Composition with EC2 and VolumeAttachment using this created Volume:

```
- name: vm
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Instance
      spec:
        deletionPolicy: Delete
        forProvider:
          ami: ami-00b5b48d6335258a3
          instanceType: t2.small
          region: us-east-1
          availabilityZone: us-east-1a
    patches:
      - type: ToCompositeFieldPath
        fromFieldPath: metadata.name
        toFieldPath: metadata.annotations.vmname
- name: storage_volume_attachment
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: VolumeAttachment
      spec:
        forProvider:
          region: us-east-1
          deviceName: /dev/sdf
          instanceIdRef:
            name: 
            policy:
              resolution: Required
              resolve: Always
          volumeIdRef:
            name: CreatedExternallyVolumeName
            policy:
              resolution: Required
              resolve: Always
          availabilityZone: us-east-1a
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: metadata.annotations.vmname
        toFieldPath: spec.forProvider.instanceIdRef.name
```
3. Apply Composition/CRD and Claim. 
4. Observe than on second reconcile, provider will want to destroy Instance.
5. To debug - get UID of the Instance resource, attach to provider pod, copy /tmp/<UID> to /tmp/test, change deletion prevention policy to false and run terraform plan. Plan should show that it wants to recreate EBSes again and this forces replacement.

### What environment did it happen in?

* Crossplane Version:  1.12.1
* Provider Version: v0.34.0
* Kubernetes Version:  1.26.1
* Kubernetes Distribution:  EKS
