### ISSUE TITLE
Unable to patches from a field within the composed resource to a field within the XR (AccessKey)

### ISSUE THREAD

**Issue by ashishvaishno** [crossplane-contrib/provider-upjet-aws#750]
Hello,

* I have a central crossplane eks cluster where I am creating an IAM user and AccessKey in my destination account
* I want to share the accesskey and secret and create a k8s secret file in my destination k8s cluster so that the developer can access the credentials
* Below are my xrd and composition 
<details>
  <summary>XRD</summary>

  ### XRD
  ```
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiamusers.crossplane.test.com
spec:
  claimNames:
    kind: IAMUser
    plural: iamusers
  group: crossplane.test.com
  names:
    kind: XIAMUser
    plural: xiamusers
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: IAM User test
              properties:
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Orphan
                      type: string
                      default: "Orphan"
                    serviceName:
                      description: Name of the iam user
                      type: string
                    serviceNamespace:
                      description: Namespace
                      type: string
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - serviceName
                  - serviceNamespace
                  type: object
              required:
              - resourceConfig
              type: object
            status:
              description: IAM User test
              properties:
                encryptedSecret:
                  type: string
                createDate:
                  type: string
                encryptedSesSmtpPasswordV4:
                  type: string
                id:
                  type: string
                keyFingerprint:
                  type: string
                pgpKey:
                  type: string
                status:
                  type: string
                user:
                  type: string
              type: object
          type: object
  ```
</details>

<details>
  <summary>Composition</summary>

  ### Part of my composition
```
    - name: iam-user
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: User
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.serviceName
          toFieldPath: metadata.annotations[crossplane.io/external-name]
    - name: iam-user-accesskey
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: AccessKey
        spec:
          forProvider:
            userSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.serviceName
          toFieldPath: spec.writeConnectionSecretToRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.id
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.encryptedSecret
          toFieldPath: status.encryptedSecret
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.createDate
          toFieldPath: status.createDate
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.encryptedSesSmtpPasswordV4
          toFieldPath: status.encryptedSesSmtpPasswordV4
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.status
          toFieldPath: status.status
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.user
          toFieldPath: status.user
    - name: remote-secret
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          deletionPolicy: "Orphan"
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: ""
                namespace: ""
              data:
                access_key: ""
                access_key_secret: ""
      patches:
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            strategy: string
            string:
              fmt: "kubernetes-provider-config-%s"
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.serviceNamespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.serviceName
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: status.id
          toFieldPath: spec.forProvider.manifest.data.access_key
        - type: FromCompositeFieldPath
          fromFieldPath: status.encryptedSecret
          toFieldPath: spec.forProvider.manifest.data.access_key_secret
  ```
</details>

* I can only see [4 of the mentioned 6 status.atProvider attributes](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/v0.36.0/resources/iam.aws.upbound.io/AccessKey/v1beta1#doc:status-atProvider)  (not counting the pgp ones 😉 )
```
Status:
  Conditions:
    Last Transition Time:  2023-06-23T07:51:53Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-06-23T07:52:22Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Create Date:             2023-06-23T07:52:01Z
  Id:                      XXXXXXXXX
  Status:                  Active
  User:                    xxxxxxxxxxx
```
* Locally the secret created has the Access key secret (using writeConnectionSecretToRef), but my remote k8s secret is empty. 
* May be I am missing some configuration 🤷‍♂️ 
* Please feel free to move this into a discussion(if this is not a bug 😄 )

iam provider version : xpkg.upbound.io/upbound/provider-aws-iam:v0.36.0

Regards
Ashish

**Comment by gosim-bah** [comment]
@ashishvaishno did you ever get past this bug?

**Comment by jrossBah** [comment]
Hey we are still continually running into this issue. In our problem we aren't even able to control what the created Managed Resource level secret puts into it.

```
name: accesskey
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: AccessKey
      patches:
        # adds name and namespace for resource secret
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.accessKeySecretNamespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-accesskey-secret"
```

This creates a secret with the following things in it.
```
attribute.secret: REDACTED
attribute.ses_smtp_password_v4: REDACTED
password: REDACTED
username: REDACTED
```
THis also then causes issues when trying to get these values our using flux, or Kustomization and into other places as the `.` in the keys causes errors.

**Comment by jrossBah** [comment]
@ashishvaishno so I figured this out. Upbound does a really poor job of documenting this and explaining this.

So the ConnectionSecret which a managed resource has is different than connectionDetails. The ConnectionSecret is specific to the MR and has data that is determined by the provider. HOWEVER upbound in their marketplace does not document or make clear what any of these things would be. Your only way to know is to create the managed resource and see what is there. 

As well there is a specific way of notating in the connectionDetails block of a resource to get it to grab a value from the ManagedResource's ConnectionSecret here is how you would do that.

```
- name: accesskey
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: AccessKey
      writeConnectionSecretToRef:
        name: my-connection-secret
        namespace: my-namespace
      connectionDetails:
        - type: FromConnectionSecretKey
          name: accessKeySecret
          fromConnectionSecretKey: password
        - type: FromConnectionSecretKey
          name: accessKeyId
          fromConnectionSecretKey: username
```

We know the above provider when `writeConnectionSecretToRef` is declared creates a kubernetesSecret this secret contains the managedResource's ConnectionSecrets. again there is nothing that documents what is actually in there anywhere in the docs or any sort of show of this.

Then in the `connectionDetails` adding `type: FromConnectionSecretKey` means to pull the value from something in this ManagedResources ConnectionSecret which you would be able to see with `kubectl get secret my-connection-secret -n my-namespace`

lastly `fromConnectionSecretKey` says which key in that kubernetes secret to grab the value from and put in the claim or composite resource secret. 

Hope this helps. And I hope Upbound cleans up these docs to better explain this.
