### ISSUE TITLE
Resource association has to provide an option to attach the resource not only per ARN but also per matchLabels:

### ISSUE THREAD

**Issue by sterziev88** [crossplane-contrib/provider-upjet-aws#773]
### What problem are you facing?

I want to use resource association to attach tgw to resource share. I already have resource share created by terraform and I provide its ARN but my crossplane will create a tgw and I can't set its ARN. So will be useful option if I would be able to use matchLabels or something like that to attach my tgw ARN to resource association.
--->

### How could Official AWS Provider help solve your problem?
Will be really useful if  ARN of the resource which you want to attach to resource share be able to be attached with matchLabels or something like that.
-->

**Comment by turkenf** [comment]
Hi @sterziev88,

Thank you for raising this issue. Could you provide more information(example manifest you are using etc.) so that we can fully understand the issue you are facing?

**Comment by sterziev88** [comment]
Hi @turkenf 

That is my manifest:
    resourceAssociations:
      - name: "resource-association-crossplane"
        annotations: {}
        labels: {}
        region: "eu-west-1"
        resourceArn: "arn:XXXXX"
        resourceShareArn: "${TGW_RA_SHARE_ARN}"

As I obtain the ${TGW_RA_SHARE_ARN} from terraform. That works as expected but because I run script which creates entire environment and everything is automated the issue with the resourceArn is something which stops my script because it searches the resource ARN but it is not there....or I don't know how to submit it on correct way. I create my resource which in my example is tgw with that manifest: 
transitGateway:
      name: "tgw-crossplane"
      annotations:  {}
      labels:
        createdByCrossplane: "true"
      region: "${AWS_REGION}"
      autoAcceptSharedAttachments: enable
      tags:
        Name: tgw-crossplane
        createdByCrossplane: "true"

after that I am not able to obtain the tgw ARN in order to replace it value in resource-association resource.

So will b e great if there is an option to use resourceARN matchlabels for example where I will be able to set a label to my tgw during its creation and then to use it for resourceARN in resource-association creation resource.

Thank you in advance.

**Comment by turkenf** [comment]
Thank you for your reply @sterziev88, can you please verify me so that I can fully understand your request?

```
apiVersion: ram.aws.upbound.io/v1beta1
kind: ResourceAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1beta1/resourceassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    resourceArn: ${arn}
    resourceShareArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
```

In the above example manifest you want to pass the parameter `resourceArn` using selector, correct?
