### ISSUE TITLE
It is not possible to import securitygroup which is created previously  

### ISSUE THREAD

**Issue by nujragan** [crossplane-contrib/provider-upjet-aws#782]
### What happened?

This problem is best described with an example:

Create a managed resource with a securitygroup with deletionPolicy: Orphan

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: test-sg-rule-deletion
spec:
  deletionPolicy: Orphan
  forProvider:
    description: test security group import
    region: us-east-1
    name: testsg
    vpcId: vpcxxxx
  providerConfigRef:
    name: XXXX

```
Apply the securitygroup
Delete the securitygroup
Now the securitygroup stays behind in AWS which is as expected.
Apply the securitygroup again
Now the security will have a reconcile error and cannot create a duplicate groupname.

```
apply failed: creating Security Group (testsg): InvalidGroup.Duplicate:
      The security group 'testsgv3' already exists for VPC 'vpc-XXX'
      code: 400
```

Tried using `crossplane.io/external-name` annotation but the external name for a securitygroup is a securitygroup ID which is random and generated by aws.

We expect that it can reconcile the existing securitygroup.

We want to import this created securitygroup but this is not possible this way.

This also prevents us from migrating from crossplane-contrib/provider-aws to the official provider.

This was an issue with crossplane-contrib/provider-aws(https://github.com/crossplane-contrib/provider-aws/issues/1175)
but they seemed to have fixed it. 

Expected behavior is for the securitygroup to reconcile based on name instead of id which is generated by aws(which we have no control over or means to get it)

### How can we reproduce it?

Above steps should help to reproduce the issue

### What environment did it happen in?

* Crossplane Version: v0.12.1
* Provider Version: 0.37.0
* Kubernetes Version:   1.25
* Kubernetes Distribution:  EKS

**Comment by jbw976** [comment]
@nujragan did you try this scenario according to the documentation in https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/? The `crossplane.io/external-name` annotation is key to the import flow, but I didn't see it mentioned in this issue, hence why I'm asking 😇

**Comment by nujragan** [comment]
@jbw976 `crossplane.io/external-name `for a securitygroup is the security group id, which is generated by aws which is not known by the composition

**Comment by nujragan** [comment]
Just FYI: crossplane-contrib/provider-aws has already solved this issue: https://github.com/crossplane-contrib/provider-aws/issues/1175

**Comment by turkenf** [comment]
Hi @nujragan,

Thank you for raising this issue but I could not reproduce the issue. Could you please try again?
- After deleting the source in your terminal, can you try `crossplane.io/external-name` annotation as below:
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    crossplane.io/external-name: sg-01234567891234567 
    meta.upbound.io/example-id: ec2/v1beta1/securitygroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-east-1
    description: test security group import
    name: testsg
    vpcIdRef:
      name: sample-vpc
```
- You can find the external-name:
```
NAME                                       READY   SYNCED   EXTERNAL-NAME          AGE
securitygroup.ec2.aws.upbound.io/example   True    True     sg-01234567891234567   7m13s
```
or:
```
AWS Console->EC2->Security Groups->Security group ID->sg-.........
```
![Screenshot 2023-07-11 at 13 32 19](https://github.com/upbound/provider-aws/assets/103541666/122baade-5587-4384-9e30-a4084b92963d)
