### ISSUE TITLE
kmsKeyArnSelector

### ISSUE THREAD

**Issue by sidpalas** [crossplane-contrib/provider-upjet-aws#803]
### What problem are you facing?

The KMS key for `cluster.eks.aws.upbound.io` `spec.forProvider.encryptionConfig` requires the KMS key ARN.

https://marketplace.upbound.io/providers/upbound/provider-aws-eks/v0.37.0/resources/eks.aws.upbound.io/Cluster/v1beta1#doc:spec-forProvider-encryptionConfig-provider-keyArn

I want to create a `key.kms.aws.upbound.io` and `cluster.eks.aws.upbound.io` within the same Composition and use the KMS key for the cluster encryption config.

### How could Official AWS Provider help solve your problem?

In order to facilitate creating a KMS key and using it for the Cluster config at the same time, it would be useful to implement a `kmsKeyArnSelector`.

This would be similar to the `kmsKeyArnRef` implemented for `seccurityconfiguration.glue.aws.upbound.io` (https://marketplace.upbound.io/providers/upbound/provider-aws/v0.37.0/resources/glue.aws.upbound.io/SecurityConfiguration/v1beta1)

### Workaround:

My current workaround is to store the KMS key ARN as a field on the XR status populated by a patch:
```
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.clusterKmsKeyArn
          policy:
            fromFieldPath: Required
```

And then patch that into the Cluster config:
```
       - type: FromCompositeFieldPath
          fromFieldPath: status.clusterKmsKeyArn
          toFieldPath: spec.forProvider.encryptionConfig[0].provider[0].keyArn
          policy:
            fromFieldPath: Required
```
