### ISSUE TITLE
`VPC`: Refresh fails when `ipv6_ipam_pool_id` is specified (lateinit)

### ISSUE THREAD

**Issue by korenyoni** [crossplane-contrib/provider-upjet-aws#859]
### What happened?

When `ipv6_ipam_pool_id` is specified for the `VPC` MR, the resource is successfully provisioned, however on further reconciles the generated Terraform includes the `ipv6_cidr_block_network_border_group` field, which must be specified alongside `assign_generated_ipv6_cidr_block`. However `assign_generated_ipv6_cidr_block` conflicts with `ipv6_ipam_pool_id`.

![CleanShot 2023-09-05 at 16 12 07](https://github.com/upbound/provider-aws/assets/10080107/d6330930-c93e-4aab-a568-50bc36da3e4e)

##### MR (derived from XR; some fields redacted)

```yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
spec:
  deletionPolicy: Delete
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    instanceTenancy: default
    ipv6CidrBlockNetworkBorderGroup: us-east-1
    ipv6IpamPoolId: ipam-pool-12345678901234567
    ipv6NetmaskLength: 56
    region: us-east-1
    tags:
      Name: network-qsfrr
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: network-qsfrr-nnz5z
      crossplane-providerconfig: rnd-sandbox
  initProvider: {}
  managementPolicies:
    - '*'
  providerConfigRef:
    name: rnd-sandbox
```

##### `provider-aws` logs:

```bash
2023-09-05T13:00:01Z    DEBUG    events    cannot run refresh: refresh failed: Missing required argument: "ipv6_cidr_block_network_border_group": all of `assign_generated_ipv6_cidr_block,ipv6_cidr_block_network_border_group` must be specified    {"type": "Warning", "object": {"kind":"VPC","name":"network-qsfrr-nnz5z","uid":"86eaa743-4f77-4181-9e48-184ab3b22ee5","apiVersion":"ec2.aws.upbound.io/v1beta1","resourceVersion":"1024207"}, "reason": "CannotObserveExternalResource"}
```

##### Generated Terraform:

```json
{
  "provider": {
    "aws": {
      "assume_role": {
        "external_id": "rnd-sandbox",
        "role_arn": "arn:aws:iam::123456789123:role/crossplane-delegated",
        "tags": null,
        "transitive_tag_keys": null
      },
      "region": "us-east-1"
    }
  },
  "resource": {
    "aws_vpc": {
      "network-n4zc5-jvmqc": {
        "cidr_block": "10.0.0.0/16",
        "enable_dns_support": true,
        "instance_tenancy": "default",
        "ipv6_cidr_block_network_border_group": "us-east-1",
        "ipv6_ipam_pool_id": "ipam-pool-12345678901234567",
        "ipv6_netmask_length": 56,
        "lifecycle": { "prevent_destroy": false },
        "tags": {
          "Name": "network-n4zc5",
          "crossplane-kind": "vpc.ec2.aws.upbound.io",
          "crossplane-name": "network-n4zc5-jvmqc",
          "crossplane-providerconfig": "rnd-sandbox"
        }
      }
    }
  },
  "terraform": {
    "required_providers": {
      "aws": { "source": "hashicorp/aws", "version": "4.67.0" }
    }
  }
}
```

### What environment did it happen in?

* Crossplane Version: `crossplane/crossplane:v1.14.0-rc.0.203.g3996f200`
* Provider Version: `0.40.0`
* Kubernetes Version: `v1.24.16-eks-2d98532`
* Kubernetes Distribution: `EKS`
