### ISSUE TITLE
upbound aws provider fails to create/delete SNS topic on china due to bad aws partition (shall be aws-cn and not aws)

### ISSUE THREAD

**Issue by yebolenko** [crossplane-contrib/provider-upjet-aws#881]
### What environment did it happen in?

* Crossplane Version: docker.io/crossplane/crossplane:**v1.13.2**
* Provider Version: xpkg.upbound.io/upbound/provider-aws:**v0.38.0**
* Kubernetes Version:  1.27
* Kubernetes Distribution:  EKS

**Comment by yebolenko** [comment]
Please ensure that all upbound components use aws partition as a parameter and not hardcoded aws

**Comment by yebolenko** [comment]
it seems that some info in the issue has not been update:
I'm summarizing it again:
We create SNS Topic with crossplane/upbound on aws China region cn-north-1
When SNS topic shall be deleted, it fails with the following error:
InvalidParameter: Invalid parameter: TopicArn Reason: A REDACTED ARN must begin with **arn:aws-cn**, not **arn:aws:sns**:REDACTED:REDACTED:ye-sns-topic-2-demo-china-cnn1\\n\\tstatus code: 40I

**Comment by yebolenko** [comment]
any progress?

**Comment by turkenf** [comment]
@yebolenko, could you please fill in the description properly? Reproduction steps, the MRs you used, expected and actual behavior.

**Comment by yebolenko** [comment]
It's always reproducible. You just need to create/delete SNS topic on aws region cn-north-1 (china).
It doesn't work due to hardcoded aws partition id (aws) and not aws-cn. 
I believe it's general issue also in many other resources. You need to add ability to pass aws partition id as parameter (aws is default)

**Comment by yebolenko** [comment]
any update? it's URGENT issue for us. We cannot use SNS and (maybe other components) on china.
As I said, we use an official upbound release

**Comment by turkenf** [comment]
Please provide the requested information in the description.

**Comment by yebolenko** [comment]
Providing again all details:
------------------------- 
**What happened?**  When SNS topic shall be created/deleted, it fails with the following error:
**InvalidParameter: Invalid parameter: TopicArn Reason: A REDACTED ARN must begin with arn:aws-cn, not arn:aws:sns:REDACTED:REDACTED:ye-sns-topic-2-demo-china-cnn1\n\tstatus code: 40I**
How can we reproduce it?  It's always reproducible. You just need to create/delete SNS topic on **aws region cn-north-1 (china).**
What environment did it happen in?
Crossplane Version: docker.io/crossplane/crossplane:v1.13.2
Provider Version: xpkg.upbound.io/upbound/provider-aws:v0.38.0
Kubernetes Version: 1.27
Kubernetes Distribution: EKS
**Notes:**
It doesn't work due to hardcoded aws partition id (aws) and not aws-cn.
I believe it's general issue also in many other resources. You need to add ability to pass aws partition id as parameter (aws is default)

**Comment by yebolenko** [comment]
As I said above, it seems that we already have similar issue (with the same root cause, that hardcoded aws partition is used) for GOV
https://github.com/upbound/provider-aws/issues/757

**Comment by turkenf** [comment]
Hi @yebolenko,

Thank you for raising this issue, it can be reproducible with the following MR:

```
apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: sns
spec:
  forProvider:
    region: cn-north-1
```

This issue will be sorted and handled according to the prioritization policy.

**Comment by yebolenko** [comment]
Fatih, thank you. Please let me know when it will be resolved. As I said, it's not only SNS. It's a general issue with hardcoded aws partition Id (**aws:**) and I believe that some global fix is required (which will fix in general special regions such as China  and AWS GOV)

**Comment by cnshadzh** [comment]
The issue still exists, failed to create sns topic in region cn-northwest-1 with the same error.

**Comment by feifei-xu** [comment]
I cross the similar issue to create Policy using provider IAM. I set the region as cn-northwest-1, also I create providerConfig to set the partition to aws-cn
```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: iam
spec:
  credentials:
    source: PodIdentity
  endpoint:
    partitionId: aws-cn
    signingRegion: cn-northwest-1
    source: Custom
    url:
      type: Dynamic
      dynamic:
        host: amazonaws.com.cn
        protocol: https
```
but the partition still is aws, not aws-cn.
