### ISSUE TITLE
RDS Cluster needs KMS ARN instead of KMS Key ID

### ISSUE THREAD

**Issue by cristicalin** [crossplane-contrib/provider-upjet-aws#892]
### What happened?

In a composition which contains a KMS key and an RDS cluster I expected to be able to use the `kmsKeyIdSelector` key of the RDS cluster to properly match the KMS key in the composition. Unfortunately the query used seems to fetch the KMS Key ID instead of the ARN. I suspect the issue si somewhere around https://github.com/upbound/provider-aws/blob/main/apis/rds/v1beta1/zz_cluster_types.go#L441 but I lack sufficient understanding of how the provider code works at the moment to provide a solution.

### How can we reproduce it?

1. Create a composition with a KMS key and and RDS cluster
2. In the RDS cluster set the following for `spec.forProvider`:

```
kmsKeyIdSelector:
  matchControllerRef: true
```

Instantiate a claim for that composition and see this error in the cluster status:

```
observe failed: cannot run refresh: refresh failed: "kms_key_id" (mrk-4847128a609f4ba981df90ecfff90907) is an invalid ARN: arn: invalid prefix:
```

Complete resource example:

```
    - name: kms-key
      base:
        apiVersion: kms.aws.upbound.io/v1beta1
        kind: Key
        spec:
          forProvider:
            deletionWindowInDays: 7
            multiRegion: true
          providerConfigRef:
            name: provider-aws-upbound-kms
      patches:
        - type: PatchSet
          patchSetName: location
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-key"
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Cluster
        spec:
          forProvider:
            allowMajorVersionUpgrade: true
            applyImmediately: true
            kmsKeyIdSelector:
              matchControllerRef: true
            storageEncrypted: true
            masterUsername: root
            manageMasterUserPassword: true
            masterUserSecretKmsKeyIdSelector:
              matchControllerRef: true
            skipFinalSnapshot: true
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            vpcSecurityGroupIds:
              - sg-0a6dee57df5ea8255
          providerConfigRef:
            name: provider-aws-upbound-rds
      patches:
        - type: PatchSet
          patchSetName: location
        - type: PatchSet
          patchSetName: engine
        - type: PatchSet
          patchSetName: engineVersion
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.dbClusterParameterGroupName
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-cluster-parameter-group"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.dbInstanceParameterGroupName
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-db-parameter-group"
```

### What environment did it happen in?

* Crossplane Version: 1.13.2
* Provider Version: 0.40
* Kubernetes Version:  
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.7-eks-2d98532
```
* Kubernetes Distribution: 
```
EKS 1.26.7
```
