### ISSUE TITLE
Failure create AWS Aurora Cluster

### ISSUE THREAD

**Issue by rubenhak** [crossplane-contrib/provider-upjet-aws#901]
I'm trying to create an AuroraMySQL cluster. Getting an error:
```
apply failed: creating RDS Cluster (mysql-cluster): InvalidParameterCombination: DBClusterInstanceClass isn't supported for DB engine aurora-mysql. status code: 400
```

Used the following config:

```
apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: mysql-cluster
spec:
  forProvider:
    engine: aurora-mysql
    engineVersion: 8.0.mysql_aurora.3.04.0
    masterPasswordSecretRef:
      namespace: argocd
      name: mysql-creds
      key: MYSQL_PASS
    masterUsername: admin
    region: us-east-1
    skipFinalSnapshot: true
    dbClusterInstanceClass: db.t3.medium
  providerConfigRef:
    name: default  
```

Using `xpkg.upbound.io/upbound/provider-aws-rds:v0.41.0`

Thank you.
