### ISSUE TITLE
Lambda EventSourceMapping forProvider updated after apply with wrong params

### ISSUE THREAD

**Issue by shxdxwraze** [crossplane-contrib/provider-upjet-aws#907]
### What happened?

When creating `lambda.aws.upbound.io/v1beta1` `EventSourceMapping` without `destinationConfig` it autogenerated after the first successful apply and added into `forProvider` spec. As i know in terraform there is no such behavior.

### How can we reproduce it?

Apply this

```
apiVersion: lambda.aws.upbound.io/v1beta1
kind: EventSourceMapping
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    eventSourceArn: >-
      arn:aws:dynamodb:eu-central-1:ACC_ID:table/example/stream/*
    functionName: arn:aws:lambda:eu-central-1:ACC_ID:function:example
    region: eu-central-1
    startingPosition: LATEST
  providerConfigRef:
    name: aws-upbound-lambda
```

After successful apply you will get this

```
apiVersion: lambda.aws.upbound.io/v1beta1
kind: EventSourceMapping
metadata:
  name: example
status:
  atProvider: {}
  conditions:
    - lastTransitionTime: '2023-10-03T22:04:20Z'
      reason: Creating
      status: 'False'
      type: Ready
    - lastTransitionTime: '2023-10-03T22:06:29Z'
      message: >-
        observe failed: cannot run refresh: refresh failed: Missing required
        argument: The argument "destination_arn" is required, but no definition
        was found.
      reason: ReconcileError
      status: 'False'
      type: Synced
    - lastTransitionTime: '2023-10-03T22:05:29Z'
      reason: Success
      status: 'True'
      type: LastAsyncOperation
    - lastTransitionTime: '2023-10-03T22:04:25Z'
      reason: Finished
      status: 'True'
      type: AsyncOperation
spec:
  deletionPolicy: Delete
  forProvider:
    batchSize: 100
    destinationConfig:
      - onFailure:
          - {}
    enabled: true
    eventSourceArn: >-
      arn:aws:dynamodb:eu-central-1:ACC_ID:table/example/stream/*
    functionName: arn:aws:lambda:eu-central-1:ACC_ID:function:example
    maximumRecordAgeInSeconds: -1
    maximumRetryAttempts: -1
    parallelizationFactor: 1
    region: eu-central-1
    startingPosition: LATEST
  initProvider: {}
  managementPolicies:
    - '*'
  providerConfigRef:
    name: aws-upbound-lambda
```

### What environment did it happen in?

* Crossplane Version: 1.13.2
* Provider Version: 0.41.0
* Kubernetes Version: 1.24
* Kubernetes Distribution: EKS
