### ISSUE TITLE
Lambda Alias does not expose name property

### ISSUE THREAD

**Issue by kaofelix** [crossplane-contrib/provider-upjet-aws#911]
### What happened?

When creating lambda Aliases, it's missing the `name` property in the `forProvider` section to set the name of the Alias. The resource name from the `metadata` session is used instead. This means:
- We can't follow our resource naming scheme for lambda aliases, without trickling the name down to the aliases themselves
- We can't use the same alias name for two different functions, as there is a name clash between the resources
- Our CI/CD pipelines then cannot rely in the consistency of alias naming for automation

### How can we reproduce it?

Create two lambda Alias resources with the same name, but pointing to different functions, as part of the same deployment.

```
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Alias
metadata:
  name: production
spec:
  forProvider:
    functionNameSelector:
      matchLabels:
        testing.upbound.io/example-name: my_first_function
   <...>
```

```
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Alias
metadata:
  name: production
spec:
  forProvider:
    functionNameSelector:
      matchLabels:
        testing.upbound.io/example-name: my_first_function
   <...>
```

It won't work since there will be a name clash between the two resources.
