### ISSUE TITLE
CloudFormation - Issue Importing Existing Stack

### ISSUE THREAD

**Issue by stefan01** [crossplane-contrib/provider-upjet-aws#934]
### What happened?

I am currently facing the issue, that I am unable to import an existing CloudFormation Stack.
Creating a new one works as expected, but adding the `crossplane.io/external-name` annotation does not
attach an already existing resouce.
When I add `managementPolicies: ["Observe"]` to the Managed Resource, I am receiving the following status:
```
status:
  atProvider: {}
  conditions:
    - lastTransitionTime: '2023-10-25T07:58:17Z'
      message: 'observe failed: external resource does not exist'
      reason: ReconcileError
      status: 'False'
      type: Synced
```
The Stack definetly exists. As external-name I tried to use the stack id (ARN), stack name and the id (last part of the arn after `/`).

### How can we reproduce it?

1. Create a simple **new** Stack Managed Resource:
```
apiVersion: cloudformation.aws.upbound.io/v1beta1
kind: Stack
metadata:
  name: cf-test
  annotations:
    crossplane.io/external-name: arn:aws:cloudformation:xxxx:xxxxx:stack/cf-test/xxxxxxxxx-xxxxxxxx-xxxxxxxx-xxxxxxxx
spec:
  deletionPolicy: Orphan
  forProvider:
    name: cf-test
    region: eu-west-1
    templateBody: >
      {
        "Resources" : {
          "testParam": {
            "Type" : "AWS::SSM::Parameter",
            "Properties" : {
              "Type": "String",
              "Name": "/cf-test",
              "Value": "testing"
            }
          }
        }
      }
```

2. Copy the external-name annotation from the status

3. Delete the Managed Resource (The Cloud Formation Stack will not be deleted because of `deletionPolicy: Orphan`)

4. Create a new Managed Resource, which should attach to the existing Stack
```
apiVersion: cloudformation.aws.upbound.io/v1beta1
kind: Stack
metadata:
  name: cf-test
  annotations:
    crossplane.io/external-name: arn:aws:cloudformation:xxxx:xxxxx:stack/cf-test/xxxxxxxxx-xxxxxxxx-xxxxxxxx-xxxxxxxx
spec:
  managementPolicies: ["Observe"]
  forProvider:
    name: cf-test
    region: eu-west-1
    templateBody: >
      {
        "Resources" : {
          "testParam": {
            "Type" : "AWS::SSM::Parameter",
            "Properties" : {
              "Type": "String",
              "Name": "/cf-test",
              "Value": "testing"
            }
          }
        }
      }
```

### What environment did it happen in?

* Crossplane Version: v1.13.2
* Provider Version: v0.42.0
* Kubernetes Version: 1.26
* Kubernetes Distribution: EKS

**Comment by BartoszZawadzki** [comment]
This also happens when trying to `Observe` a `Certificate` (`acm.aws.upbound.io/v1beta1`):

```
Message:               observe failed: failed to observe the resource: [{0 reading ACM Certificate (3ab4ec14-7274-4095-b9c3-fb4c474da576): operation error ACM: DescribeCertificate, https response error StatusCode: 400, RequestID: bbc9954f-d065-4a09-9269-e8b01696f1f7, api error ValidationException: 1 validation error detected: Value '3ab4ec14-7274-4095-b9c3-fb4c474da576' at 'certificateArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:[\w+=/,.@-]+:acm:[\w+=/,.@-]*:[0-9]+:[\w+=,.@-]+(/[\w+=,.@-]+)*  []}]
```

It would seem that "" (double-quotes) are expected to be passed-on but are stripped in the process.

**Comment by achernev** [comment]
I'm having the same problem. I got it to load the existing stack by providing the Stack ID in the annotation, and the Stack Name in `forProvider.name`, like this:

```yaml
apiVersion: cloudformation.aws.upbound.io/v1beta1
kind: Stack
metadata:
  name: httpbin-test-observed
  annotations:
    crossplane.io/external-name: "af390330-dcce-11ef-8c94-0a3c9fb19ddb"
spec:
  managementPolicies:
    - Observe
  forProvider:
    name: "App-httpbin-test"
    region: "eu-west-2"
```

It seems to construct the stack ARN like this: `arn:<partition>:cloudformation:<region>:<account id>:stack/<forProvider.name>/<annotation value>`.
This is still not ideal, however, because the Stack ID must be known.
