### ISSUE TITLE
The SSM provider crashes the external secrets

### ISSUE THREAD

**Issue by dtelaroli** [crossplane-contrib/provider-upjet-aws#952]
### What happened?
The [provider ssm v0.43.1](https://marketplace.upbound.io/providers/upbound/provider-aws-ssm/v0.43.1) crashes the service [external secrets](https://github.com/external-secrets/kubernetes-external-secrets). Searching for the error, it seems related with some CRD, as described in this issue https://github.com/external-secrets/kubernetes-external-secrets/issues/563#issuecomment-732312285

Other providers are working fine, such: iam, sns, sqs and dynamodb.

## External secrets log:
```
> kubernetes-external-secrets@8.5.5 start /app
> ./bin/daemon.js

Error: Failed to get /openapi/v2 and /swagger.json: Created Component, but require templated one. This is a bug. Please report: https://github.com/silasbw/fluent-openapi/issues
    at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (/app/bin/daemon.js:35:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@8.5.5 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kubernetes-external-secrets@8.5.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-11-06T15_47_48_649Z-debug.log
```

### How can we reproduce it?

Install the provider and get the error.
```
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws-ssm
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ssm:v0.43.1
  controllerConfigRef:
    name: irsa-controllerconfig
```

### What environment did it happen in?

* Crossplane Version: 1.14.0
* Provider Version: 0.43.1 (tested 0.36.0 with no success)
* Kubernetes Version: 1.25.14
* Kubernetes Distribution: EKS
