### ISSUE TITLE
How to use least-privilege with AWS accounts 

### ISSUE THREAD

**Issue by RobCannon** [crossplane-contrib/provider-upjet-aws#954]
### What problem are you facing?

I am trying to make sure that we are using the principles of least privilege when using AWS roles in Crossplane.

### How could Official AWS Provider help solve your problem?
I don't think it is really possible.

Providers are all Cluster scopes and all Crossplane AWS resources are cluster scoped.  We want to allow developers to create resources in a constrained manner.  So maybe developers can create S3 resources, but not IAM or SecretManager resources.  Maybe they should be able to read only specific secrets.

So, I create a provider that has higher privileges and can create the secrets and IAM roles:
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws-low-privilege
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.accountId }}:role/k8s-xp-low-privledge
spec:
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:latest
  controllerConfigRef:
    name: provider-aws-low-privilege
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws-low-privilege
spec:
  credentials:
    source: IRSA
```

I am not even sure what links the ProviderConfig to a specific role at this point.  Is there anything or is there only one role used by the provider?

Assuming that I can create two ProviderConfigs that are bound to different AWS roles:

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-secretsmanager
spec:
  package: xpkg.upbound.io/upbound/provider-aws-secretsmanager:latest
  controllerConfigRef:
    name: provider-aws-high-privilege
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws-high-privilege
spec:
  credentials:
    source: IRSA
```

What would keep a developer from just using a high-privilege account?  If everything is Cluster level, how do I control access to a particular ProviderConfig?  Limiting an AWS role to a namespace is how we do this with something like Pulumi.
```
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: test-secret
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: provider-aws-high-privilege
```

Also, it really looks like I need to configure a Provider for each permutation of AWS resource type and AWS role?  It seems like the design here is really around all providers have god-mode access to their resources.

Am I missing something?
