### ISSUE TITLE
Unable to read S3 bucket - ObjectLockConfigurationNotFoundError

### ISSUE THREAD

**Issue by nicraMarcin** [crossplane-contrib/provider-upjet-aws#990]
Hi,

In S3 provider I have a lot fo warnings:
```
2023/11/29 06:36:28 [WARN] Unable to read S3 bucket (my-bucet-for-my-app-6529457) Object Lock Configuration: ObjectLockConfigurationNotFoundError: Object Lock configuration does not exist for this bucket
2023/11/29 06:39:04 [DEBUG] S3 bucket policy, read for bucket: my-bucet-for-my-app-6529457
2023/11/29 06:46:29 [WARN] Unable to read S3 bucket (my-bucet-for-my-app-6529457) Object Lock Configuration: ObjectLockConfigurationNotFoundError: Object Lock configuration does not exist for this bucket
2023/11/29 06:48:52 [DEBUG] S3 bucket policy, read for bucket: my-bucet-for-my-app-6529457
2023/11/29 06:56:37 [WARN] Unable to read S3 bucket (my-bucet-for-my-app-6529457) Object Lock Configuration: ObjectLockConfigurationNotFoundError: Object Lock configuration does not exist for this bucket
2023/11/29 06:58:48 [DEBUG] S3 bucket policy, read for bucket: my-bucet-for-my-app-6529457
```
Bucket status
```yaml
status:                                                                                                                                                                           
  atProvider:                                                                                                                                                                     
    accelerationStatus: ""                                                                                                                                                        
    arn: arn:aws:s3:::my-bucet-for-my-app-6529457                                                                                                                                  
    bucketDomainName: my-bucet-for-my-app-6529457.s3.amazonaws.com                                                                                                                 
    bucketRegionalDomainName: my-bucet-for-my-app-6529457.s3.eu-central-1.amazonaws.com                                                                                            
    forceDestroy: true                                                                                                                                                            
    grant:                                                                                                                                                                        
    - id: f8e2b00d7842f3a0a4b50aad5238g2d677c1f69ffdf95e746e11662f25905357c                                                                                                        
      permissions:                                                                                                                                                                
      - FULL_CONTROL                                                                                                                                                              
      type: CanonicalUser                                                                                                                                                         
      uri: ""                                                                                                                                                                     
    hostedZoneId: Z21DNDDWPTQW6Q                                                                                                                                                  
    id: my-bucet-for-my-app-6529457                                                                                                                                                
    objectLockEnabled: false                                                                                                                                                      
    policy: '{"Statement":[{"Action":["s3:GetObject","s3:ListBucket"],"Effect":"Allow","Principal":"*","Resource":["arn:aws:s3:::my-bucet-for-my-app-6529457","arn:aws:s3:::cdn-s3-
bot-frontend-predev/*"],"Sid":"VisualEditor0"}],"Version":"2012-10-17"}'                                                                                                          
    region: eu-central-1                                                                                                                                                          
    requestPayer: BucketOwner                                                                                                                                                     
    serverSideEncryptionConfiguration:                                                                                                                                            
    - rule:                                                                                                                                                                       
      - applyServerSideEncryptionByDefault:                                                                                                                                       
        - kmsMasterKeyId: ""                                                                                                                                                      
          sseAlgorithm: AES256                                                                                                                                                    
        bucketKeyEnabled: false                                                                                                                                                   
    tags:                                                                                                                                                                         
      crossplane-kind: bucket.s3.aws.upbound.io                                                                                                                                   
      crossplane-name: my-bucet-for-my-app-6529457                                                                                                                                 
      crossplane-providerconfig: aws-provider                                                                                                                                     
    tagsAll:                                                                                                                                                                      
      crossplane-kind: bucket.s3.aws.upbound.io                                                                                                                                   
      crossplane-name: my-bucet-for-my-app-6529457                                                                                                                                 
      crossplane-providerconfig: aws-provider                                                                                                                                     
    versioning:                                                                                                                                                                   
    - enabled: false                                                                                                                                                              
      mfaDelete: false                                                                                                                                                            
  conditions:                                                                                                                                                                     
  - lastTransitionTime: "2023-11-27T15:09:38Z"                                                                                                                                    
    reason: Available                                                                                                                                                             
    status: "True"                                                                                                                                                                
    type: Ready                                                                                                                                                                   
  - lastTransitionTime: "2023-11-27T15:09:36Z"                                                                                                                                    
    reason: ReconcileSuccess                                                                                                                                                      
    status: "True"                                                                                                                                                                
    type: Synced                                                                                                                                                                  
  - lastTransitionTime: "2023-11-27T15:09:37Z"                                                                                                                                    
    reason: Success                                                                                                                                                               
    status: "True"                                                                                                                                                                
    type: LastAsyncOperation      
```

Environment:
EKS 1.27
provider-aws-s3 v0.44.0
GitOps approach ArgoCD 2.7
